### ISSUE TITLE
unresponsive at unexpected buffer stop

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#1]
When communicating with an extremely slow server or high latency the player stops buffering when the playhead reaches the end of the buffer.

jwplayer does behave better: it continues to buffer - although it can also be made unresponsive sometimes by pausing.

Demo by user: http://222.73.47.242:8088/bug/bufferstop.html

wireshark log: http://www.gikidy.com/wp-content/uploads/2012/08/wireshark1.jpg

See: http://flowplayer.org/forum/8/103085
especially: http://flowplayer.org/forum/8/103085#post-103143

**Comment by danrossi** [comment]
I'm trying to work the thing out but can't after going through the communication.  do you mean it hangs at the end on a buffer empty for http also ? I may have to provide the fix that I put in rtmp in the core so it's done for all providers.

**Comment by phloxic** [comment]
It's obviously a major problem with the server: it serves a 250 kbps movie with 42 kbps speed.

Today I also cannot reproduce the problem: The player does not stop buffering, it's just veeeeery slow and interrupted. On the day I could reproduce, and less so with jwplayer.

Not sure where the RTMPConnectionProvider comes from, it's all http, so I thought this might be worth investigating.

Will encourage user to comment here.

P.S. I gave a link to the wrong thread, sorry. Corrected above, and it's here: http://flowplayer.org/forum/8/103085

**Comment by danrossi** [comment]
Halfway through the stream or right at the end ? What is it exactly that jwplayer is doing that flowplayer doesn't stop at the end if its buffering ?

**Comment by danrossi** [comment]
unfortunately he isn't logging the correct classes. it is rebuffering pretty badly for me on a 100MB cable connection. Perhaps move to cloudfront or another cdn ? I'll see what happens at the end.

**Comment by danrossi** [comment]
it played the whole way through, if it buffers right at the end and not finish, I can put the code from the rtmp plugin which fixes the buffering hanging issue back into the core and should fix that problem. If it doesn't restart midway, then it's a server issue and adding extra code to work around that might not be worth it I reckon, and possibly can be done in the javascript.

**Comment by gikidy** [comment]
I'm curious fix can be done via javascript. 

In Javascript environment, it should not know when the buffer stop, 

From the phenomenon, player will continue to wait video data package come from sever. Request data from video sever can return with HTTP header including keep-alive timeout value, maybe we can use this value to reset video data request.

**Comment by gikidy** [comment]
At halfway the buffer stopped, and never come back again, :)

**Comment by danrossi** [comment]
Ok thank you. Please try and use a CDN, your server has issues delivering video. Or capture a buffer empty event with javascript, and create an interval to seek back a little bit if it fails to begin after a certain period of time.

**Comment by gikidy** [comment]
I don't think seek back a little bit works. While the buffer stops, seek back a little bit manually will also stop at previous buffer end position.

Also i don't think the root cause is video sever. While the net speed of client is slowly, this issue can also be reproduced. I ever found the flowplayer official website have the same issue.

Could you take a look at the original thread link as below?

http://flowplayer.org/forum/8/103085

**Comment by danrossi** [comment]
I can't follow that conversation i'm afraid. please reduce it all here. That demo isn't the best either as they are coming from blip.tv. I need console logs when the hang occurs if possible and you need to enable the org.flowplayer.controller.\* filter. its not a bug but you are hoping for work arounds, which means more code required added to the core. Any screenshots would do, so its sit there with a buffering animation ? How did you come to the conclusion jwplayer is different within the same circumstances ? I don't see the issue it will rebuffer and continue downloading. Perhaps also show screenshots of the resource browser as well which shows the download. I'll try one more time reducing my bandwidth.

**Comment by danrossi** [comment]
Most importantly is the file still downloading in the resource monitor. I reduced my bandwidth to 48k , its clearly downloading, but obviously not playing back waiting for it to download. perhaps try fiddling with the buffertime settings also. I was unable to ping your server to determine your latency. I still think it's on a high latency connection, I tested downloading and i was getting 25k/s download on a 100MB connection and 75k/s on my EC2 server.

**Comment by danrossi** [comment]
I let it play the whole way through it eventually got there :) No hanging. Probably worth checking if its still downloading in the resource monitor console.

**Comment by gikidy** [comment]
I'm trying to combine JWplayer and flowplayer with the same page to reproduce the issue. But sames in the same page and the same link for request video data, the browser will combine it to only one request. So i'm afraid i cannot give out an sample in the same page that JWPlayer works well but Flowplayer has issue. 

And here i must clarify i don't have any view for which one is better, in fact i choose flowplayer as my video website video player solution. :)

Maybe you can ask Christian Ebert for some information of reproduce it, he ever reproduced it. 

Then the snapshot of buffer stops and the buffering animation is going on as following:
<img src="http://www.gikidy.com/wp-content/uploads/2012/08/111.jpg"></img>

The snapshot of network request for long time and finally failed. 
<img src="http://www.gikidy.com/wp-content/uploads/2012/08/222.jpg"><img>

The snapshot for console output. 

<img src="http://www.gikidy.com/wp-content/uploads/2012/08/3333.jpg"> </img>

**Comment by danrossi** [comment]
Hmm, you are playing back in the cache from the looks of it so it's not even downloading from the server right, it clearly says failed, the bytes downloaded matches the total and of course flash dispatches a stop event. Still nothing we can do right now until we can actually see the problem. Flash is dispatching stop for some reason or another that's not from the player. I'll try and run tests in chrome / windows 7 but I will have to try and find a throttler for windows.

**Comment by gikidy** [comment]
It's a little bit strange, i'm not understand why you say i'm playing back in the cache? Could you help to give out some comments for that? Thanks a lot.

**Comment by gikidy** [comment]
BTW, i just test the behavior under Linux(Ubuntu 11.10) environment, the result same as Windows.

**Comment by danrossi** [comment]
You are losing your wireless / internet connection intermittently. I am able to display what your have if I simply turn my wireless off.

**Comment by gikidy** [comment]
So if you just turn off the internet connection during playing, the player will show buffer complete on progress bar just like the snapshot i provided previously? 

Please notice the snapshot for this issue, the player show it has buffer completed on progress bar, but the buffer animation is showing, and also the player is in play mode.

I'm trying to narrow down this issue, if i use a download tool to download the video, it can always finish download. So i don't think this is sever or network issue.

If you cannot reproduce this issue, could you help to provide me maybe a patch for if client detect network timeout then do a reconnect? I can help to test it under my environment.

**Comment by danrossi** [comment]
Hi i would do this as a custom http provider plugin or customise the sources. I just tested out jwplayer and it also sits in a buffering state. The issue the player with http will dispatch the play button on a stop event but when it's at the end of the stream which is the normal place it would be. After this call flash is also triggering a buffer empty event therefore showing the buffering animation because http is stateless it has no idea about client disconnections, there is some code I made in the rtmp plugin to reconnect because it knows about this. Adding anything here my break the providers so best to be left as a customisation I think. It's events from flash controlling the player that is all. Ive had to provide a couple of reconnection customisations for people in the past also particularly for wowza.

**Comment by gikidy** [comment]
Hi, 
It's good enough for a custom http provider plugin/or a patch to source code to me. Thank you very much!

Could you help to tell me when will this patch available?

**Comment by gikidy** [comment]
Any update for this?

**Comment by phloxic** [comment]
I cannot speak for @danrossi - but in my personal opinion your server is simply to slow to serve video, even if it plays through I would give up "watching" it. Why don't you serve your media via a CDN? It's also not certain whether your server has other hiccups than just slowness.

I have set up a demo which seeks to 0 in the `onBufferEmpty` clip event here:
http://flowplayer.blacktrash.org/test/bufferempty.html
It also tries to seek to the previous position after a timeout. But the buffer is often lost - which does normally _not_ happen when you seek to 0. The player does not become unresponsive, it just loops the first few seconds. You can see it even better when you try some of the outcommented seek code: it sometimes works, and sometimes the buffer is lost although the controlbar often does not update that quickly. But when you click into an unbuffered portion the buffer disappears. I tried the outcommented code, and if you don't do anything sooner or later it starts playing again, but basically it behaves like with a damaged clip.

Again from my personal perspective this is not worth an official patch which potentially breaks lots of other things. Note your case is the first we have come across in years.

**Comment by danrossi** [comment]
Yes you misunderstood me, you would have to implement such things as a customisation job and because its http it has no idea the client connection has been cut to the server.

**Comment by phloxic** [comment]
@gikidy - you can ask @danrossi  to create a custom provider or plugin for you. You contact him here: http://www.electroteque.org/contact . But as I said, this will not be an official enhancement; therefore this issue is closed.
