### ISSUE TITLE
 events assigned to content plugin added at runtime dosnt work

### ISSUE THREAD

**Issue by a7madgamal** [flowplayer/flash#10]
i am using flowplayer-3.2.14.swf and flowplayer.controls-3.2.13.swf with flowplayer-3.2.11.js
OS:Ubuntu 12.04
Browsers: FF 15.0 and Chrome 12

when i call $f().loadPlugin('unique_key', "path/to/flowplayer.content-3.2.8.swf",
{
attr:value,
attr:value,
event:function(){alert('test');}
}
);
the plugin is added with the correct values but no events seems to work at all (onClick,onMouseOut,onMouseOver)
also when i check getConfig new plugins are not in the plugins array (although they are shown in the player)
do i have to recreate the player to enable plugin events?

kindly respond ASAP as i have a deadline soon
thanks alot

A.Gamal

**Comment by danrossi** [comment]
Hi did you try the actual callback event like onClick: function() {
            this.hide();
        }

see more here http://flowplayer.org/plugins/flash/content.html.

**Comment by a7madgamal** [comment]
i tried everything!
here is an example to show the problem:
http://jsbin.com/omitaz/8/edit

**Comment by a7madgamal** [comment]
any fix or workaround?

**Comment by danrossi** [comment]
Yes your example is exactly like putting it directly in the config, just load up a second content plugin named differently. this is a js api issue so needs to be tracked down.

**Comment by a7madgamal** [comment]
ok hopefully this gets fixed soon
amazing work by the way the flexibility of flowplayer is mind-blowing,keep it up!

**Comment by danrossi** [comment]
Does that work for you now ?

**Comment by anssip** [comment]
Unfortunate the player does not support this. When you load a plugin using loadPlugin() it strips out all function definitions from the supplied configuration.

Can you work around this by adding two content plugins into the configuration (and not use loadPlugin at all)? You can make the second one hidden initially and then bring it visible when you need to. Adding a plugin several times to the configuration does not cause any overhead, the player loads the plugin only once.

**Comment by a7madgamal** [comment]
the problem is that i add new plugins (like time markers) to the player when the user clicks on a button to add one
so i must add the markers after player load
anyway i worked around by using javascript links in the html attribute of the added plugins
still i think you should leave this bug opened and try to fix events as many users will make use of it :)
also fix 'this' scope in plugins html attribute as the functions called in the global scope

**Comment by danrossi** [comment]
It's in the javascript api section I believe not flash end where it binds events.
