### ISSUE TITLE
Slowmotion functionality with DVR (cached part) 

### ISSUE THREAD

**Issue by 99ers4ever** [flowplayer/flash#100]
I have the following problem: 

I'm trying to set up a livestream for sport events. I'm using AMS and DVR and I tried to get Flowplayer Slowmotion work for the part which is cached (to analyse it, if needed). 

Steps done: 
Testing DVR-functionality with http://www.osmf.org/configurator/fmp/ (works fine)

Livestream used: 
rtmp://hockey-news.info/dvrcast_origin
stream: test 

Occuring error: 
stream stops when trying to use slowmotion in cached part
DVR not working properly

I posted my configuration here: 
http://flash.flowplayer.org/forum/2/104815

So I'm not sure if it's bug or my configuration is wrong. 
I hope it's possible to get these two components work together. 

If you need any other information please contact me.

**Comment by danrossi** [comment]
The stream isn't available to test, let me know when it's back up. Have only tested slow motion support with VOD streams on DVR live streams create more complexities in terms of slow motion within buffers as the buffers are small.

**Comment by 99ers4ever** [comment]
hm just tested it - stream works for me. how did you try to test it?

**Comment by danrossi** [comment]
rtmp: {
                        url: "flowplayer.rtmp.swf",
                        netConnectionUrl: "rtmp://hockey-news.info/dvrcast_origin"
                    }

...

clip: {
                    url: "test",
                    live: true,
                    provider: 'rtmp'
                },

Using this config the stream does not play, its sitting there which means its not publishing.

**Comment by danrossi** [comment]
Hi the server is still down therefore unable to check it thanks.

**Comment by 99ers4ever** [comment]
I'm really sorry it took me so long to respond (busy with my bachelor thesis) - the server was crashed and is up again. checked it with your config and i was able to stream!

**Comment by danrossi** [comment]
alright thanks, can you leave it up until tommorow if possible there is likely a requirement on the fms side to get stepping working with DVR due to it being a live stream still theoretically and buffers. It steps within the buffer, and with live stream its small like 2 seconds or less to avoid latency between audio and video.

**Comment by 99ers4ever** [comment]
the server should be available all the time (someone destroyed the whole server config so i had to reinstall it  and that's the reason it wasn't working for you the last time) so yeah take the time you need :-)

**Comment by danrossi** [comment]
still unable to test what is the filename now.

**Comment by danrossi** [comment]
what is the updated filename ?

**Comment by 99ers4ever** [comment]
hm should be still the same! what software do you use to stream? 

i use FME 
my config: https://www.dropbox.com/s/p1bpsovtcb5a1ac/server.PNG
and I'm able to stream at the moment

**Comment by danrossi** [comment]
just tried again and its down 

netConnectionUrl: "rtmp://hockey-news.info/dvrcast_origin"

**Comment by 99ers4ever** [comment]
NOW it should work - hope the server stays alive for more than 24 hours ^^

**Comment by danrossi** [comment]
Hi I believe as of now fastplay only works with vp6 codec not h264 its not working for me on hds either. Contact wowza perhaps and that might change. the api should be the same for either rtmp or hds. Closing for now.
