### ISSUE TITLE
cluster: server clustering fails with wowza

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#101]
Demo:
http://flowplayer.blacktrash.org/test/cluster.html (HDDN)
Works fine with fms (cloudfront)

See also: http://flowplayer.org/forum/#!/moot/11121

**Comment by phloxic** [comment]
Seems to happen when the Wowza server runs a load balancer.

**Comment by carlosjpr** [comment]
The Dynamic Load Balancing of Wowza doesn't work when I use the clustering plugin of Flowplayer.
http://www.wowza.com/forums/content.php?108 - Dynamic Load Balancing Wowza
http://flash.flowplayer.org/plugins/streaming/cluster.html - Clustering RTMP Servers
NOTE: The dynamic load balancing of wowza works normally in flowplayer if I don't use the clustering plugin.
Examples:
Without Clustering (works): http://www.localmidia.com.br/flash/example-without-cluster.html
With Clustering (don't work): http://www.localmidia.com.br/flash/example-with-cluster.html

This problem has been related in 2011 on Wowza Forum, and it still doesn't work. If possible, see the explanation of this post: http://www.wowza.com/forums/showthread.php?14469-flowplayer-problem-with-origin-edge-amp-redirect-settings

**Comment by danrossi** [comment]
Yeah the plugin was made ages ago when load balancing was expensive, and required renting expensive routers for edge server setups. HDDN already has a load balancer and redirects to their internal servers. For some reason your version is trying to resolve files as http instead of rtmp will have to look at this.

**Comment by danrossi** [comment]
Just had a look, its doing a hddn style redirection style which may need to be handled the same.

**Comment by danrossi** [comment]
https://dl.dropboxusercontent.com/u/3394987/flowplayer.cluster-3.2.9.zip Please try this, it will now handle the redirects on the origin servers and update the current host to connect with. The issue is was not dealing with the connect reject status.

**Comment by carlosjpr** [comment]
Thanks danrossi! One more question! How do I use the clustering plugin with Adobe Http Streaming?

**Comment by danrossi** [comment]
Use the http clustering example the hosts config would be the separate manifest files.

**Comment by danrossi** [comment]
That fix is for wowza origin rtmp redirections.

**Comment by phloxic** [comment]
Cannot test because http://flash.dev94.flowplayer.us/plugins/streaming/cluster.html currently uses cluster-3.2.9 - and 3.2.11-dev (?) does not exist at http://flash.dev94.flowplayer.us/swf/
Reopening for testing - once cluster-3.2.11-dev is at http://flash.dev94.flowplayer.us/swf/flowplayer.cluster-3.2.11-dev.swf it can be tested at http://flowplayer.blacktrash.org/test/cluster.html (in conjunction with 3.2.17-dev core).

**Comment by phloxic** [comment]
ah ok, it's 3.2.10-dev - demo updated and working. Closing.

**Comment by phloxic** [comment]
Reopening: both http://flash.flowplayer.us/plugins/streaming/cluster.html and http://flash.dev94.flowplayer.us/plugins/streaming/cluster.html do not work in Chrome - endless loop.
Standalone demos might be easier to diagnose:
http://flash.dev94.flowplayer.us/demos/standalone/plugins/streaming/cluster-http.html
http://flash.flowplayer.us/demos/standalone/plugins/streaming/cluster-http.html

Other browsers available to me - Safari, Firefox, Opera are ok.

**Comment by phloxic** [comment]
Update: This only happens with Chrome's PepperFlash plugin - unfortunately it is enabled by default.

**Comment by phloxic** [comment]
I will open a separate issue for this - http://flash.dev94.flowplayer.us/demos/standalone/plugins/streaming/clustering.html - also gets stuck in an endless loop with PepperFlash.

**Comment by phloxic** [comment]
Closing in favour of #177
