### ISSUE TITLE
bitrateselect: does not work with playlists

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#102]
Demo: http://flowplayer.blacktrash.org/test/playlist-hdtoggle.html

**Comment by danrossi** [comment]
Nothing has changed for a while, requires sd, hd properties

bitrates: [
            {url: "mp4:ccc_trailer2-400", bitrate: 400, sd: true, isDefault: true},
            {url: "mp4:ccc_trailer2-1000", bitrate: 1000, hd: true}
          ],

**Comment by phloxic** [comment]
arrgh, sorry for the noise - closing of course.
