### ISSUE TITLE
remove fixed flash not found message from plugin code to settings

### ISSUE THREAD

**Issue by a7madgamal** [flowplayer/flash#11]
i wanted to change the missing flash message but found it hard coded into the plugin which is risky is we updated the plugin and lose the changes

i think its better to move this functionality to settings to be able to set deferent messages for different setups
thanks

**Comment by a7madgamal** [comment]
current code:
f.innerHTML = "<div class='notify warning'>Flash version " + n.version + " or greater is required" + (k[0] > 0 ? "Your version is " + k : "You have no flash plugin installed") + (f.tagName == "A" ? "Click here to download latest version" : "Download latest version from <a href='" + j + "'>here</a></div>");

**Comment by danrossi** [comment]
There has been a lot of requests for this, i'll let you know.

**Comment by a7madgamal** [comment]
i think you didnt get my point
my issue is related to flash plugin not installed at all,so flowplayer instead show a link to download flash (shown in the line of code in my previous comment)
the problem is the i want to change this message to a custom message other than the default one
to do so i had to change the flowplayer.js code which is not recommended because if we update to newer version we risk losing the custom message
if you move the message to configuration it will be much better in my opinoin :)
thanks

**Comment by a7madgamal** [comment]
not just the message but the whole error and link html

**Comment by danrossi** [comment]
Hi yes that's what I mean it's been setup as a feature request on the google bug tracker.
