### ISSUE TITLE
sharing/viralvideos: embedded players do not offer sharing by default

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#110]
To verify: http://flowplayer.blacktrash.org/test/embed-viral.html

I believe this is a leftover from the time when the pageUrl was not available consistent for both viralivideos and sharing plugins, and above all, was not always set by default to the originating page - see:
http://code.google.com/p/flowplayer-core/issues/detail?id=265

Therefore, as an intermediate stage sharing was disabled in embedded players, because there was no way to make sure the originating page would be shared by the embedded players.

This restriction has become obsolete with the consistent handling of clip.pageUrl and can be left out.

**Comment by anssip** [comment]
A version of viralvideos where sharing is enabled in embedded players is now in the dev site.

**Comment by phloxic** [comment]
Maybe, but we now have a more serious problem:
http://flowplayer.blacktrash.org/test/embed-viral.html - embedded from dev site http://flash.dev94.flowplayer.us/plugins/flash/viralvideos.html
There is stray code in the embed code, like: `%22callType%22%3A%22default%22` ...

**Comment by phloxic** [comment]
And the same _fix_ must be done for the sharing plugin.
Updating bug title.

**Comment by phloxic** [comment]
Sorry - caching issue. Viralvideos embed code works ok - what is the `callType` thing though?
And seems fine for sharing - at least with 3.2.16 (sorry) - can't test with 3.2.17 because of #159 :-(
But closing this one.
