### ISSUE TITLE
Send custom header

### ISSUE THREAD

**Issue by w3apps** [flowplayer/flash#111]
Is there any way to send custom headers when requesting a video file ? I'm using the pseudostreaming plugin and I tried to to add addHeader("Referer", "http://example.com"); in the httprequest.as file but It doesn't work.

**Comment by danrossi** [comment]
Hi there, that is for the byterange feature which has other complications because it uses a custom http client. For the normal streaming its not using a http client so no headers are sent. I would perhaps add the referer as a query string and deal with it on the server end.

**Comment by danrossi** [comment]
btw only some browsers do not send referer from flash. perhaps check which ones they are and add the query string.

**Comment by danrossi** [comment]
Closing this not much that can be done sorry.
