### ISSUE TITLE
Httpstreaming - Windows - Chrome Sandboxing - Requires "access your computer"

### ISSUE THREAD

**Issue by rdkls** [flowplayer/flash#115]
Note only on Windows, OSX I don't get it.

![windows-chrome-sandbox-prob](https://f.cloud.github.com/assets/1166229/646253/dcadeba0-d3c2-11e2-957d-9fd58165e0db.png)

If the user clicks [Deny], an entry is made in Chrome Settings - "Unsandboxed plug-in access" with value for the domain = "Block"

From then on, the player will get "DRM Error: 3321 : [i15nFailed]" or "DRM Error: 3368"
and just continually buffer.
The only way to fix it is follow the directions as in this Adobe post: http://helpx.adobe.com/adobe-access/kb/error-3321.html

Ideally, we could detect this error, and send the user to similar instructions.

Dan if you want access to BrowserStack to test with Windows I can give to you, let me know.

**Comment by danrossi** [comment]
Yes this cannot be helped it is a feature in windows chrome, the user simply has to click allow once for that domain. If they click deny you have to go all the way through the settings to change it to allow for the domain with those instructions above. There is noway to detect in flash this security box in chrome. 

I believe it's because 

1) windows is prone to virus
2) google have a stance against flash so "fixing what is not broken" therefore breaking the internet pretty much haha
3) flash is being scapegoated as a security hole when it's javascript that should be disabled ;)

**Comment by danrossi** [comment]
Oh you are possibly correct there, those two codes get returned during a rejection for authentication. This is not a feature of the httpstreaming plugin but I will look at adding it to the drm plugin.

**Comment by danrossi** [comment]
Ironically they have in their plugins list a remote desktop viewer that is enabled by default talk about security holes :O It's a strange world we live in.  

In the middle of testing it on the jwplayer version of the plugin first as I enabled user notification messages there first and will port those changes to flowplayer also.

**Comment by danrossi** [comment]
Confirming the codes fix the issue however it only happens on their built in and hacked up plugin. Not one supplied by adobe.

**Comment by danrossi** [comment]
Hi there this feature has been updated in the flash access drm plugin with the help of user notifications for drm errors.

http://flowplayer.electroteque.org/securedrm

When a user clicks deny it will popup a notification message on how to enable the domain again.

**Comment by rdkls** [comment]
Hey that's cool, it's nice of the player to try to help =)

But probably we should just hook into that event with a JS listener right,
in our playback page, and tell the user why it's not working, and what they
have to do in order to play back video.

Ideally, when our page first loads, if we detect a situation where the
authorization bar will happen, we'd preemptively show a floating dialogue
pointing to "Ok" and saying they'll have to click this in order to play
back video.

**Comment by danrossi** [comment]
No you have no way to detect the security banner has opened up its a hack in the flash plugin. The event will be returned after they have clicked deny.

**Comment by rdkls** [comment]
Right so any tips on implementing a proactive bubble pointing to 'Allow'
something like

"In order to watch this secure video you'll have to click 'Allow' here"

**Comment by danrossi** [comment]
Ive created javascript callbacks now for the various error events ;)

**Comment by rdkls** [comment]
ALL HAIL

**Comment by danrossi** [comment]
I would assume you have to do client checks then flash a message if they have just visited the site perhaps as the security banner happens once only for the domain. Thats what I would do anyway. And this other notification is for after the fact lol. Yes it would make things easier if it provided a flash event while the banner is popping up. There is no DRM client loaded until after sandbox access is given. The DRM client is part of the flash plugin that is what is needed to give access so it can store licences. 

Other peeps like widevine use a browser proxy plugin which is buggy and crap but circumvents around these restrictions obviouslly.

**Comment by danrossi** [comment]
How did you go ?  If you still do not want to use the drm plugin, you could look at making the modifications directly just grab the sources from my branch though ;) I fear if using flash shared objects instead to store the banner notification has been displayed will also trigger the security banner, if cookies get cleared the notification will appear again also. I'll also have a look at the possibility of this also.

**Comment by rdkls** [comment]
Cool thanks Dan, I'll have a talk with Ash about it tomorrow

**Comment by danrossi** [comment]
closing this for now.
