### ISSUE TITLE
Flash audio plugin does not recognise mp3 unless it sees a pattern of name.mp3 into the URL

### ISSUE THREAD

**Issue by thanosk** [flowplayer/flash#116]
Reproducible with version 3.2.10.

For example, if the URL of the mp3 is like: example.com/my/action?id=n, flowplayer responds with 200 stream not found. In order to overcome it, it is possible to use a fake get parameter like this:

example.com/my/action?id=n&ext=name.mp3

It's a bit crazy! :-)

**Comment by danrossi** [comment]
please provide page also you need to uri encode your urls.

**Comment by thanosk** [comment]
Oh, sorry, you are right :-)  There it is: http://lists.hellug.gr/audio-bug/demo.html

As you can see, it fires 3 flowplayers, the first one is fed with the absolute url to the mp3 file (current directory).
The 2nd one calls file.php?id=103 and fails.
The 3rd one calls file.php?id=103&ext=fake_empire.mp3 with success.

(they are not uri encoded but that doesn't seem to affect anything, we'll get the same results even if I change & to %26 etc ...)

The source code for file.php is shown here: http://lists.hellug.gr/audio-bug/file.html

ext is a dummy get parameter, it doesn't actually do anything. I kind of wild guessed it to be honest, I noticed that if I set file.php to serve flv (or f4v/m4v) files, it works as is. So my guess is that flowplayer might be looking for ".mp3" on the URLPath in order to fire the audio plugin and thought to add the dummy ext to give it a helping hand ;-) (I didn't go on debugging flowplayer to check if my guess is correct)

**Comment by danrossi** [comment]
try clip: { type: "audio" }

**Comment by thanosk** [comment]
Thank you, that works.
