### ISSUE TITLE
console.log extension, or debug plugin?

### ISSUE THREAD

**Issue by willwh** [flowplayer/flash#118]
Hi guys.

I've been running through the codebase, trying to understand completely how the logging interface works.

I'm using it happily - but I'd like to be able to do more than get the data in console, ideally I'd like to be able to use some javascript to send it to the page itself (i.e. jquery.append to a div or ul), not the console, or the flash object.

Is that possible?

**Comment by danrossi** [comment]
It simply calls console.log.

**Comment by willwh** [comment]
Thanks.

**Comment by danrossi** [comment]
You could possibly modify how this works within the Logger class. It's an externalinterface call to console.log. You could call "logfunction" instead.
