### ISSUE TITLE
BitrateSelect plugin "isDefault" not applied

### ISSUE THREAD

**Issue by nderambure** [flowplayer/flash#119]
Hi !

I'm testing Flowplayer (fash) with Wowza server, and after many tests, I can get the video live stream (from a webcam) to wowza and then to Flowplayer.

I use httpstreaming and a smil file on the Wowza server for bitrate selection.
Here is the smil file : https://gist.github.com/nderambure/6081829

And here is the Flowplayer config : 
https://gist.github.com/nderambure/6071678

I've specified that the 360p stream is the default one, but it's never applied. If I load the page with my player, the 160p stream is selected and running.
Note that I can change bitrate after loading, it works.

**Comment by danrossi** [comment]
https://dl.dropboxusercontent.com/u/3394987/flowplayer.httpstreaming-3.2.11-dev.zip
https://dl.dropboxusercontent.com/u/3394987/flowplayer.f4m-3.2.10-dev.zip
https://dl.dropboxusercontent.com/u/3394987/flowplayer.bwcheck-httpstreaming-3.2.13-dev.zip

use these thanks

**Comment by nderambure** [comment]
Thx @danrossi, it now works as expected.
Note that I don't use bwcheck here, only bitrateselect.

**Comment by danrossi** [comment]
That's ok the bwcheck updates is for the dynamic switching fixes. The one you want is the f4m updates.

**Comment by nderambure** [comment]
Hi @danrossi, will you release the new versions of f4m and httpstreaming soon ?
Did you work on it since 3 month, so I can test again with the new dev version ?
Thank you for your time !

**Comment by danrossi** [comment]
I believe it has all been merged into the dev branch now. Every single change and fix for the past 6 months is in there now.
