### ISSUE TITLE
rss: custom fp: namespace breaks any rss setup

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#120]
The feature to set e.g. clip properties in the fp:clip namespace - http://flash.flowplayer.org/documentation/configuration/playlists.html#flowplayer-specific-clip-properties-in-rss - is broken. Not only that, it prevents rss playlists from working it all.
Demo: http://flowplayer.blacktrash.org/test/fp-rss-namespace.html

**Comment by danrossi** [comment]
```
<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/" xmlns:fp="http://flash.flowplayer.org/rss">
```

set it to something bogus but needs the namespace setup or else it don't know what to parse try that.

**Comment by phloxic** [comment]
@danrossi - thanks, I guess I should read the docs I wrote myself ;-)
