### ISSUE TITLE
clip.onMetaDataChange - why?

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#122]
3.2.16 introduced the `onMetadataChange` - http://flash.flowplayer.org/documentation/version-history.html#3216-february-2013 - clip event.

Why a new clip event when the brselect, bwcheck and bwcheck-httpstreaming plugins already provide onStreamSwitch?
This should do:

``` js
onStreamSwitch: function () {
  var meta = this.getPlayer().getClip().metaData
}
```

However, it always returns the metadata for the isDefault clip (a bug imho).
Why I new method instead of fixing the existing one?

**Comment by danrossi** [comment]
Go back in the tickets it was introduced to prevent triggering onMetaData during switches because rtmp servers resend metadata callbacks after switch updates. Actually metadata callbacks on HDS too.

**Comment by phloxic** [comment]
I infer from this that indeed onMetadataChange is relevant for all _3_ of the following plugins: brselect, bwcheck, bwcheck-httpstreaming
You could make my life easier if you answered at https://github.com/flowplayer/work/issues/639 - e.g. regarding number of arguments, and if any, what they refer to.

I am aware of the tickets. And I wasn't talking about onMetaData, I was talking about calling getClip from within onStreamSwitch which is fired _after_ and not _during_ the switch. It seems getClip() does not grab the current clip in the sense of the current item, but the clip which was indeed active at onMetaData (which is fired at start, but not for stream switches).

But I will try to update docs like so:
- warn that getClip() always returns the isDefault clip in conjunction with brselect, bwcheck, bwcheck-httpstreaming (from the UI perspective this is still wrong imho, but so be it)
- warn that clip.onMetaData is not fired for stream switches
- document clip.onMetadataChange as additional clip event provided by the 3 plugins - once I have all the details (which I still have not)

**Comment by phloxic** [comment]
Right, I'm now actually testing this, and onMetaDataChange also only returns the isDefault clip.
Demo:
http://flowplayer.blacktrash.org/test/brmenu.html
The clip configuration contains:

``` js
onMetaDataChange: function (clip) {
  console.log(clip.url);
}
```

and it logs always the same url.
Promoting to bug.

**Comment by danrossi** [comment]
I just found time to search back it's related to this #50. I can take it out but you will be back to where we started it will dispatch metadata during each transition. its simply checking if metadata is already set on the clip and firing a different event. It also gets cleared to be reset when moving to a new playlist item. Did you still need this open ?

**Comment by phloxic** [comment]
Alright, I see `onMetaDataChange` now working in 3.2.17 dev. Closing.

**Comment by phloxic** [comment]
Ooops. Have to test this with bwcheck.

**Comment by phloxic** [comment]
Sorry, I have to reopen this.
`onMetaDataChange` is triggered ok when a stream switch happens - simultaneously with `onStreamSwitch`, but the `metaData` reported references the default clip, not the currently played.
So, in this case either `onMetaDataChange` is not the right place to find out about the current clip, or it is the right place, but it reports the wrong thing.

**Comment by danrossi** [comment]
I fixed it in the other ticket.

**Comment by phloxic** [comment]
In which ticket?
Is this about registering `onMetaDataChange` in the API?
I'm trying that now. Now it does nothing on stream switch.
http://flash.flowplayer.org/documentation/version-history.html#3216-february-2013 says:
"new clip event onMetadataChange [typo, I guess], dispatched for example when switching bitrate"
???

**Comment by phloxic** [comment]
AHA - after some wild cache-refreshing it works: http://flowplayer.blacktrash.org/test/brmenu.html
Good.
Of course only if @danrossi's revert at https://github.com/flowplayer/flash/commit/39430416dff9860551424772ad6b5877b9c1da00 is reverted again.

**Comment by danrossi** [comment]
Shall we close this. I took it out to follow the correct order of committing, I put it into a branch lol.

**Comment by danrossi** [comment]
I'll redo it onto the dev branch again which is what's been requested and close that pull request.

**Comment by danrossi** [comment]
it has been added.
