### ISSUE TITLE
error: flowplayer only loop clip when the current browser tab's active

### ISSUE THREAD

**Issue by sergeysavchuk** [flowplayer/flash#123]
When you have the below code to loop clip with flowplayer:

```
var player = flowplayer(id, {
            src: flowPlayerSource
        });

player.setClip({
        url: clipUrl,
        autoPlay: false,
        scaling: 'scale',
        onBeforeFinish: function () {
            return false;
        }
    });
player.play();
```

It works well when you on the current browser tab and don't leave its. But when you go to another tab and if at this moment your video comes to end player doesn't repeat the clip, it stops and displays a black screen.

**Comment by danrossi** [comment]
Please supply a demo page thanks.

**Comment by sergeysavchuk** [comment]
It only reproduced for specific flv files or when you set debug mode whith level info or debug; or  when you run heig-loaded script on any tabs of brouser.

You can reproduce it whith next steps:
1. Open the demo page: http://jsfiddle.net/a5yCs/9/;
2. Open another browser tab  and connect to any site
3. Make any actions on site (about 3 minutes)
4. Open a previous tab.

**Comment by danrossi** [comment]
I suspect the external interface which flash uses to interface with javascript gets disconnected when you move away from the tab. I still need a page that you are actually looking at, that link was unusable sorry broken stream.

**Comment by sergeysavchuk** [comment]
I'm sorry. I updated the demo page: http://jsfiddle.net/a5yCs/9/.

**Comment by danrossi** [comment]
The setup is a bit complex you should make it more basic, I had to change the stream still to this

http://videos.electroteque.org/big_buck_bunny_400k.mp4

, the callbacks are working for me, chrome osx. Please provide your environment.

**Comment by danrossi** [comment]
configure duration: 10 also to reduce it's length make it easier to debug.
