### ISSUE TITLE
rtmp: seeks of less than 0.2 sec are ignored

### ISSUE THREAD

**Issue by gmcnaughton** [flowplayer/flash#124]
As reported in http://flowplayer.org/forum/#!/moot/13085:

`NetStreamControllingStreamProvider#doSeek` has a check to ignore seeks of <  0.2 seconds. That makes frame-by-frame seeking impossible even if sufficient keyframes are available (users can't advance frame-by-frame at any granularity higher than 5fps).

What is tripping us up is this code in https://github.com/flowplayer/flash/blob/master/core/src/actionscript/org/flowplayer/controller/NetStreamControllingStreamProvider.as#L534:

```
if (Math.abs(seconds - time) < 0.2) {
  log.debug("current time within 0.2 range from the seek target --> will not seek");
  dispatchPlayEvent(ClipEventType.SEEK, seconds);
  return;
}
```

Any reason for the 0.2 second minimum?

**Comment by danrossi** [comment]
rtmp can override this. The base is mostly for http and where rtmp overrides alot of these. I'm not sure what the check was for I'm sorry but it has affected some things for wanting to seek on startup by the api etc. It's a check that 200ms of time has passed before allowing to seek.

**Comment by danrossi** [comment]
https://github.com/flowplayer/flash/blob/master/plugins/rtmp/src/actionscript/org/flowplayer/rtmp/RTMPStreamProvider.as according to the master branch it's already overriding it. Please explain the issue exactly.

**Comment by danrossi** [comment]
closing this for now
