### ISSUE TITLE
play(clip, instream) broken for rtmp clips

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#125]
Demo - simplified version of http://flash.flowplayer.org/demos/scripting/play-instream.html but via rtmp here:
http://flowplayer.blacktrash.org/test/rtmp-instream.html

Note that specifying the rtmp provider explicitly for the clip to be played does not help - in spite of the error message. There also should be no need to specify it as the rtmp provider is set in the common clip object.
Specifying full rtmp urls also does not help.

**Comment by bbbo** [comment]
@blacktrash : is this the outcome of http://flowplayer.org/forum/#!/moot/15621 ?

**Comment by phloxic** [comment]
@bbbo - no, this one is for Flowplayer Flash (support channel). The above moot is for Flowplayer HTML5 (wrong category).

**Comment by danrossi** [comment]
The error

"Error: 202, The provider specified in this clip is not loaded, Provider 'rtmpInstream' (if this instream clip was started using play() you need to explicitly load/configure provider 'rtmpInstream' before calling play()), clip: '[Clip] 'mp4:stsp''"

It's designed for ads to roll into a seperate stream / connection. Therefore configuring a second rtmp plugin as rtmpInStream: {} . Should correct this. Install a flash debug player and it will show these errors.

**Comment by phloxic** [comment]
It shows this error, but it wasn't clear that it should be a _second_ plugin.
Ok, will try that.

**Comment by phloxic** [comment]
Yes, that works.
Yes, must be documented that:
A dedicated rtmp plugin with the obligatory label "rtmpInstream" must be configured.

**Comment by danrossi** [comment]
Yeah thats how ova etc configure it.

**Comment by phloxic** [comment]
Closing this here then. Thanks for the info.

**Comment by danrossi** [comment]
That's ok I just noticed it wasn't flagged for me. Send them to me if you want me to look at them thanks or I won't answer them  ;)
