### ISSUE TITLE
bwcheck causes long videos to freeze frequently

### ISSUE THREAD

**Issue by edlabAdmin** [flowplayer/flash#126]
We use the bwcheck with the rtmp plugins for distributing our AWS videos via cloudfront. Recently we found an issue that all our long videos (1-2 hours) are freezing every now and then for 3-5 seconds. The occurrence of the freezing seems to have a regular pattern (in a given video the time span that each freezing occurs seems to be a constant value, but this time span differs between videos).

We figured out it was not the problem with Amazon as JW Player does not have the same problem in playing the same videos. The issue is with the "dynamic" configuration option of the "bwcheck" plugin. After we set "dynamic : false" the problem is gone. Please check your code and suggest how we can turn "dynamic" back on without causing the same problem.

**Comment by danrossi** [comment]
You've provided no page or console log output, but please try this dev build

https://dl.dropboxusercontent.com/u/3394987/flowplayer.bwcheck-3.2.13-dev.zip

Disable the screen size rule perhaps as it might be causing issue with the rules also and selecting a too high bitrate qos: {screen: false} let me know if that helps. 

Where are your streams coming from ? Are they on a CDN ? The closer you are the better really. It sounds like buffer problems you are experiencing no idea.

**Comment by edlabAdmin** [comment]
Hi danrossi, thanks for the reply. I followed your suggestion to set {screen: false} in "qos". This partially fixed the lagging problem. The video does not freeze when it is played from the beginning. However if I seek the video, the freezing comes back again. Our bitrate value is set to 800 which I think the default value in bwcheck.

Here is the page:

http://dev-ya.tc-library.org/wp-content/plugins/vialogues/vialoguesplayer/example/index2.html

Haven't tried your dev build yet but will do.

**Comment by danrossi** [comment]
Provide basic config that page is not helpful both have buffer issues likely keyframe / encoding / bitrate. Although its on cloudfront so i should be able to play a high rate from a local node.

**Comment by edlabAdmin** [comment]
ok I've added a basic configuration at the bottom (the third video) using the basic components (rtmp+bwcheck plugins). For your convenience to debug, the player instance var is 'video_obj2'.

The actual video is 1.3G with 1h19m48s in length. So the average bitrate should be something like 2200K (1300 \* 8 / 4788). 

The curious thing is I found if I use the correct bitrate value 2200 (which is unfortunately not yet available in our infrastructure) instead of the default 800, it seems the lagging issue is less likely to happen. Do you think this is the cause?

**Comment by danrossi** [comment]
you've configured dynamic switch streaming with only one bitrate configured so of course it's going to be a problem set a min of 3.

**Comment by edlabAdmin** [comment]
Thanks a lot Dan! Following your suggestion, I avoid using bwcheck when there is only one bitrate stream. The slowed video loading seems to be gone after a week's testing.
