### ISSUE TITLE
bwcheck: on empty buffer switches down to lowest bitrate

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#127]
With streams which are not completely optimized for multibitrate deployment in the sense that they contain extreme bitrate peaks (keyframe synchronicity ok) - the following can be observed:

Sometimes the buffer is empty -> buffer animation -> bitrate switches first down to lowest and only the to the next lowest bitrate.

i.e. it goes e.g from 1300 -> 350 -> 1000 - instead of simply 1300 -> 1000 and only going further down if needed.

A bit hard to reproduce, but I can observe this here: http://flowplayer.blacktrash.org/test/bwcheck-dynamic.html in fullscreen - ca. at 55:30 mins onwards. Users also noticed this behaviour with their videos.

**Comment by danrossi** [comment]
https://dl.dropboxusercontent.com/u/3394987/flowplayer.bwcheck-3.2.13-dev.zip try the dev version with the osmf 2 changes.

The sufficient bandwidth rule is also dictated by dropped frames it seems in which the min setting is 10 with minDroppedFrames. 

It's set to reset the index it seems to switch down so will go back to the lowest to start switching up again.

**Comment by phloxic** [comment]
"It's set to reset the index it seems to switch down so will go back to the lowest to start switching up again."
So the behaviour is intentional?

**Comment by danrossi** [comment]
According to the osmf classes the default index is -1 until one of the rules picks up what index to collect. Either one of them could be resetting it back to -1 but no idea. At least try the newer versions perhaps they made improvements for rtmp also. It works fine for me. The dropped frame setting above also affects the sufficient bandwidth rule, try and fudge it to something really high and see if that helps ?

**Comment by phloxic** [comment]
Will play around with it.
I also have some ideas as to optimized video encoding for bwcheck - similar to what I'm using for hls. The hls specs are slightly clearer because they require the _maximum_ bitrate in the manifest spec. Whereas here one usually gives the average bitrate. This will take longer to test though.

**Comment by danrossi** [comment]
The fallback indexes may required to be tweaked on the rules but im not sure yet and its hard to debug those. They can all be overridden though if needed. We are only overriding the sufficient bandwidth rule to allow configuring a few details. There is the qos monitor plugin which may help expose these details in regards to the dropped frames but I doubt they could reach over 10 or could they ? If so it could be falling back regardless if there is sufficient bandwidth. I could comment that check out also perhaps.

**Comment by danrossi** [comment]
And regards to hls I'm not sure if the max bandwidth setting has any affect with rtmp but give it a try. Maybe for HDS as it's segmented http streaming. This is what is used to configure the mbr HLS feeds anyway the max bandwidth. HLS suffers with offset issues though when segmenting depending what tool is doing it.  it needs to start at a specific offset on the first fragment which is usually the duration length.

**Comment by phloxic** [comment]
So far I haven't seen any behaviour change with the dev version.
I have not trouble with HLS encoding, with enforced key frame interval and some other tweaks it works like a charm.
Capping bitrate and bufsize should help in rtmp too against dropped frames or buffering. Simple: if a bitrate of 500 is declared and peaks of 1500 or more encountered, that may cause trouble imho.

**Comment by phloxic** [comment]
To the issue at hand: setting qos waitDurationAfterDownSwitch to a low value improves the behaviour inasmuch as the lowest bitrate isn't stuck that long.

**Comment by danrossi** [comment]
ok I figured out something that might work without trying to change too much of how it chooses the indexes. the buffer empty rule can be ignored completely or i'll change this empty buffer rule scale factor to be configurable. Its doing a bitrate \* 0.4 to get the recommendation currently. If I change this to 0.8 as default that might help ?

**Comment by danrossi** [comment]
I set it to be on the safe side to 0.6 which say at 1500 recommend 900. This can be changed to 0.8 as default. 

https://dl.dropboxusercontent.com/u/3394987/flowplayer.bwcheck_httpstreaming-3.2.13-dev.zip

New setting

qos: {
   bufferScaleDownFactor: 0.6
}

**Comment by phloxic** [comment]
Is this for bwcheck only or for bwcheck-httpstreaming too?

**Comment by phloxic** [comment]
And is this now in dev for 3.2.17 and do we have to document qos.bufferScaleDownFactor?

**Comment by danrossi** [comment]
its for HDS only. Those metric properties for HDS are constants I just made that one configurable. Are you able to confirm if it helps alleviate the issue when you have a moment.

**Comment by phloxic** [comment]
I don't have a HDS bitrate array sample. The bug was original filed for RTMP and "normal" bwcheck.

**Comment by danrossi** [comment]
crap. OK well the default osmf code is set to use the lowest index if its less than the qos.minBufferLength setting which is 2. If it's less than 2 it might be unstable to make it go back one index so its there for a reason. I can make it go back one to test I guess.

**Comment by danrossi** [comment]
https://dl.dropboxusercontent.com/u/3394987/flowplayer.bwcheck-3.2.13-dev.zip
https://dl.dropboxusercontent.com/u/3394987/flowplayer.bwcheck_httpstreaming-3.2.13-dev.zip
https://dl.dropboxusercontent.com/u/3394987/flowplayer.rtmp-3.2.12.zip

I replicated some buffer optimisation in rtmp like hds also.

**Comment by anssip** [comment]
The version is here: http://flash.160f.flowplayer.me

**Comment by anssip** [comment]
merged to dev version, now here http://flash.dev94.flowplayer.us

Closing this.

**Comment by phloxic** [comment]
Is `qos.bufferScaleDownFactor` an option now? If yes, is it present in both bwcheck and bwcheck-httpstreaming?

**Comment by phloxic** [comment]
@danrossi - ping, please answer: "Is qos.bufferScaleDownFactor an option now? If yes, is it present in both bwcheck and bwcheck-httpstreaming?"
