### ISSUE TITLE
brselect + bwcheck checkOnStart + fms: broken

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#128]
http://flowplayer.blacktrash.org/test/bwcheck-brselect.html
works with wowza, but not with fms.
Without brselect checkOnStart is ok.

**Comment by phloxic** [comment]
http://flowplayer.org/forum/#!/moot/16147

**Comment by phloxic** [comment]
Same problem with dev bwcheck from https://dl.dropboxusercontent.com/u/3394987/flowplayer.bwcheck-3.2.13-dev.zip - detected bitrate undefined.

**Comment by danrossi** [comment]
Nothing wrong with it here

  urlResolvers: ["bwcheck","brselect"],

[LOG] time 17:36:12.347 :: org.flowplayer.bwcheck.detect::BandwidthDetectorFms : onBWCheck
[LOG] time 17:36:13.431 :: org.flowplayer.bwcheck.detect::BandwidthDetectorFms : onBWCheck
[LOG] time 17:36:13.738 :: org.flowplayer.bwcheck.detect::BandwidthDetectorFms : onBWCheck
[LOG] time 17:36:13.740 :: org.flowplayer.bwcheck.detect::BandwidthDetectorFms : onBWDone() 949,0,0,590
[LOG] time 17:36:13.742 :: org.flowplayer.bwcheck::BwCheckProvider : onDetectorComplete()
[INFO] time 17:36:13.743 :: org.flowplayer.bwcheck::BwCheckProvider : 

 kbit Down: 949 Delta Down: undefined Delta Time: undefined Latency: 590

Cloudfront FMS has a bug so it needs to trigger the callback many times until it returns a value. 

https://dl.dropboxusercontent.com/u/3394987/flowplayer.bwcheck-3.2.13-dev.zip

was fixed ages ago. Perhaps it's just the order of the resolver but try this file also.

**Comment by phloxic** [comment]
What was unclear about https://github.com/flowplayer/flash/issues/128#issuecomment-22863557 ? I tried the dev version.
http://flowplayer.blacktrash.org/test/bwcheck-brselect.html now uses the dev version from dropbox, same problem.

**Comment by danrossi** [comment]
^ look at the config above. working here see the console log.

**Comment by phloxic** [comment]
With the right order it resolves correctly - but still reporting undefined on BwDone. Again no difference between 3.2.12 and 3.2.13-dev

**Comment by phloxic** [comment]
So it seems the bug is only the wrong bitrate report in onBwDone.

**Comment by danrossi** [comment]
onBwDone: function (mappedBitrate, detectedBandwidth) {
      console.log(mappedBitrate);
       console.log(detectedBandwidth);
}

the cloudfront servers seem to randomly fail the connection therefore it will default back to the default mapped bitrate. The arguments were not correct, this is how its used.

**Comment by phloxic** [comment]
Oops - some old config interfering. All's fine even with current flowplayer.bwcheck-3.2.12.swf - sorry for the noise.
