### ISSUE TITLE
bwcheck-httpstreaming : bad track selection

### ISSUE THREAD

**Issue by itusersvidiatorcom** [flowplayer/flash#129]
Issue : on non stable connection, track selection is too optimistic and making the player periodically stop playing, waiting for buffering

Solution : Client download speed should be statistically defined and not for optimal connection. flowplayer.bwcheck-httpstreaming-3.2.12.swf should select a track that he can download in time to be able to continuesly play back content without the need to pause for buffering.

Details :
Full live page : http://hkvmpwap.strim.co:8080/strim/playerpweb?mediaItem=501&pId=1&pV=0
You may find my minimalistic test page code here : http://pastebin.com/e30rbR2i
f4m file : http://pastebin.com/gkDQ7S0S
Server provides tracks : 404 kbps / 550kbps / 794 kbps / 1039 kbps / 1283kbps
As you can see in this image, player selected as first fragment 404 kbps. Then he switched to 1283kbps segments. To download 50 seconds of video content it took him 53 seconds, then he switched back to 404 kbps.
![flowplayerbwcheckplugin2](https://f.cloud.github.com/assets/5269183/992848/7afbd78a-0989-11e3-8c96-e4ace8904483.png)

Our issue is that player keeps repeating the same mistake : jump to highest available track, realize he can't keep downloading content, jump back to lowest track. 
A solution would be to statistically calculate download time of a segment and try to not repeat the same mistake over and over. If player can't download 1283 kbps track, then try to use 794 kbps track in the future.

**Comment by danrossi** [comment]
https://dl.dropboxusercontent.com/u/3394987/flowplayer.bwcheck-httpstreaming-3.2.13-dev.zip
https://dl.dropboxusercontent.com/u/3394987/flowplayer.httpstreaming-3.2.11-dev.zip
https://dl.dropboxusercontent.com/u/3394987/flowplayer.f4m-3.2.10-dev.zip

try this thanks

**Comment by itusersvidiatorcom** [comment]
quick feedback : i can see a large improvement in behavior. Will forward the build to QA to make a larger test. Thanks so far.

**Comment by phloxic** [comment]
See also: http://flowplayer.org/forum/#!/moot/16369

**Comment by itusersvidiatorcom** [comment]
QA confirmed that the behavior is as expected from DBA. There are very few cases when player got stuck on lowest track for a while, but this not a bug, just a situation.
I can also confirm that subtitle desync issue is resolved in this build.
Hope to see these changes in next release build.
