### ISSUE TITLE
Replaying instream rtmp "Error in Actionscript"

### ISSUE THREAD

**Issue by alexcroox** [flowplayer/flash#131]
My configuration:

```
player = flowplayer("livestream", appPath+"public/js/third_party/flowplayer/flowplayer-3.2.16.swf", {
    clip: {
        live: true,
        provider: 'customrtmp',
        autoBuffering: true,
        bufferLength: 0,
        fadeInSpeed: 0,
        url: 'stream0'
    },         
    plugins: {
        customrtmp: {
            url: appPath+"public/js/third_party/flowplayer/flowplayer.rtmp-3.2.12.swf",
            netConnectionUrl: 'rtmp://xxx/big/',
            inBufferSeek: false
        },
        customrtmpInstream: {
            url: appPath+"public/js/third_party/flowplayer/flowplayer.rtmp-3.2.12.swf",
            netConnectionUrl: 'rtmp://xxx/big/',
            inBufferSeek: false
        },
        controls: null
    },
    canvas: {
        backgroundGradient: 'none',
        backgroundColor: 'transparent', 
        border: 0,
        backgroundImage: ''
    }
});
```

This loads stream0 fine. I then click a button and it loads stream1

```
player.play({ url: 'stream1' }, true);
```

instream and without the black screen <- important
This works fine. 

However if I try load stream0 again it fails

```
player.play({ url: 'stream0' }, true);
```

console.log -> uncaught exception: Error in Actionscript. Use a try/catch block to find error.

I've tried using stream/playlist arrays which cycle fine, but neither will do the instream (no black screen between clips loading)

**Comment by danrossi** [comment]
Please provide a working page please. Im sure the error is easy to find.

**Comment by alexcroox** [comment]
OK I've seperated my code and made a standalone example:

http://alexcrooks.me/others/streamtest/

There are 2 streams, clicking the cycle button will switch from 0 -> 1 then again 1 -> 0 ERROR

**Comment by danrossi** [comment]
You are trying to play an instream within and instream, it may need to be closed first ... ill have to see how Ova deals with this. The feature is for ads playing within a clip. Whats the purpose of this ?

**Comment by alexcroox** [comment]
To rapidly switch between 3 camera angles pointing at a robot arm. I need it to be as fast as possible as they are on a time restricted game.

**Comment by danrossi** [comment]
If you are using rtmp, use dynamic stream switching. you will need to build a plugin for this though there is no js api for this im afraid but a plugin can make an api available. 

using that feature isn't seamless anyway its calling a normal play.

**Comment by alexcroox** [comment]
Well it pauses the frame of the current video and waits for the next one to load before replacing it with that one (takes max 1 second for me), instead of the default behavior of showing a black loading screen. The timings may be similar but it's a perception of speed.

**Comment by danrossi** [comment]
Still its not a feature you are trying to use it for.

**Comment by anssip** [comment]
This is the stack trace of the error. Can be seen in the test page at http://alexcrooks.me/others/streamtest/

```
Error: Already playing an instream clip
    at org.flowplayer.model::Playlist/setInStreamClip()
    at org.flowplayer.controller::PlayListController/http://flowplayer.org/core/internal::playInstream()
    at org.flowplayer.view::FlowplayerBase/playInstream()
    at org.flowplayer.view::Flowplayer/genericPlay()
    at Function/http://adobe.com/AS3/2006/builtin::apply()
    at flash.external::ExternalInterface$/_callIn()
    at Function/<anonymous>()
```

I will work on this.
