### ISSUE TITLE
fms token authentication via rtmpe

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#132]
Secure streaming plugin supports Wowza and lighttpd.

See: http://flowplayer.org/forum/#!/moot/16818

**Comment by danrossi** [comment]
There is no such thing with FMS. they should probably use the many protection features available with AMS 5.1 now ie PHDS / PHLS and swf protection etc.

**Comment by phloxic** [comment]
There is some stuff available via Google, e.g.: http://www.adobe.com/devnet/adobe-media-server/articles/scaling_securing_fms3.html#articlecontentAdobe_numberedheader_1
?

**Comment by danrossi** [comment]
Yes it's pseudo code there is no default solution. The user would have to modify their server application code to provide the same feature as Wowza. Worse is having to implement the authentication module via c++ code. Their best bet is enabling DRM with HDS perhaps OR develop the server side code and customise the secure token plugin for their needs ?
