### ISSUE TITLE
brselect + pseudostreaming restarts clip on stream switch (regression)

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#133]
Regression in 3.2.16 core:
- http://flowplayer.blacktrash.org/test/brselect-pseudo.html - 3.2.16 core shows the problem.
- http://flowplayer.blacktrash.org/test/brselect-pseudo-3215.html - 3.2.15 core works as expected with the latest plugins.

See also: http://flowplayer.org/forum/#!/moot/17258

**Comment by danrossi** [comment]
the dev might be fine and I think I've posted it before, it's due to this metadatachange event business that has been rolled over to that plugin also as it needs this event to reset its position.

**Comment by adammada** [comment]
Here: https://github.com/flowplayer/flash/issues/88 ? Links are not working. Could you give link to compiled (commercial)  version?

**Comment by phloxic** [comment]
Closing in favour of #88
