### ISSUE TITLE
Video froze on Mac OS

### ISSUE THREAD

**Issue by wigurenko** [flowplayer/flash#135]
Video froze on Mac OS, on 12 sec, especially on Safari, but sound is steel playing and thumb moving
http://yadi.sk/d/uEavA_x79ZD6m

**Comment by danrossi** [comment]
Sounds like encoding and video sync issues ? Link to a page you are working with

**Comment by wigurenko** [comment]
I found out that this is due to 'hardware acceleration', is it possible disable it from flowplayer configuration, without user interaction?

**Comment by danrossi** [comment]
accelerated: false it's not on by default though

**Comment by danrossi** [comment]
not sure if this is fixable will close for now, that is the config to disable / enable acceleration.
