### ISSUE TITLE
httpstreaming live controls: allow removal of "duration" display

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#136]
(pardon if this is already reported - I could not find it)
With live HDS or http streams the controlbar always shows the "duration".
See: http://flash.flowplayer.org/demos/plugins/streaming/bwcheck-hds-live.html
In most circumstances this is not useful or distracting.
Make the controlbar behave like when setting clip.live for rtmp live streams (omit duration).
By default? Optional?
What good is this duration for the **user**?

See also: http://flowplayer.org/forum/#!/moot/17318

**Comment by danrossi** [comment]
^ doesn't look like using the dev files I've posted many times. The dev sets the duration to zero on a live stream as the HDS feature is still setting this and is required for a dvr type stream.

**Comment by phloxic** [comment]
And when the duration is zero, it is also not displayed?

**Comment by danrossi** [comment]
No i dont believe it displays like with rtmp live streaming.

**Comment by phloxic** [comment]
So there will be a constant 0 there? - Why can't we just do the same as for other live streams: specifying `live: true` for the clip will cause the controlbar not to show duration?

**Comment by danrossi** [comment]
test those files I sent in other tickets it won't display as a 0 value is considered empty makes no difference.

**Comment by phloxic** [comment]
Still there in 3.2.17 dev:
http://flash.flowplayer.org/demos/plugins/streaming/bwcheck-hds-live.html

**Comment by danrossi** [comment]
I believe you should be loading the dev link anssi sent thats the live site with the old versions.

**Comment by danrossi** [comment]
http://flash.dev94.flowplayer.us/demos/plugins/streaming/bwcheck-hds-live.html

**Comment by phloxic** [comment]
That wasn't present when I tested, so I took what I had. Looking good now.

**Comment by phloxic** [comment]
Almost. Right after page load, hovering over the controlbar I can make it alternate hecticly between duration display and non-display. Please have another look, I'll try to make a screencast.

**Comment by phloxic** [comment]
Here's a screencast: http://media.blacktrash.org/fp/test/hds-controls.m4v
After the first switch it becomes stable.

**Comment by danrossi** [comment]
To be more specific, I have to set an empty duration on the callback of metadata so perhaps there is a delay when doing so. The internals is adding a duration I'd have to override it's source which is possible. I haven't seen an issue with normal usage and playback.

**Comment by danrossi** [comment]
its fine now its because of a delay doing it in the callback and because metadata is dispatched on each dynamic switch.

**Comment by anssip** [comment]
@blacktrash can you again verify this. Latest is in dev94

**Comment by phloxic** [comment]
Behaving nicely - closing.
