### ISSUE TITLE
live dvr (devel f4m, httpstreaming): onStart and onResume not fired

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#138]
User example: http://test.yourgamecam.com/flowplayer
Live from 7am to 11pm Pacific Time.

Uses devel
http://flowplayer.blacktrash.org/dev/flowplayer.f4m-3.2.10-dev.swf
http://flowplayer.blacktrash.org/dev/flowplayer.httpstreaming-3.2.11-dev.swf

See: http://flowplayer.org/forum/#!/setup_configuration#17460_we_trying_to_

**Comment by danrossi** [comment]
feed is offline now but I can test with a wowza

**Comment by danrossi** [comment]
wasted a bit of time it's fine

[LOG] time 23:43:00.466 :: org.flowplayer.httpstreaming::HttpStreamingProvider : onNetStatus(), code: NetStream.Play.Start, paused? false, seeking? false
[LOG] time 23:43:00.486 :: org.flowplayer.httpstreaming::HttpStreamingProvider : in NetStreamControllingStremProvider.onMetaData: [Clip] 'http://localhost:1935/dvr/livestream/DVR_b125000_w1963203422_qRFZS.abst/'
onStart HEre http-bitrates.html:29
[LOG] time 23:43:00.569 :: org.flowplayer.httpstreaming::HttpStreamingProvider : onPlayStatus() -- NetStream.Play.TransitionComplete
[LOG] time 23:43:00.570 :: org.flowplayer.httpstreaming::HttpStreamingProvider : silentSeek == false
[LOG] time 23:43:00.571 :: org.flowplayer.httpstreaming::HttpStreamingProvider : dispatching [ClipEvent type="onSwitchComplete" info=null] on clip [Clip] 'http://localhost:1935/dvr/livestream/DVR_b125000_w1963203422_qRFZS.abst/'
[INFO] time 23:43:00.616 :: org.flowplayer.httpstreaming::HttpStreamingProvider : _onNetStatus, code: NetStream.Seek.Notify
[LOG] time 23:43:00.618 :: org.flowplayer.httpstreaming::HttpStreamingProvider : silentSeek == false
[LOG] time 23:43:00.620 :: org.flowplayer.httpstreaming::HttpStreamingProvider : starting seek target wait timer
[LOG] time 23:43:00.622 :: org.flowplayer.httpstreaming::HttpStreamingProvider : onNetStatus(), code: NetStream.Seek.Notify, paused? false, seeking? false
[INFO] time 23:43:00.643 :: org.flowplayer.httpstreaming::HttpStreamingProvider : _onNetStatus, code: NetStream.Video.DimensionChange
[LOG] time 23:43:00.645 :: org.flowplayer.httpstreaming::HttpStreamingProvider : onNetStatus(), code: NetStream.Video.DimensionChange, paused? false, seeking? false
[INFO] time 23:43:00.858 :: org.flowplayer.httpstreaming::HttpStreamingProvider : _onNetStatus, code: NetStream.Buffer.Full
[LOG] time 23:43:00.859 :: org.flowplayer.httpstreaming::HttpStreamingProvider : silentSeek == false
[LOG] time 23:43:00.861 :: org.flowplayer.httpstreaming::HttpStreamingProvider : dispatching [ClipEvent type="onBufferFull" info=null] on clip [Clip] 'http://localhost:1935/dvr/livestream/DVR_b125000_w1963203422_qRFZS.abst/'
[LOG] time 23:43:00.867 :: org.flowplayer.httpstreaming::HttpStreamingProvider : onNetStatus(), code: NetStream.Buffer.Full, paused? false, seeking? false
[INFO] time 23:43:03.628 :: org.flowplayer.httpstreaming::HttpStreamingProvider : _onNetStatus, code: NetStream.Pause.Notify
[LOG] time 23:43:03.629 :: org.flowplayer.httpstreaming::HttpStreamingProvider : onNetStatus(), code: NetStream.Pause.Notify, paused? true, seeking? false
[LOG] time 23:43:03.630 :: org.flowplayer.httpstreaming::HttpStreamingProvider : silentSeek == false
[LOG] time 23:43:03.631 :: org.flowplayer.httpstreaming::HttpStreamingProvider : dispatching [ClipEvent type="onPause" info=null] on clip [Clip] 'http://localhost:1935/dvr/livestream/DVR_b125000_w1963203422_qRFZS.abst/'
onPause http-bitrates.html:37
[LOG] time 23:43:06.130 :: org.flowplayer.httpstreaming::HttpStreamingProvider : doResume
[INFO] time 23:43:06.132 :: org.flowplayer.httpstreaming::HttpStreamingProvider : _onNetStatus, code: NetStream.Unpause.Notify
[LOG] time 23:43:06.133 :: org.flowplayer.httpstreaming::HttpStreamingProvider : onNetStatus(), code: NetStream.Unpause.Notify, paused? false, seeking? false
[LOG] time 23:43:06.134 :: org.flowplayer.httpstreaming::HttpStreamingProvider : silentSeek == false
[LOG] time 23:43:06.136 :: org.flowplayer.httpstreaming::HttpStreamingProvider : dispatching [ClipEvent type="onResume" info=null] on clip [Clip] 'http://localhost:1935/dvr/livestream/DVR_b125000_w1963203422_qRFZS.abst/'
onResume

**Comment by phloxic** [comment]
Please have a look at http://test.yourgamecam.com/flowplayer again - only onPause is fired, neither onStart nor onResume is fired.

**Comment by ygc** [comment]
I enabled logging (level debug) on flowplayer and have saved the log to a file. I dont see a way to attach it to this issue and is about 330k in size. Let me know if there is somewhere I can upload it if you need it.
I took a quick look and search for onStart and onResume. I found the following:

[LOG] time 20:48:13.722 :: org.flowplayer.model::EventListener : [ClipEvent type="onStart" info=false] was filtered out for this listener
...

[LOG] time 20:48:40.382 :: org.flowplayer.model::EventListener : [ClipEvent type="onResume" info=null] was filtered out for this listener

I dont know if this is relevant but thought I'd post just in case it helps. I've left the logging enabled in the sample page.

**Comment by phloxic** [comment]
@danrossi - ping!

**Comment by danrossi** [comment]
^ see the logs above those events are available as they appear when metadata is available. as Ive yet to be able to see that stream up I'm not much help.

**Comment by ygc** [comment]
If changed the stream to a different DVR feed that runs from 00:15 to 23:55 pacific time every day. 

Cheers,
Jo

**Comment by danrossi** [comment]
there is something certainly very wrong with the stream. can you try setting up a new dvr stream name and trying again. notice some errors on the console. the startup time gives it away because its 10 hours long.

**Comment by ygc** [comment]
I stopped the stream, deleted the DVR files and restarted the stream and
now the events fire as expected. So this brings up a question.

Does flowplayer have a limit on the length of a DVR recording using HTTP
streaming?
We run our cameras in most cases for 16 hours a day, a few for nearly 24
hours. Our users need to be able to scrub back from live to the beginning
of the day.
What is the limit on the duration of a DVR with flowplayer?

Thanks for your help.

Jo

**Comment by danrossi** [comment]
it looked corrupted to me that is all it likely was not triggering metadata.

**Comment by ygc** [comment]
Hmm. I have added the original DVR streamso now there are two to observe.
test.yourgamecam.com/flowplayer is there and I get the onStart/onResume
events just fine, even with 7+ hours of DVR.
test.yourgamecam.com/flowplayer is the other stream. I just restarted it
clean and it doesn't give the onStart/onResume events.
Both cameras are the exact same model with same firmware revision.
They are feeding to Wowza 3.5.2 with same configuration. There are
(currently) no errors in either the wowzamediaserver_error.log or
wowzamediaserver_access.log.

What metadata is corrupted, especially in the flowplayer1 stream?

**Comment by ygc** [comment]
Once more thing we've noticed. With the streams that do not give onStart,
the clip.duration is always 0 (checked in onPause handler), even though it
is playing and the control bar displays the correct duration. Looks like
control bar is registering for OSMF onDurationChange and onTimeUpdate
events.

**Comment by danrossi** [comment]
the duration gets updated elsewhere outside the metadata events its a dvr event. the duration is only set to zero if its a live only stream. it should start as default with a duration of the current fragment start time. i could see the duration updating in your player so not sure what you are talking about sorry.

**Comment by danrossi** [comment]
closing this for now
