### ISSUE TITLE
long mp3: duration completely wrong and does not update after mp3 has buffered

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#14]
http://media.blacktrash.org/fp/test/120904-Ep1.mp3 has a duration of 50min 48sec. Flowplayer shows over 4 hours  and does not update once the mp3 has buffered.

Debug log by user:

```
[LOG] time 21:21:26.597 :: org.flowplayer.view::ClipResizer : we don't have a size yet.. waiting for the video object to have a size
[LOG] time 21:21:27.98 :: org.flowplayer.view::ClipResizer : we don't have a size yet.. waiting for the video object to have a size
[LOG] time 21:21:27.601 :: org.flowplayer.view::ClipResizer : we don't have a size yet.. waiting for the video object to have a size
[LOG] time 21:21:28.141 :: org.flowplayer.view::ClipResizer : we don't have a size yet.. waiting for the video object to have a size
[LOG] time 21:21:28.650 :: org.flowplayer.view::MediaResizer : resizeTo() [MediaSize] 'scale'
[LOG] time 21:21:28.652 :: org.flowplayer.view::MediaResizer : resizing to max size (filling available space)
[LOG] time 21:21:28.654 :: org.flowplayer.view::MediaResizer : resizing to 442x6
[WARN] time 21:21:28.655 :: org.flowplayer.model::Clip : Trying to change width of a clip that does not have media content loaded yet
[WARN] time 21:21:28.657 :: org.flowplayer.model::Clip : Trying to change height of a clip that does not have media content loaded yet
[LOG] time 21:21:28.659 :: org.flowplayer.view::MediaResizer : resized to 0x0
[LOG] time 21:21:28.661 :: org.flowplayer.model::ClipEvent : null, null, null, null, null
[INFO] time 21:21:28.662 :: org.flowplayer.model::Clip : [Clip] '/uploads/podcasts/11/120904-Ep1.mp3' dispatchEvent(), event [ClipEvent type="onResized" info=null]
[LOG] time 21:21:28.663 :: org.flowplayer.model::EventListener : notifying listener for event [ClipEvent type="onResized" info=null]
[INFO] time 21:21:28.665 :: org.flowplayer.model::Clip : received onClipEvent, I am commmon clip: true
[INFO] time 21:21:28.667 :: org.flowplayer.model::Clip : [Clip] '/uploads/podcasts/11/120904-Ep1.mp3' dispatchEvent(), event [ClipEvent type="onResized" info=null]
[LOG] time 21:21:28.669 :: org.flowplayer.model::Clip : [Clip] '/uploads/podcasts/11/120904-Ep1.mp3': dispatchEvent(): no listeners for event [ClipEventType] 'onResized'
[LOG] time 21:21:28.671 :: org.flowplayer.model::ClipEvent : fireExternal onResized, 0, null, null,null, null
[LOG] time 21:21:30.631 :: org.flowplayer.model::Clip : [Clip] '/uploads/podcasts/11/120904-Ep1.mp3': dispatched play event with target [Clip] '/uploads/podcasts/11/120904-Ep1.mp3'
```

See also: http://flowplayer.org/forum/8/103295

What is very strange is that the problem is not present with:
http://media.blacktrash.org/fp/test/FH-VFNRadio-6-5-12.mp3 - even slightly longer

I can exclude a server problem, as I have tested with
http://media.blacktrash.org/fp/test/120904-Ep1.mp3
as well: same result.

**Comment by danrossi** [comment]
I checked osmf, it's also not predicting right. I check with jwplayer and they have made audio duration time update every few ms which is visually undesirable I reckon, it's incrementing also as it's downloading ;). 

It should get a download complete status to update the end duration.

**Comment by danrossi** [comment]
It is dispatching a complete status but still calculating 16766.136009070295  seconds.

**Comment by danrossi** [comment]
I can't get it calculating right even once it's cached :(

**Comment by danrossi** [comment]
Back to this is it vbr or cbr ? it calculates the duration by the filesize over the bitrate.

**Comment by phloxic** [comment]
It's cbr - but normally cbr is required for rtmp only. - Complete mystery to me as well :-(

**Comment by danrossi** [comment]
This is a common problem really it looks like nothing out there can estimate it right. The only way I think is to get the real bitrate and divide by the filesize. I'll hack something up for testing anyway. There is an mp3 tool that can grab the bitrate from the byte data.

**Comment by phloxic** [comment]
One could also put the mp3 into a FLV container with a minimal white video ;-) That actually works - before I deployed via rtmp, I used this trick for php-pseudostreaming "audio" with seeking to cuepoints etc.  - don't try this at home though ;-) - but once I got it done, it worked like a charm.

**Comment by danrossi** [comment]
Should I investigate in such a tool then ? It's not byte appending sadly so it might need two requests to grab the header bytes to obtain the bitrate. No player out there does this though. Im pretty sure the calc thats in there is correct there is many ways to achieve it I believe.

**Comment by phloxic** [comment]
It's just strange that it's so extremely off the mark for this file. Wait - there is a header missing:

```
$ ffprobe -show_streams 120904-Ep1.mp3 | head -n1
ffprobe version N-44127-gb0dc428 Copyright (c) 2007-2012 the FFmpeg developers
  built on Sep  3 2012 21:29:48 with gcc 4.0.1 (GCC) (Apple Inc. build 5493)
  configuration: --enable-gpl --enable-version3 --enable-nonfree --disable-network --disable-ffserver --disable-ffplay --enable-shared --enable-pthreads --enable-postproc --enable-libx264 --enable-libxvid --enable-libfaac --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libvpx --enable-librtmp --extra-cflags=-I/sw/include --extra-libs=-L/sw/lib
  libavutil      51. 70.100 / 51. 70.100
  libavcodec     54. 55.100 / 54. 55.100
  libavformat    54. 25.104 / 54. 25.104
  libavdevice    54.  2.100 / 54.  2.100
  libavfilter     3. 15.102 /  3. 15.102
  libswscale      2.  1.101 /  2.  1.101
  libswresample   0. 15.100 /  0. 15.100
  libpostproc    52.  0.100 / 52.  0.100
[mp3 @ 0x2004220] Header missing
    Last message repeated 1 times
[mp3 @ 0x2002620] max_analyze_duration 5000000 reached at 5015510
[mp3 @ 0x2002620] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '120904-Ep1.mp3':
  Duration: 00:50:41.54, start: 0.000000, bitrate: 128 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, mono, s16, 128 kb/s
[STREAM]
```

As well when I am reencoding:

```
$ ffmpeg -i 120904-Ep1.mp3 -b:a 128k -ac 1 120904-Ep1-reenc.mp3
ffmpeg version N-44127-gb0dc428 Copyright (c) 2000-2012 the FFmpeg developers
  built on Sep  3 2012 21:29:48 with gcc 4.0.1 (GCC) (Apple Inc. build 5493)
  configuration: --enable-gpl --enable-version3 --enable-nonfree --disable-network --disable-ffserver --disable-ffplay --enable-shared --enable-pthreads --enable-postproc --enable-libx264 --enable-libxvid --enable-libfaac --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libvpx --enable-librtmp --extra-cflags=-I/sw/include --extra-libs=-L/sw/lib
  libavutil      51. 70.100 / 51. 70.100
  libavcodec     54. 55.100 / 54. 55.100
  libavformat    54. 25.104 / 54. 25.104
  libavdevice    54.  2.100 / 54.  2.100
  libavfilter     3. 15.102 /  3. 15.102
  libswscale      2.  1.101 /  2.  1.101
  libswresample   0. 15.100 /  0. 15.100
  libpostproc    52.  0.100 / 52.  0.100
[mp3 @ 0x2004220] Header missing
    Last message repeated 1 times
[mp3 @ 0x2002620] max_analyze_duration 5000000 reached at 5015510
[mp3 @ 0x2002620] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '120904-Ep1.mp3':
  Duration: 00:50:41.54, start: 0.000000, bitrate: 128 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, mono, s16, 128 kb/s
Output #0, mp3, to '120904-Ep1-reenc.mp3':
  Metadata:
    TSSE            : Lavf54.25.104
    Stream #0:0: Audio: mp3, 44100 Hz, mono, s16, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 -> libmp3lame)
Press [q] to stop, [?] for help
[mp3 @ 0x2004220] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
[mp3 @ 0x2004220] Header missing
Error while decoding stream #0:0: Invalid data found when processing input
```

Will test the reencoded file with the error ironed out. - If it behaves reasonably well, then I'd say this kind of additional feature is not needed.

**Comment by phloxic** [comment]
Yes, the missing header was the problem: http://flowplayer.org/forum/8/103295#post-103397

So, @danrossi,  feel free to either close this, or turn it into a luxurious enhancement ;-)

**Comment by danrossi** [comment]
Hmm that won't be up to me I think ;) Let me know if you want to look further into it because it's not something anyone is doing and obviously no one is correct.

**Comment by phloxic** [comment]
@anssip?

My 2¢: We are in feature freeze, so no - unless you can foresee that
- a it can be implemented rather easily
- does not affect loading speed of the audio file too much; otherwise it would have to be optional, and I don't think it's worth an option
- it does not break anything - playlist transitions, events etc.

Then obviously it would be a nice to have.

**Comment by danrossi** [comment]
Yep so no.

**Comment by danrossi** [comment]
I would do it simultaniously and dynamically update the duration. Anyway leave it as it is.

**Comment by danrossi** [comment]
basically it has to request the file a second time to grab the header bytes during initial playback so can be done at the same time. pretty much like the duration callback on the rtmp server it would be doing some file processing also.

**Comment by danrossi** [comment]
shall we close this ?

**Comment by phloxic** [comment]
From my perspective yes - unless @anssip wants to advertise a unique audio feature.

**Comment by danrossi** [comment]
closing for now
