### ISSUE TITLE
onTextData returns empty value

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#140]
http://flowplayer.blacktrash.org/test/netstreamevent.html
The `onTextData` netStreamEvent always returns an empty object (array?) in the console.
Is this to be expected? Doesn't the caption plugin use these?

See: http://flowplayer.org/forum/#!/scripting_api#netstreamevent-ontextdata

**Comment by danrossi** [comment]
The argument returned is empty on that video outside of flowplayer.

**Comment by phloxic** [comment]
I can see that it's empty, yes. So, when is it not empty?
The video has e.g. trackid etc.?

**Comment by danrossi** [comment]
it would be in info["trackid"]  normally.

**Comment by phloxic** [comment]
Yeah, so a) the docs are wrong because they are talking about an object, not an array, and b) what is "normally"?

**Comment by danrossi** [comment]
if the info object is available info["trackid"] it would appear here.

**Comment by phloxic** [comment]
Well, the info object _is_ available, it's just not an _object_, but an _empty_ array.
What info does the `captionsTrackFilter` evaluate then?
Where does it get its information from?
How must the clip be muxed(?) to not return an empty array? Any samples?

**Comment by danrossi** [comment]
http://flowplayer.blacktrash.org/test/netstreamevent.html it seems to be working here now, that text is obtained from ontextdata

**Comment by phloxic** [comment]
Huh? there is no text returned in the console, there is just an empty array?
The captions plugin is only installed to show that the captions work - it's about the `onTextData` netstream event which returns nothing meaningful. So, if the player, as you say, obtains its info from ontextdata, then there's a bug in the `onNetStreamEvent` handler - as originally stated in this report.

``` js
clip: {
  onNetStreamEvent: function (clip, type, info) {
    if (type == "onTextData") {
      console.log(info);
    }
  }
}
```

should not print an empty array in the console.

**Comment by danrossi** [comment]
ok

**Comment by anssip** [comment]
I did investigate this few weeks back because of some customer issue. Will take a look again now.

**Comment by anssip** [comment]
@blacktrash the fixed version is now in the dev site.

**Comment by phloxic** [comment]
Confirming that this is fixed in 3.2.17 dev. Closing.

**Comment by Prendo93** [comment]
Was this fix implmented translate for HDS streams also? I have been expermenting with wowza and a stream that has onTextData events, will fire when streamed via both RTMP and HDS however only the RTMP stream logs the actual text data (in the third argument).

**Comment by danrossi** [comment]
Hi. HDS uses embedded 608, wowza reparses that back to onTextData. Please have a look at your setup, it should do it out of the box or you might need to turn on that config.
