### ISSUE TITLE
Loading the video by url directly from the flash player ?

### ISSUE THREAD

**Issue by moumenrahhali** [flowplayer/flash#142]
is it possible to use it like this ?
http://releases.flowplayer.org/swf/flowplayer-3.2.16.swf?someconfig=link to the video

**Comment by danrossi** [comment]
?config={ clip: "url": "video" } 

Or you would have to customise it by building in a custom clip resolver plugin, so you could just do

?videoid

**Comment by moumenrahhali** [comment]
Something like this ? 
http://releases.flowplayer.org/swf/flowplayer-3.2.16.swf?config={clip:"link to mp4 video":"video"}
Didn't work ><

**Comment by danrossi** [comment]
you need to urlencode it.

**Comment by danrossi** [comment]
config=path/to/config is also possible. 

or modify to suit your needs with a custom url resolver might work.

**Comment by danrossi** [comment]
closing this for now if possible, or modify the player functionality yourself. If you require something like this I can do this for you.
