### ISSUE TITLE
Pipes in linkUrl breaks regex

### ISSUE THREAD

**Issue by cgrice** [flowplayer/flash#146]
When setting the linkUrl of a clip to a URL that includes pipes in query params, the url fails validation. For example, the following url will fail:

http://example.com/test?118990|114|&iari=281214

**Comment by anssip** [comment]
Should work if you escape the linkUrl value. For example:

```
clip: {
  linkUrl: escape("http://example.com/test?118990|114|&iari=281214")
}
```
