### ISSUE TITLE
3.2.16 rtmp live does not refresh metadata

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#148]
Another regression regarding live streams in 3.2.16 core.

In this demo http://flowplayer.blacktrash.org/test/audio-live.html clip metaData is refreshed when a new song starts. This demo works with core 3.2._15_ and rtmp 3.2.12, but not with core 3.2._16_ and rtmp 3.2.12.

See also #81
and: http://flowplayer.org/forum/#!/plugins#metadata-out-of-rtmp-audio

**Comment by danrossi** [comment]
it's because its a server side playlist so the filename is the same. it will take a while to test this as its an audio server playlist and can't replicate it easy. what about in onMetaDataUpdate ?

**Comment by phloxic** [comment]
Just let
http://flowplayer.blacktrash.org/test/audio-live.html (working 3.2.15)
http://flowplayer.blacktrash.org/test/audio-live-3216.html (broken 3.2.16)
run in parallel and you'll see the difference.

If you read the forum thread you can see that I first argued with "same filename" as well - only to discover that it works all fine in 3.2.15 ...

I can check `onMetaDataUpdate` - but "secret" and undocumented config options are of no use to anyone.

**Comment by phloxic** [comment]
`onMetaDataUpdate` (if it exists) does not do anything at all, or is not called ever.

**Comment by phloxic** [comment]
Seems as mystical an event as `onMetaDataChange` which I never saw do anything either: https://github.com/flowplayer/flash/issues/122#issuecomment-21712254

**Comment by danrossi** [comment]
yeh i can see its called onMetaData on the console no idea will have to look during the week.

**Comment by danrossi** [comment]
the clip argument is showing up as zero.

**Comment by danrossi** [comment]
javascript is not getting the updated clip on callback ? it's being updated fine internally.  the event system is pretty mad so will take a while.

**Comment by danrossi** [comment]
js api needs the event added to extend clip properties before calling the callback method.

**Comment by danrossi** [comment]
I stuffed it up. Have to make a branch. It will be fixed soon.

**Comment by danrossi** [comment]
its in.

**Comment by phloxic** [comment]
So what does `onMetaDataChange` do what `onMetaData` did not already in 3.2.15?

**Comment by danrossi** [comment]
#50 #122

**Comment by phloxic** [comment]
EDIT: `onMetaDataChange` works in 3.2.17 dev.
Does not include the first `onMetaData`.

**Comment by phloxic** [comment]
Needs doc update/add-on new clip event `onMetaDataChange` with 3.2.17.

**Comment by phloxic** [comment]
Grrrh. No. It does not work yet. Please run
http://flowplayer.blacktrash.org/test/audio-live.html - 3.2.15 with `onMetaData`
and
http://flowplayer.blacktrash.org/test/audio-live-3217.html - 3.2.17 dev with `onMetaData` and `onMetaDataChange`
in parallel.
3.2.17 does not update the meta data display.

**Comment by danrossi** [comment]
Yes it does you need the updated javascript api this is the blocker it apparantly extends the clip properties to update them here from an event filter. its in the dev branch now.

**Comment by phloxic** [comment]
Where is what? `flowplayer-src.js` is exactly the current 3.2.12
There have been 2 changes regarding this issue, resulting in no change, the second being a revert:
https://github.com/flowplayer/flash/commit/035a64d3499340baf5db02f6b4a253e4dcc6d645
https://github.com/flowplayer/flash/commit/39430416dff9860551424772ad6b5877b9c1da00 (reverts previous)
So there has been no change in the api.

**Comment by phloxic** [comment]
I'll try with the registered `onMetaDataChange` for testing.

**Comment by phloxic** [comment]
Registering the event in the JS API has no effect. Still the same at http://flowplayer.blacktrash.org/test/audio-live-3217.html

**Comment by phloxic** [comment]
CORRECTION: Yes, works with the registered event. Was a bit hard to test because opening the same stream in 2 instances results asynchroneous playback (about 30 secs!).
So @danrossi - I guess you have to revert the revert?

**Comment by phloxic** [comment]
Let's assume this will be in. Closing.
