### ISSUE TITLE
free player logos linkUrl does not point to fp flash site

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#149]
The logos should point to http://flash.flowplayer.org now, not http://flowplayer.org

@anssip - I found one instance here:
https://github.com/flowplayer/flash/blob/master/core/src/actionscript-commercial/org/flowplayer/view/LogoView.as#L309
But where is the one visible in the bottom left corner of the screen?

**Comment by anssip** [comment]
@blacktrash can be verified in the dev site.

**Comment by phloxic** [comment]
Yes. Closing.
