### ISSUE TITLE
Cluster demos don't show video

### ISSUE THREAD

**Issue by anssip** [flowplayer/flash#15]
http://ec2-50-16-32-151.compute-1.amazonaws.com/plugins/streaming/cluster.html

For @bbbo both the demos on this page have only audio - no video shown at all. For me i sometimes get also video, but sometimes it's audio only when i start playback after page refresh.

**Comment by danrossi** [comment]
bum, it could be related to the screen fixes for the stagevideo fixes :(

**Comment by anssip** [comment]
i was guessing it was about events, like some event missing to fire. I think you made changes to those?

**Comment by danrossi** [comment]
i moved the display adding out of the bufferfull event to the start event as it was removing it from the stage and adding back to the stage after each seek.

**Comment by danrossi** [comment]
better video to use perhaps ? Its preloading the video before playback.

**Comment by danrossi** [comment]
ok i see the issue , well start events arent dispatched so thats why it's not displaying, its trying to play the resolving stream wierd.

**Comment by danrossi** [comment]
I worked it out, the http files being checked need to be cached busted, its hard to explain but will start the resolved clip once it's being checked to work properly. Ive now just realised I probably need to clean up this fix in the screen. but on further discovery there is duplicated init code on the display as its already happening in the handleStart method

https://github.com/flowplayer/flash/blob/master/core/src/actionscript/org/flowplayer/view/Screen.as#L358

same as 

https://github.com/flowplayer/flash/blob/master/core/src/actionscript/org/flowplayer/view/Screen.as#L392

I don't quite get that bit sorry but I'll put it within the onStart method perhaps so there is just one start listener.

https://github.com/flowplayer/flash/blob/master/core/src/actionscript/org/flowplayer/view/Screen.as#L314

**Comment by danrossi** [comment]
How about this is it still doing the same thing

private function onStart(event:ClipEvent):void {
            var clip:Clip = event.target as Clip;
            if (clip.metaData == false) return;
            handleStart(clip, event.info as Boolean);

```
        if (clip.type == ClipType.IMAGE) {
            showDisplay(event);
        }
        if (clip.type == ClipType.VIDEO) {
            var disp:MediaDisplay = _displays[clip];
            if (! disp) return;
            disp.init(clip);

            if (clip.live) {
                showDisplay(event);
            }
        }
    }
```

**Comment by danrossi** [comment]
It's in just lemme know what works best. The cluster changes are in I suspect it's a new flash player quirk attempting to replay the same file partially in the cache on a different stream.

**Comment by anssip** [comment]
Do you think that cache busting is needed, or would your Screen class changes fix this alone?

Just worried about side effects caused by that cache busting param...  Will test without a new cluster plugin first.

**Comment by anssip** [comment]
Works for me every time now: http://ec2-50-16-32-151.compute-1.amazonaws.com/plugins/streaming/cluster.html
Did not update the cluster plugin yet.

@bbbo please also check, i think it was audio-only for you every time

**Comment by bbbo** [comment]
no luck so far, audio only in Firefox 15, Chrome 22 and IE9 (didn't test 
that before, so it's not in the browser cache)

**Comment by anssip** [comment]
Now updated the cluster plugin also, but it does not work yet.

**Comment by danrossi** [comment]
No well it wasn't dispatching start events hence why the display doesn't get added. It's needed because it will try to play the resolving file instead, and will just sit there downloading it and then buggering events up. You can see it in the resource monitor. The actual file being requested to play is sitting there pending. My main question is  the code i've now moved to clean it up even needed as the other code in the start event is also hiding other displays and adding the current display. It causes more chaos with the stagevideo otherwise because its adding and removing the video object from the stage after each seek if its in a bufferfull event.

**Comment by danrossi** [comment]
its working for me.

**Comment by anssip** [comment]
Yeah it looks like the Screen class would need some cleaning up. I will test this a bit locally.

For me the 2nd demo has the problem after following sequence:
1. start player in the 1st demo
2. start player in the 2nd demo
3. start player in the 1st demo
4. start player in the 2nd demo ---> now there is no video

**Comment by anssip** [comment]
Which resource monitor you are referring to?

**Comment by anssip** [comment]
Should be fixed now. The workaround for the missing onBegin event is in the StreamProviderController class.

@danrossi any ideas why onBegin is not fired here?

**Comment by danrossi** [comment]
Sorry guys I was down with the flu, is this still a problem ? The screen changes cleaner now ? Was the listener also required in the streamprovider for a reason ?  Do you now not see onBegin being dispatched ?

**Comment by danrossi** [comment]
Hmm there was some changes to the begin dispatching but it seems they were lost hmmm, it's to prevent begin being dispatched many times and to dispatch if the player is in paused mode. 

http://code.google.com/p/flowplayer-core/issues/detail?id=629
http://code.google.com/p/flowplayer-core/issues/detail?id=615

I'll put them through to have a look thanks.

**Comment by danrossi** [comment]
And in terms of this problem, if you can see, it's using the netstream in the cluster plugin from the looks of it for playback but downloading the file for a very long time therefore no events are being dispatched from the main netstream. The cache buster works around that if its due to play back the same file. I think it's a flash player bug if loading up multiple connections / streams at once.

**Comment by anssip** [comment]
we just made a new release :-) Right now it works around the missing onBegin event, see the change in StreamProviderController.

**Comment by danrossi** [comment]
//#15 add cache busting to the file being checked for availability to play back correctly once resolving has completed.
            _netStream.play(_clip.getResolvedUrl(this));

looks like it didn't merge properly or didn't go in, it's still a problem on my end without it. Is that correct ?

**Comment by danrossi** [comment]
https://dl.dropbox.com/u/3394987/clusterissue.png
