### ISSUE TITLE
Flowplayer 3.2.16 single quote in filename

### ISSUE THREAD

**Issue by nikita-v** [flowplayer/flash#150]
Hi!
When the file name contains a single quote (even with escaping), I see a black screen.

sorry for my poor language

**Comment by danrossi** [comment]
Yes this is a pest I had implemented a replacement change in the javascript but it was taken out by request. You have to do a unicode replacement for these. A quote in a filename is also bad formatting in the first place. 

This is the code I had to put back into the javascript api for a client as too many fields had to be replaced and got messy and would randomly break ! something like that. 

 obj = obj.replace(/(%)/g,"%25").replace(/'/g,'\u0027').replace(/"/g,'\u0022').replace(/&/g,'%26');

**Comment by danrossi** [comment]
closing this for now if possible.
