### ISSUE TITLE
js controls: allow streaming protocols

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#152]
Currently the javascript controlbar does not support streaming protocols because it expects a growing buffer - `status.bufferEnd`.
By making a fake buffer equal to duration the plugin also works with streaming protocols.
First stab here: http://flowplayer.blacktrash.org/dev/flowplayer.controls-3.2.11-dev.js
Demo: http://flowplayer.blacktrash.org/test/jscontrols-rtmp.html
See also: http://flowplayer.org/forum/#!/scripting_api#designing-the-flash-flowpla

**Comment by anssip** [comment]
@blacktrash can you finish this :-)

**Comment by phloxic** [comment]
Let me just test a bit more ;-)

**Comment by phloxic** [comment]
Also taking care of #153

**Comment by phloxic** [comment]
Works in dev94. Closing.
