### ISSUE TITLE
js controls: go to "paused" state onFinish

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#153]
To show the _play_ button onFinish (for replay).

**Comment by phloxic** [comment]
Demo: http://flowplayer.blacktrash.org/test/jscontrols-rtmp.html

**Comment by anssip** [comment]
@blacktrash these changes are in dev94 now. Can you update that demo to verify this.

**Comment by phloxic** [comment]
@anssip - if it's like the api: the js haven't been updated at e.g. http://flash.dev94.flowplayer.us/plugins/javascript/controlbar.html - still at 3.2.10.

**Comment by anssip** [comment]
i'll update the version numbers of _all_ plugins. Like we agreed let's release everything with new version numbers.

**Comment by phloxic** [comment]
Ok - http://flash.cdn.dev94.flowplayer.us.s3.amazonaws.com/js/flowplayer.controls-3.2.10.min.js already has the fixes and I confirm that they work. Closing.
