### ISSUE TITLE
Memory leak on repeated play() calls via API

### ISSUE THREAD

**Issue by anssip** [flowplayer/flash#163]
Flash's memory usage seems to continuously grow when calling play("video.mp4") via the API. Here is a test page that can be used to investigate this: https://github.com/flowplayer/flash/blob/dev/core/test/memoryleak.html

> "I am running the Flash-based Flowplayer. After playing a few MP4 videos, Flash crashes
> with the "gray circle of death" as described here:
> http://blogs.adobe.com/dekesmith/2012/06/07/what-is-the-gray-circle-with-an[..]. According
> to the Adobe blog post, this is Flash failing to allocate more memory from the browser.
> 
> I have run the memory profiler found in Flash Develop and it seems that each time I play
> an MP4, flash allocates a fairly large amount of memory that never gets freed. After a few
> videos, when Flash Develop shows that 200MB or thereabouts have been allocated, Flash
> crashes."

**Comment by danrossi** [comment]
I'm not seeing a problem if the api call is made in the correct place, the code above is basically a dos attack and creating a bottleneck from the looks of it. 

onStart: function() {
            console.log("onStart");
            this.play("http://www.blacktrash.org/php/streamer.php/ccc_trailer1.flv");
        },

or with http://pseudo01.hddn.com/vod/demo.flowplayervod/bbb-400.mp4

Need the actual video to test.

**Comment by danrossi** [comment]
The garbage collector is being run very often and keeping memory in check.

**Comment by danrossi** [comment]
There was a bit of surgery required so needs testing but it looks ok to me.

**Comment by anssip** [comment]
These fixes are now merged and in dev94. Thre's still a problem in this demo: http://flash.dev94.flowplayer.us/demos/configuration/instream-playlist.html

it does not continue playing after the midroll finishes.

**Comment by anssip** [comment]
Buffering animation is stuck after pause here: http://flash.dev94.flowplayer.us/demos/configuration/playlist-splash.html

**Comment by anssip** [comment]
Exception is thrown here http://flash.dev94.flowplayer.us/demos/plugins/javascript/playlist/youtube.html

```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
    at org.flowplayer.model::Playlist/doReplace()
    at org.flowplayer.model::Playlist/replaceClips2()
    at org.flowplayer.controller::PlayListController/http://flowplayer.org/core/internal::setPlaylist()
    at org.flowplayer.view::FlowplayerBase/setPlaylist()
    at MethodInfo-861()
```

**Comment by danrossi** [comment]
Yes I know where it is, perhaps its not the best place for this here, but i believe the stream needs to be detached from the current video before replacement also to help clear display and network buffers. i'll try something that will work.

**Comment by anssip** [comment]
Please check the other issues also, i found 3 problems, all listed above :smile:

**Comment by danrossi** [comment]
it's hard to determine it now it wasn't ready for merging. the other problems are probably events. 

https://github.com/flowplayer/flash/pull/175

**Comment by danrossi** [comment]
I just recompiled a few times and was able to get instream working. It's being added correctly for me.

**Comment by anssip** [comment]
Merged now. It will build to dev94 and i'll test once it's done.

**Comment by danrossi** [comment]
cannot replicate either of those. the playlist plugin issue has been fixed up.

**Comment by anssip** [comment]
No exception here any more: http://flash.dev94.flowplayer.us/demos/plugins/javascript/playlist/youtube.html

With Mac Safari the buffer animation is still stuck here: http://flash.dev94.flowplayer.us/demos/configuration/playlist-splash.html  One way to solve this is to have a "start detect timer" in the PlayButtonOverlayView that monitors if the playback time starts moving and hides the buffer animation, something similar to this https://github.com/flowplayer/flash/blob/master/plugins/controls/src/actionscript/org/flowplayer/controls/scrubber/ScrubberSlider.as#L257

**Comment by danrossi** [comment]
Yes got it it's being garbage collected I will turn the listener on and off manually. something is unruly with safari now it seems.

**Comment by danrossi** [comment]
it seems to be fine now.

**Comment by danrossi** [comment]
I believe this is a buffer empty event after unpausing it will clear after its done. There is some shotty power management thing in mavericks safari which is doing this. Its not buffering progressive download. I can't really figure what it's doing because I can't even see the logs in safari either it's showing up empty / clear / white so a bug with safari. This might take some time and I doubt its got anything to do with these changes.

**Comment by danrossi** [comment]
it's happening in chrome also and its because of another timer event set as weak reference will have to reconfigure its listener setup. will test in chrome and it should work in safari.

**Comment by danrossi** [comment]
ok its random. within that file there is some playback timer tracker to stop the buffer animation after 200ms of playback. What was this for exactly ?

**Comment by danrossi** [comment]
ok something is up for some reason clearing the timer reference when its stopped and completed helps and leave weak references on the listener is ok. 

Playback and buffering progressive download in general is bad in safari which seems to reflect the changes in IOS7 also it's wierd. It looks like some network bug to me in safari no idea.

**Comment by danrossi** [comment]
looks better now, but this weak reference stuff might need to be moved to external listeners instead. instream looks better now.
