### ISSUE TITLE
bwcheck + pseudostreaming: only checkOnStart supported

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#164]
If you do not specify `checkOnStart: true` bwcheck just hangs with pseudostreaming:
http://flowplayer.blacktrash.org/test/bwcheck-pseudo.html (uses 3.2.17-dev - but also present before).

[I think I reported this before, but cannot find the issue]

**Comment by phloxic** [comment]
HDDN is driving me around the bend. Update:
- video plays but
- no stream switch on fullscreen toggle, no onBwDone fired like with `checkOnStart: true`

**Comment by danrossi** [comment]
i'll prioritise these next.

**Comment by danrossi** [comment]
i'm experiencing the same thing. i have made a change to the config, if checkonstart is not set, and its not set to dynamic enable bandwidth checking. your config did not have it available therefore no onBwDone. You can see the file is sitting there pending, and its likely it needs ?start=0 for some reason.

**Comment by danrossi** [comment]
no idea but it needs ?start=0 on the initial request. and the 800k video has a slow start time because of possibly latency and metadata.

**Comment by danrossi** [comment]
it's re-requesting the bandwidth when changing to fullscreen however perhaps a different method could be used for pseudo to capture it from the current file playing when changing to fullscreen no idea.

**Comment by danrossi** [comment]
I just checked back its now not hanging very strange. I reckon its latency/caching issues with hddn. I can initiate the pull request again if requesting the start param won't cause issues.

**Comment by danrossi** [comment]
ok I can confirm it was probably random playback was really slow for me too. i'll just commit the bwcheck change if people want to changebust they could do it on the config perhaps.

**Comment by danrossi** [comment]
wasn't neccesary, reverted the change.
