### ISSUE TITLE
API Safari 6 Flash detection

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#167]
Leads currently to unreliable results. Even when Flash is turned off `flashembed.getVersion()` or flashembed.isSupported()` report as if the plugin was enabled.
Additional conditional(s) something like:

``` js
navigator.plugins["Shockwave Flash"]["application/x-shockwave-splash"].enabledPlugin != null // enabled
```

**Comment by phloxic** [comment]
@bbbo, @anssip - fix can be tested here: http://flowplayer.blacktrash.org/test/flashtest.html - turn Flash on and off in Safari and other browsers; for comparison turn off Flash in Safari 6 (at least on Mac) in any example.

**Comment by anssip** [comment]
@blacktrash please verify, latest in dev94

**Comment by phloxic** [comment]
Are you sure? dev94 still uses http://flash.cdn.dev94.flowplayer.us.s3.amazonaws.com/js/flowplayer-3.2.12.min.js

**Comment by anssip** [comment]
Checking this.

**Comment by anssip** [comment]
Now dev94 uses 3.2.13-dev.min.js. Also all flash and js plugins have now their version numbers pumped up.

**Comment by phloxic** [comment]
Confirming that this fixes the problem in the browsers available to me, including Safari 6.
@bbbo - can you try e.g. http://flash.dev94.flowplayer.us/demos/standalone/installation/index.html with (also older) IE, turning Flash on/off. When off the expressInstall should be shown, otherwise the player (obviously, hopefully).

**Comment by bbbo** [comment]
this seems to work fine in IE7 / 8 / 9 .
