### ISSUE TITLE
3.2.17: unexpected security errors with direct embedding

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#181]
No clear pattern of failure:
Both
http://flash.flowplayer.org/demos/commercial/embed.html :-1:
http://flowplayer.blacktrash.org/embed-commercial.html :-1: 

http://flowplayer.blacktrash.org/viralvideos-extconfig.html :+1:  with rather more involved embed code from here: http://flash.flowplayer.org/demos/plugins/flash/viralvideos-extconfig.html

**Comment by phloxic** [comment]
In all likelyhood caused by the XSS tightening: https://github.com/flowplayer/flash/issues/121
But what exactly is causing what failure?

**Comment by phloxic** [comment]
Note that the error is not fatal. The player works as expected - except for the display of the error message.

**Comment by danrossi** [comment]
Security sandbox due to the new Focus feature added to the launcher. It's strange its happening when trying to add a javascript callback. Perhaps the function is missing. the crossdomain files are added to both sub domains.

**Comment by danrossi** [comment]
I believe it's the code to add focus for tabbing remember that guy talking about it ? I didn't do this sorry.

**Comment by anssip** [comment]
Adding allowScriptAccess to the embed code fixes it:

```
        <param name="allowScriptAccess" value="always" />
```

**Comment by phloxic** [comment]
But I cannot govern the embed parameters - e.g. Facebook does not allow "always".
It's clearly a bug imho, as it happens "temporarily" upon initialization.
The workaround hack would be to add `showErrors: false` to configurations which are known to work - but that's not a solution.

**Comment by phloxic** [comment]
To be precise: we can offer _our_ embed code with allowscriptaccess - but we can't control the embed parameters e.g. when sharing.

**Comment by phloxic** [comment]
I thought the accessibility code only came into action if `seamlessTabbing: "true"` in the Flash config and a few other requirements are met? http://flash.flowplayer.org/documentation/configuration/player.html#standard-flash-parameters
On the other hand I never could spot a difference in behaviour with or without those parameters and assumed they came into play with screen readers. I never received any _clear_ information on this, all info I collected borders on speculation, e.g. here: http://flowplayer.blacktrash.org/test/accessibility.html
But that code should not influence direct embedding, should it?

**Comment by danrossi** [comment]
The Focus class added in deals with forcing focus to the flash object I believe ?. It's doing a javascript bridge call / setup therefore requires allowscriptaccess enabled. I assume it needs a try / catch around the setup of that perhaps to trap the error.

**Comment by anssip** [comment]
Yes, a try/catch is needed there. I'll probably release a bug fix for this later this week.

**Comment by anssip** [comment]
Fixed here: the security error is fixed here: http://flash.182f.flowplayer.me  @blacktrash can you please verify.

**Comment by phloxic** [comment]
:+1: http://flash.182f.flowplayer.me/demos/commercial/embed.html

**Comment by phloxic** [comment]
Fixed in 3.2.18 - closing.
