### ISSUE TITLE
coop: loadCaptions still a no-op

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#19]
@danrossi, @anssip - the captions plugin is still at version 3.2.8, although
http://code.google.com/p/flowplayer-core/issues/detail?id=574
declares this as fixed.

Probably @danrossi's dropbox version fixes it:
https://dl.dropbox.com/u/3394987/flowplayer.captions-3.2.8.zip

Looks like @danrossi's fix never made it into svn (now git).

See also: http://flowplayer.org/forum/4/103398

**Comment by phloxic** [comment]
Here's a working demo with @danrossi's dev version and 3.2.15:
http://flowplayer.blacktrash.org/test/captionswitch.html

**Comment by danrossi** [comment]
Hi my fixes were added to svn ages ago, and it is indeed in github. Hmm which file has the problem ? I found there is a build file issue so the plugin isn't compiling correctly.

**Comment by danrossi** [comment]
It's working fine here.

**Comment by phloxic** [comment]
But it was never released. 3.2.8 came out in January, bug report and your fix came later.

**Comment by danrossi** [comment]
Yes I don't know about that but you were saying it never made it to svn I had to do some digging around and it was all in tact :)

**Comment by phloxic** [comment]
Ah, I see ;-)

@anssip - I am for testing and pushing just a new captions plugin (after all we have separate versioning) to fix this long-standing bug.

**Comment by anssip** [comment]
Yep, will release also captions.

**Comment by phloxic** [comment]
This can be closed.
