### ISSUE TITLE
RTMP Buffering Issue

### ISSUE THREAD

**Issue by ghost** [flowplayer/flash#191]
I have an issue with the buffering progress bar (slider) of the video. Buffering keeps appearing and disappearing intermittently, and then just disappears after a while (around the middle of the video). My environment is flowplayer version 3.2.15 and wowza streaming RTMP VOD files with ABR.
Please check minimal player configurations here: http://flowplayer.blacktrash.org/test/bwcheck-smil.html

And here:
http://dev.streamtrix.com/embed/video/MjAyLTA=

**Comment by anssip** [comment]
Investigating this now.

**Comment by anssip** [comment]
This is fixed now. Can be tested with these:
http://flash.cdn.201f.flowplayer.me.s3.amazonaws.com/swf/flowplayer-3.2.19-dev.swf
http://flash.cdn.201f.flowplayer.me.s3.amazonaws.com/swf/flowplayer.controls-3.2.17-dev.swf

**Comment by ghost** [comment]
Many thanks Anssip for your efforts.
Should I wait the update in your website to download the commercial version

**Comment by anssip** [comment]
The commercial version is here: http://flash.cdn.201f.flowplayer.me.s3.amazonaws.com/swf/flowplayer.commercial-3.2.19-dev.swf

Sorry i forgot include a link to this.

**Comment by ghost** [comment]
NVM Anssip, Thanks a lot for your efforts and hard work.

**Comment by ghost** [comment]
Hello All,
Any news about Instream clips issue?
