### ISSUE TITLE
accelerated: still shows flowplayer branding

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#20]
The flowplayer branding in the bottom left corner is still visible during playback:
- Flash 11.3: in fullscreen mode
- Flash 10.3: always

@danrossi - you avoided testing this by offering a _commercial_ test player:
http://code.google.com/p/flowplayer-core/issues/detail?id=627#c18

This should be tested with a free player.

**Comment by danrossi** [comment]
What did I avoid sorry ? What is the problem ?

**Comment by phloxic** [comment]
With the free player the fp branding at the bottom left corner should only be visible during clip load, not during playback. This cannot be checked with a commercial player as the _prominent_ branding will always be visible.

![hw branding](http://www.blacktrash.org/downloads/tmp/flowplayer/hw_branding.jpg)

Strangely enough, Opera with Flash 10.3 also shows it in fullscreen only. Safari 5.0.6 and Firefox 15.0.1 with Flash 10.3 always show it.

But the bottom left branding should never be visible during playback in the free version.

**Comment by danrossi** [comment]
I'll have to check it's indexing, the display position has been the problem the whole time and was breaking before depending what player is used because of the logo I thought that was working now, so it needs to display underneath instead and the commercial logo on top like the other elements. The screen mask which was added back in has to move to the bottom layer to display everything else on top. I might have to use compiler flags to change this for the free version.

**Comment by danrossi** [comment]
OK the commercial logo is supposed to display above and the free logo is supposed to display underneath. I'll try and swap it around for the free player.

**Comment by danrossi** [comment]
https://dl.dropbox.com/u/3394987/flowplayer-3.2.15.zip

**Comment by phloxic** [comment]
Exactly the same behavior. Perhaps because on my machine stage video is never used for some reason.

**Comment by danrossi** [comment]
skype

**Comment by danrossi** [comment]
one more time before skype ;) https://dl.dropbox.com/u/3394987/flowplayer-3.2.15.zip im thinking it didn't package correctly.

**Comment by danrossi** [comment]
here https://dl.dropbox.com/u/3394987/stagevideo.png

**Comment by phloxic** [comment]
https://dl.dropbox.com/u/3394987/flowplayer-3.2.15.zip LGTM ;-)

**Comment by danrossi** [comment]
LGTM ?

**Comment by danrossi** [comment]
It's back ! farout. Let me know if its working for you now.

**Comment by phloxic** [comment]
```
$ wtf lgtm
LGTM: looks good to me
```

;-)

What is back? The latest dropbox file seemed to work on my end - I have not access to the very latest Flash versions though.

**Comment by danrossi** [comment]
Github database has been crashing for the past 2 days, and takes up to two hours for them to recover it, it may go down daily from the looks of it.

**Comment by danrossi** [comment]
It hinders productivity on my end because I'm on a time limit because of my timezone obviously. google code would never do this ;)

**Comment by danrossi** [comment]
fixed and merged. AFR hehe :).

**Comment by danrossi** [comment]
Here is a question, is there a way to move these tickets into a to release mode, there is no such method here and makes it hard to track what to release obviouslly.

**Comment by phloxic** [comment]
Probably a "ready for testing" label would be good. - I haven't found a way to create one.

**Comment by danrossi** [comment]
let me know if you do that would be great.

**Comment by danrossi** [comment]
just did it hehe.

**Comment by danrossi** [comment]
closing for now
