### ISSUE TITLE
Master Build Folowing "For Developers" documentation does not work

### ISSUE THREAD

**Issue by MasterOliveira** [flowplayer/flash#202]
I tried to building several branches "release-3-2-16", "master" and "dev" following the documentation.

Java1.6.0_45, Ant1.9.3 and Flex4.6 are installed and added to the PATH variable

I keep getting the output:
C:\Flow\flash-build>ant
Buildfile: C:\Flow\flash-build\build.xml
     [echo] flowplayer version 3.2.18

check-uptodate:
     [echo] main up-to-date: ${uptodate.main}
     [echo] main up-to-date: ${uptodate.commercial}
     [echo] lib up-to-date: ${uptodate.lib}

concat-flowplayer.js:

flowplayer.js:

source:
     [copy] Copying 1 file to C:\Flow\flash-build\dist
     [echo] C:\Flow\flash-build/dist/flowplayer.js --> C:\Flow\flash-build/dist/
flowplayer-3.2.13.js copied
     [echo] C:\Flow\flash-build/dist/flowplayer-3.2.13.js build

min:
     [echo] C:\Flow\flash-build/dist/flowplayer-3.2.13.js minified

build-lib:
     [echo] flowplayer version 3.2.18

prepare:
     [echo] flowplayer version 3.2.18

compile-lib:
     [echo] running C:/Program Files (x86)/Adobe/Adobe Flash Builder 4.5/sdks/4.
5.0/bin/compc.exe with classpath ../flash/core/lib/corelib/src ../flash/core/lib
/goasp/src_go ../flash/plugins/controls/src/actionscript ../flash/lib/common/src
/actionscript ../flash/core/src/actionscript-builtin, using manifest manifest.xm
l
     [exec] Error loading: C:\Program Files\Java\jdk1.6.0_45\jre\bin\server\jvm.
dll

BUILD FAILED
C:\Flow\flash-build\build.xml:270: The following error occurred while executing
this line:
C:\Flow\flash-build\build.xml:278: exec returned: 6

Total time: 1 second

**Comment by MasterOliveira** [comment]
mxmlc is NOT compatible with java 64bit versions, that was the problem...

**Comment by anssip** [comment]
Hopefuly we will get a compatible Flex SDK from Adobe.
