### ISSUE TITLE
bitrateselect + live streams?

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#209]
Is it supposed to work? It does not.
You can make it work by stop-starting the stream - switch happens after stop.
But it does not work per se.
Demo: http://flowplayer.blacktrash.org/test/live-brselect.html
See also this forum thread: http://flowplayer.org/forum/#!/setup#live-rtmp-bitrate-select-me

**Comment by ViliusS** [comment]
Works for me with Flash Server.

**Comment by molnarr2** [comment]
Running Evostreamms 1.6.5:

http://smglivestream.com/client/testareaBitrate2.php

Here is an unsuccessful HD -> SD livestream brselect:

09:34:43.344 "[LOG] time 09:34:43.343 :: org.flowplayer.rtmp::RTMPStreamProvider : switchStream called" testareaBitrate2.php
09:34:43.345 "[LOG] time 09:34:43.344 :: org.flowplayer.rtmp::RTMPStreamProvider : doSwitchStream() calling play2()" testareaBitrate2.php
09:34:43.487 "[INFO] time 09:34:43.486 :: org.flowplayer.rtmp::RTMPStreamProvider : _onNetStatus, code: NetStream.Play.Transition" testareaBitrate2.php
09:34:43.487 "[LOG] time 09:34:43.487 :: org.flowplayer.rtmp::RTMPStreamProvider : using the default connection provider" testareaBitrate2.php
09:34:43.488 "[INFO] time 09:34:43.488 :: org.flowplayer.rtmp::RTMPStreamProvider : onNetStatus(), code: NetStream.Play.Transition, paused? false, seeking? false" testareaBitrate2.php
09:34:43.489 "[LOG] time 09:34:43.489 :: org.flowplayer.rtmp::RTMPStreamProvider : Stream Transition -- livestreamLOW" testareaBitrate2.php
09:34:43.489 "[LOG] time 09:34:43.489 :: org.flowplayer.rtmp::RTMPStreamProvider : silentSeek == false" testareaBitrate2.php
09:34:43.490 "[LOG] time 09:34:43.490 :: org.flowplayer.rtmp::RTMPStreamProvider : dispatching [ClipEvent type="onSwitch" info="livestreamLOW"] on clip [Clip] 'livestreamLOW'" testareaBitrate2.php
09:34:46.669 "[INFO] time 09:34:46.668 :: org.flowplayer.rtmp::RTMPStreamProvider : _onNetStatus, code: NetStream.Video.DimensionChange" testareaBitrate2.php
09:34:46.670 "[LOG] time 09:34:46.670 :: org.flowplayer.rtmp::RTMPStreamProvider : using the default connection provider" testareaBitrate2.php
09:34:46.670 "[INFO] time 09:34:46.670 :: org.flowplayer.rtmp::RTMPStreamProvider : onNetStatus(), code: NetStream.Video.DimensionChange, paused? false, seeking? false" testareaBitrate2.php
09:34:46.690 "[LOG] time 09:34:46.690 :: org.flowplayer.rtmp::RTMPStreamProvider : onPlayStatus() -- NetStream.Play.TransitionComplete" testareaBitrate2.php
09:34:46.690 [Array] testareaBitrate2.php
09:34:46.690 [Object] testareaBitrate2.php
09:34:46.691 "[String] code = NetStream.Play.TransitionComplete" testareaBitrate2.php
09:34:46.691 "[String] level = status" testareaBitrate2.php
09:34:46.692 "[LOG] time 09:34:46.692 :: org.flowplayer.rtmp::RTMPStreamProvider : silentSeek == false" testareaBitrate2.php
09:34:46.693 "[LOG] time 09:34:46.693 :: org.flowplayer.rtmp::RTMPStreamProvider : dispatching [ClipEvent type="onSwitchComplete" info=null] on clip [Clip] 'livestreamLOW'" testareaBitrate2.php

Here is a successful HD -> SD:

09:30:30.267 "[LOG] time 09:30:30.266 :: org.flowplayer.rtmp::RTMPStreamProvider : switchStream called" testareaBitrate2.php
09:30:30.268 "[LOG] time 09:30:30.267 :: org.flowplayer.rtmp::RTMPStreamProvider : doSwitchStream() calling play2()" testareaBitrate2.php
09:30:30.399 "[INFO] time 09:30:30.398 :: org.flowplayer.rtmp::RTMPStreamProvider : _onNetStatus, code: NetStream.Play.Transition" testareaBitrate2.php
09:30:30.400 "[LOG] time 09:30:30.399 :: org.flowplayer.rtmp::RTMPStreamProvider : using the default connection provider" testareaBitrate2.php
09:30:30.400 "[INFO] time 09:30:30.400 :: org.flowplayer.rtmp::RTMPStreamProvider : onNetStatus(), code: NetStream.Play.Transition, paused? false, seeking? false" testareaBitrate2.php
09:30:30.401 "[LOG] time 09:30:30.401 :: org.flowplayer.rtmp::RTMPStreamProvider : Stream Transition -- livestreamLOW" testareaBitrate2.php
09:30:30.402 "[LOG] time 09:30:30.401 :: org.flowplayer.rtmp::RTMPStreamProvider : silentSeek == false" testareaBitrate2.php
09:30:30.402 "[LOG] time 09:30:30.402 :: org.flowplayer.rtmp::RTMPStreamProvider : dispatching [ClipEvent type="onSwitch" info="livestreamLOW"] on clip [Clip] 'livestreamLOW'" testareaBitrate2.php
09:30:30.405 "[INFO] time 09:30:30.405 :: org.flowplayer.rtmp::RTMPStreamProvider : _onNetStatus, code: NetConnection.Connect.Closed" testareaBitrate2.php
09:30:30.406 "[LOG] time 09:30:30.406 :: org.flowplayer.rtmp::RTMPStreamProvider : using the default connection provider" testareaBitrate2.php
09:30:30.407 "[INFO] time 09:30:30.407 :: org.flowplayer.rtmp::RTMPStreamProvider : onNetStatus(), code: NetConnection.Connect.Closed, paused? false, seeking? false" testareaBitrate2.php
09:30:30.409 "[LOG] time 09:30:30.408 :: org.flowplayer.rtmp::RTMPStreamProvider : stop called" testareaBitrate2.php
09:30:30.409 "[LOG] time 09:30:30.409 :: org.flowplayer.rtmp::RTMPStreamProvider : doStop" testareaBitrate2.php
09:30:30.410 "[LOG] time 09:30:30.410 :: org.flowplayer.rtmp::RTMPStreamProvider : doStop(), closing netStream and connection" testareaBitrate2.php
09:30:30.453 "[LOG] time 09:30:30.453 :: org.flowplayer.rtmp::RTMPStreamProvider : silentSeek == false" testareaBitrate2.php
09:30:30.454 "[LOG] time 09:30:30.454 :: org.flowplayer.rtmp::RTMPStreamProvider : dispatching [ClipEvent type="onBufferStop" info=null] on clip [Clip] 'livestreamLOW'" testareaBitrate2.php
09:30:30.462 "[LOG] time 09:30:30.461 :: org.flowplayer.rtmp::RTMPStreamProvider : silentSeek == false" testareaBitrate2.php
09:30:30.463 "[LOG] time 09:30:30.462 :: org.flowplayer.rtmp::RTMPStreamProvider : dispatching [ClipEvent type="onStop" info=null] on clip [Clip] 'livestreamLOW'" testareaBitrate2.php

**Comment by danrossi** [comment]
^ not a supported product, never tested. 

This has been raised 3 times before and switching does work with rtmp assuming the publishing filename is setup correctly with the indexing flags.

**Comment by phloxic** [comment]
Indexing flags? Providing the label is sufficient, and I have an example where this indeed works with a live stream (I am not allowed to share it though, for privacy reasons).
Closing because the original stream for this report is not available.
