### ISSUE TITLE
clip urls handled differently in config and API methods wrt url-escaping

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#21]
Becomes obvious when dealing with cloudfront signed urls:
- within the configuration ampersands and equal signs in the query string of a clip url _must_ be url-escaped
- when given as argument to a player method like `play()` or `setClip()` the query string must _not_ be url-escaped

Demo - source code docs update available soon:
http://flowplayer.blacktrash.org/cfxsigned.php

See also: http://flowplayer.org/forum/8/103438

I will try to investigate whether this inconsistency is triggered by the API. @danrossi - could you look into it from the core or rtmp plugin perspective please?

**Comment by danrossi** [comment]
It's not being double encoded if thats what you mean unless the encoding clip option is set.

**Comment by phloxic** [comment]
So far I cannot find anything in flowplayer.js which explains this differing behavior or requirement. Very very strange.

**Comment by danrossi** [comment]
Hi this seems correct to me, because it's json, it will need escaping, the flash api method is not json, therefore would take the direct call.

**Comment by phloxic** [comment]
Nah, play takes a json argument, as it does in the demo:

``` js
$f().play({
  // possibly more clip config
  url: '/path/to/video.mp4'
});
```

As always, non-json argument is just a shorthand for json. In the case of play it accepts either a string as clip url or an integer as playlist index or an array (containing json formatted objects) as playlist ...
http://flowplayer.org/documentation/api/player.html#methods

**Comment by danrossi** [comment]
Not in the js api, the json sent to flash, it's different than the plugin method, a converted object is sent directly the flash api method.

**Comment by danrossi** [comment]
see genericPlay(param:Object = null, instream:Boolean = false) , an object is sent to this there is no json parsing involved, wheras via the playlist config it is.

**Comment by phloxic** [comment]
Hm, that's pretty inconsistent UI.

Plus I wonder wether this is related to events not being passed via `setPlaylist`: http://code.google.com/p/flowplayer-core/issues/detail?id=609

**Comment by danrossi** [comment]
I'll explain again, the main config is sent as a string to flash embed which is parsed in flash, therefore the json string formatting requirements. When using the external methods of flash, a javascript object is sent to the arguments its not a json string.

**Comment by phloxic** [comment]
That's what I'm saying: It's bad UI-design ;-)
- clearly goes against principle of least surprise
- undocumented - not the least because it's hard to explain

imho one of the API's tasks is to hide such problems from the user, or at least to offer a consistent behavior.

Have to think about this, as I have now an idea what it is about. Perhaps it must be that way, but then I have to find a concise user-friendly explanation.

**Comment by danrossi** [comment]
Different technologies require different requirements I suppose. One is a json string, one is a standard object. The only way around it would mean not send the config to the player embed at all and call an external method which sends a javascript object instead.

**Comment by phloxic** [comment]
For the moment don't change anything ;-)

Maybe this can be solved in the API at least (escaping in direct embedding can leave users on their own), i.e. url-escape ampersands and equal signs of urls _only_ which are used in the embed code. - We have now a reliable detection to split out queries in the ipad plugin already. I'll have a look at some point.

**Comment by danrossi** [comment]
Well, the code to do the escaping of the values was taken out. But could be put back in I suppose ?

**Comment by phloxic** [comment]
No no! - That code escaped blindly _everything_ (entire urls, content plugin configs etc. and legal escape sequences like %26 to %%26), if we implement it at all it should encode only the query strings of urls and probably only ampersands and equal signs. If at all really clever, not over-clever ;-)

**Comment by danrossi** [comment]
Yeh thats because its looping through values, perhaps regexp might help to just process any url config.

**Comment by danrossi** [comment]
What did you want to do about this one ?

**Comment by phloxic** [comment]
When cycling through config massage the values of `url` keys by splitting off the query and replace ampersands and equal signs therein with their escape sequences.

But I don't have time before the fp5 release, this needs very careful testing.

**Comment by phloxic** [comment]
@danrossi - I've got this basically working, but try to work out all possible corner cases where this could break other things.

**Comment by phloxic** [comment]
closing
