### ISSUE TITLE
RTMP Small Start

### ISSUE THREAD

**Issue by Hunter-WebDev** [flowplayer/flash#210]
I am a little unsure of what is going on here, the video stays a 10px x 10px box until a few seconds in, then goes big, then you've missed the first part of the video. Not sure if there is already a fix for it or if I haven't created the right settings.

![screen shot 2014-02-25 at 1 45 54 pm](https://f.cloud.github.com/assets/5040696/2261308/27769b8c-9e4d-11e3-9e78-cdd5ed5cabb4.png)

Any help is much appreciated!

Thanks.

**Comment by bbbo** [comment]
please post this in the forums, along with a link to an actual example.
