### ISSUE TITLE
bwcheck_httpstreaming setup works in 3.2.16, but not in 3.2.18

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#221]
Comparison demo using the same stream:
http://flowplayer.blacktrash.org/test/purplestream.html
With 3.2.18 release and corresponding plugins the player stalls at stream switch. No problem with the 3.2.16 assets.

As our working demo at http://flash.flowplayer.org/demos/plugins/streaming/bwcheck-hds-live.html it uses version 1 manifests.

**Comment by danrossi** [comment]
Seems fine to me though there is something wrong with the other bitrate streams, its stuck in a live stall most likely not working. Are they able to confirm this ?  The other one does not switch to the 600k one because it doesn't have said changes.

**Comment by phloxic** [comment]
???
The demo has exactly the same configuration, including the same stream - except for the Flowplayer release.
The 3.2.18 release and corresponding plugins stall at the first switch attempt.
The 3.2.16 release and corresponding plugins happily switch bitrates (with the wrong reports in the events, known issue for that release #99, similarly #81, but functionaly ok).
Why does the same stream work in 3.2.16, but not in 3.2.18?

**Comment by danrossi** [comment]
There is something wrong with the 634 stream is what I'm trying to say. It's stuck in live stall once it has switched to it.

**Comment by danrossi** [comment]
clip: { bitrates: [ { bitrate: 634, isDefault: true } ] } might  display the problem not sure.

**Comment by phloxic** [comment]
You're right. 3.2.16 does not stall, but - contrary to its (buggy) diagnostics which announce a completed switch, it only _tries_ to switch, but stays on the same stream:

```
[LOG] time 02:45:52.851 :: org.osmf.net.httpstreaming::HTTPStreamSource : Prepare to switch the quality level to http://edge.purplestream.com/live/ttv/amlst:dttv/media_b400000_w549666525.abst/
[LOG] time 02:45:52.915 :: org.flowplayer.httpstreaming::HttpStreamingProvider : dispatching [ClipEvent type="onSwitch" info="http://edge.purplestream.com/live/ttv/amlst:dttv/media_b400000_w549666525.abst/"] on clip [Clip] 'http://edge.purplestream.com/live/ttv/amlst:dttv/media_b400000_w549666525.abst/'
[LOG] time 02:45:52.939 :: org.osmf.net.httpstreaming::HTTPStreamSource : Quality level switch in progress. The next chunk will use the quality level [0] with stream [http://edge.purplestream.com/live/ttv/amlst:dttv/media_b400000_w549666525.abst/ ].
[LOG] time 02:45:53.62 :: org.osmf.net.httpstreaming::HTTPStreamSource : Quality level switch completed. The current quality level [0] with stream [/ ].
[LOG] time 02:45:53.668 :: org.osmf.net.httpstreaming::HTTPStreamSource : Prepare to switch the quality level to http://edge.purplestream.com/live/ttv/amlst:dttv/media_b768000_w549666525.abst/
[LOG] time 02:45:53.682 :: org.flowplayer.httpstreaming::HttpStreamingProvider : dispatching [ClipEvent type="onSwitch" info="http://edge.purplestream.com/live/ttv/amlst:dttv/media_b768000_w549666525.abst/"] on clip [Clip] 'http://edge.purplestream.com/live/ttv/amlst:dttv/media_b400000_w549666525.abst/'
[LOG] time 02:45:53.697 :: org.osmf.net.httpstreaming::HTTPStreamSource : Quality level switch in progress. The next chunk will use the quality level [2] with stream [http://edge.purplestream.com/live/ttv/amlst:dttv/media_b768000_w549666525.abst/ ].
[LOG] time 02:45:53.780 :: org.flowplayer.httpstreaming::HttpStreamingProvider : dispatching [ClipEvent type="onSwitchComplete" info=null] on clip [Clip] 'http://edge.purplestream.com/live/ttv/amlst:dttv/media_b400000_w549666525.abst/'
[LOG] time 02:45:59.684 :: org.osmf.net.httpstreaming::HTTPStreamSource : Quality level switch completed. The current quality level [2] with stream [/ ].
```

Log reports quality level [2], but it stays on media_b400000_w549666525.abst

**Comment by danrossi** [comment]
The other rates begin playback but then get stuck and it doesn't continue. Can be seen here, they should fixup their individual streams first

http://www.osmf.org/dev/2.0gm/StrobeMediaPlayback.html?src=http://edge.purplestream.com/live/ttv/amlst:dttv/manifest.f4m

**Comment by phloxic** [comment]
Closing this.
