### ISSUE TITLE
DNN load issue

### ISSUE THREAD

**Issue by willwh** [flowplayer/flash#232]
Hi guys,

I am using the latest DNN (dotnetnuke CMS) and I'd like to use flowplayer flash to display content.

The flash object is not visible on page load.

My flash object is displayed when I click on the area of the page where the SWF should be located.

If I do this with the net inspector open, when I load the page, I see the div I've used to init the player, and using the HTML inspector with Firebug, I see the javascript in the HTML source.

Once I click in the area the player should be displayed, the <script> //flowplayer config </script> disappears and is replaced by the object/embed. (in Firebug HTML inspector)

I've tried using jquery's ready() function, as well as $(window).load(function () {}

Both "work" in that they will load the player after I click on the SWF location.

Any assistance or things to test you can offer would be great.

**Comment by danrossi** [comment]
If you aren't using the latest javascript api it sounds like there is space in the container or an image and is waiting for it to click. It's acting as a splash image and not loading the player yet.  Upgrade to the latest player and js api.

**Comment by willwh** [comment]
Hi dan, 

Thanks for the reply, I'm running the latest, flowplayer.commercial-3.2.18.swf and the flowplayer-3.2.13-min.js

Is there a way I can send you some details of this off-issue? Perhaps open a flowplayer support ticket?

**Comment by willwh** [comment]
After looking at this a little more, seems to be when I set an HTML entity runat="server" with asp.net - it fails to load.

I'll look at covering what I need with js/css and not try to do it in the c# :)

**Comment by willwh** [comment]
Almost forgot about this issue - turns out:

DNN generates the IDs in the markup on load..... so if you're setting flowplayer config like this:

$f('player //stuff');

Set "ClientIDMode="Static" on the <asp:panel ID="player">

Or (which is what I did) - write a DNN module to append the moduleID containing your flowplayer code to the asp:panel.
