### ISSUE TITLE
Allow to hide the replay-button per clip by configuration, without affecting the loading indicator

### ISSUE THREAD

**Issue by ghost** [flowplayer/flash#238]
When a clip ends, the default behavior now is to show a "Replay Video" button.
You can hide this button, setting `play: { opacity: 0.0 }` in the config, but this will also hide the default Play button as well as the loading indicator.

Please provide a flag to disable just that very button, so that after the video ends, there is nothing shown above the video.

**Comment by phloxic** [comment]
Try:

``` js
clip: {
  onBegin: function () {
    this.getPlay().css({opacity: 1});
  },
  onFinish: function () {
    this.getPlay().css({opacity: 0});
  }
}
```
