### ISSUE TITLE
httpstreaming: play button visible with playlists

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#27]
When playing through a playlist, the play button stays put after the first item has finished.

See: http://flowplayer.org/forum/8/103489
Sample by user: http://jsfiddle.net/pHfLn/3/

**Comment by kraiz** [comment]
+1

**Comment by danrossi** [comment]
Hi Kraiz. working on this ;)

**Comment by kraiz** [comment]
Great to hear!

**Comment by danrossi** [comment]
fixed here :( https://dl.dropbox.com/u/3394987/flowplayer.httpstreaming-3.2.9.zip

**Comment by kraiz** [comment]
Yeaha, this works. Thank you very much!

**Comment by danrossi** [comment]
all good

**Comment by danrossi** [comment]
closing for now
