### ISSUE TITLE
Live streaming controls

### ISSUE THREAD

**Issue by halibegic** [flowplayer/flash#270]
I disabled all the controls and enabled volume and full screen only to be used for live streaming. I'm wondering if it's possible to position these two controls on the right side? Currently it displays it on the left side.

![live](https://cloud.githubusercontent.com/assets/3328291/5149604/d1291230-71ca-11e4-85f1-1cd44c7a272f.png)

**Comment by danrossi** [comment]
try controls: { right: number }

**Comment by halibegic** [comment]
Thank you for the quick reply, but it's not working. Here is my configuration:

"controls": {
    "right": 0,
    "url": "flowplayer.controls-3.2.16.swf",
    "backgroundColor": "rgba(0,0,0,0)",
    "backgroundGradient": "none",
    "all": false,
    "volume": true,
    "mute": true,
    "fullscreen": true
}

**Comment by danrossi** [comment]
left: 50 or 
right: 50

try one of those and see if it moves across ? 

need to set width I guess also. It won't move if its set to 100% width.
