### ISSUE TITLE
bwcheck, f4m and onBeforeBegin

### ISSUE THREAD

**Issue by willwh** [flowplayer/flash#272]
Hi Guys,

Got a bit of an odd one, when using the following setup: http://flash.flowplayer.org/plugins/streaming/bwcheck-httpstreaming.html (i.e. bwcheck and f4m) with Wowza Media Server, and trying to secure the content, using some kind of token, I'm running in to some problems.

To describe what I'm doing:

I send two pieces of querystring to the server (it's a hash of a bunch of things), like so:

```
clip: { 
    url: 'smil:/_definst_/somedir/mysmil.smil/manifest.f4m?t=XXXXXXXXXX&s=XXXXXXXXXXX
    baseUrl: 'http://someserver/app'
},
onBeforeBegin: function() {
    $.get( "myAPI/grabanewtoken", function( data ) {
        if(data != window.streamToken) {
            $f('player').play('mysmil/mymanifest.f4m' + data);
        }
        window.streamToken = data;
    });
},
```

I then generate the same hash on the server side and compare, and ensure that the token is valid (based on time()).

The problem I'm seeing is as follows:

if I don't pass a token with the clip (i.e. the first click of "play") - playback is rejected by my stream server (it's session based)

If I do pass a token with the clip url, and still allow the API call to happen, flowplayer seems to really misbehave. I'm going to add some logs below if I can.

This is without the onBeforeBegin call to the API to generate a token: http://www.willwh.com/flowplayer-no-OnBeforeBegin.html

This is with onBeforeBegin: http://www.willwh.com/flowplayer-OnBeforeBegin.html

With the "no-OnBeforeBegin" -> playback starts beautifully

With the "onBeforeBegin" (i.e. API call for new token) -> playback will start, but the playhead timer doesn't move from 0:00, I don't get any video frames, only audio... (You'll see some 403 forbidden in this log) - but playback does sort of start.

Any ideas here? I've been poking at it for a few hours and not really any further forward here.

**Comment by willwh** [comment]
I should mention - this same methodology works really well for RTMP.

**Comment by willwh** [comment]
I'm only filtering on "org.flowplayer.httpstreaming_,org.flowplayer.f4m_" @ debug level, would there be anything else useful?

I can provide access to the site itself if needs be, email is on [my profile](https://github.com/willwh)

**Comment by danrossi** [comment]
you need to encode the specialchars in the url

**Comment by willwh** [comment]
Hi dan!

That doesn't really seem to be the issue I'm facing, perhaps you can help: 

Basically, after a long-ish pause, enough for the Session to time out on the stream server side, the few manifest chunks that have already been received (i.e. the buffer, for want of a better way to describe it) will play out, but then, I get 403's after the buffer is empty.

I'm thinking the best way to handle this might be something like the following:

onPause storing the getTime() -> and then when they click play again, fetch new token, and reload the player, requesting the same file, but also passing a start value to flowplayer, to seek to the right spot they were paused at.

Thoughts? :)

**Comment by willwh** [comment]
Looking through the docs, there does not seem to be a way to pass a start time to play() - can I pass a clip object in there? I am guessing I am doing something wrong here.

i.e. I tried a few variations of the following: 

```
onPause: function() {
    playTime = $f('player').getTime();
    console.log("We paused at: " + playTime + " seconds")
},
onResume: function() {
    $.get("/DesktopModules/NetroMedia.SecurePlay/API/SecurePlayApi/GetODToken?stream=<%= sStream %>", function(data) {
        if (data != window.netroToken) {
            var playOut = '<%= sStream %>' + data;
            var newclip = "clip:  { url: '" + playOut + "', " + "start: " + "'" + playTime + "' }";
            $f('player').play(newclip);
        }
        window.netroToken = data;
    });
},
```

Apologies for some c# in there, take that as the clip: { url }

**Comment by willwh** [comment]
I'm using some onpause and onresume functions and got my issue solved ;)
