### ISSUE TITLE
ipad: the player makes a GET request to HLS stream even when preload=none

### ISSUE THREAD

**Issue by xnejp03** [flowplayer/flash#273]
I'm not sure if this is related to iOS 8 only, but Safari on iPad makes the request when the player opens. It works correctly (ie no request until I press Play) in Safari on a mac.

This relates to HLS, but perhaps even to normal mp4 files (haven't tested it yet).

Btw, currently using the dev version of the plugin, as referenced here: https://flowplayer.org/forum/#!/open_word:ios-8-upgrade

**Comment by xnejp03** [comment]
@blacktrash any chance looking at this? You'd have to check your server logs to see if there is a GET request when the player opens with preload none.

**Comment by phloxic** [comment]
That's just iOS, I can see that in the Safari console for the iOS simulator at http://demos.flowplayer.org/videotest/no-preload.html - bauhaus.mp4 is requested. And desktop Safari does that as well, again I can see the GET request in timelines tab of the console.
Closing.

**Comment by xnejp03** [comment]
I tried it with simulator for iOS 7.1 and the request is not there, so it's either a new feature for iOS8 or another bug in iOS8.

**Comment by phloxic** [comment]
I get it in the simulator for 7.0, 7.1 (see screenshot) and 8.1
![ios71mp4get](https://cloud.githubusercontent.com/assets/168338/5519265/eef07508-8942-11e4-8d11-bfcfde840bb0.jpg)
