### ISSUE TITLE
Support multi-channel of subtitles

### ISSUE THREAD

**Issue by litvinok** [flowplayer/flash#282]
We already have ability to show subtitles with using the content plugin.
But when we have one or more subtitles on different languages we should have wrapper which will switch them.

I would suggest additional control element which will make able to switch between few subtitles like out-of-box solution.

This solution may include ability to use built-in to video subtitles as well.

(Source:  https://github.com/flowplayer/flowplayer/issues/777)

**Comment by danrossi** [comment]
http://flash.flowplayer.org/plugins/flash/captions.html there is an external api to change which data track to use for embedded subtitled.

**Comment by phloxic** [comment]
@litvinok - there are 2 ways of looking at builtin solutions, which is what I gather that you want: 1. they are easier to implement 2. they are less flexible.
For 1. we would have to offer a slew of options for the UI of the selector etc. which will blur the ease of implementation argument. In our opinion offering an API at this deep a configuration level offering a flexible API makes sense. YMMV.
The counter example is the CC button of this very plugin, where some users do not like the restricted out of the box offering ...
The source source for the plugin is open, so you _can_ build your "own box" solution.
As a midway solution you could use the menu plugin to select subtitle tracks: http://flash.flowplayer.org/plugins/flash/menu.html

**Comment by danrossi** [comment]
The external api is $f("#player").getPlugin("captions").loadCaptions(0, 'captions.xml');

**Comment by phloxic** [comment]
Closing. We will not offer a "builtin" solution. Tight integration can be achieved with `loadCaptions()` in combination with the menu plugin.
