### ISSUE TITLE
Flowplayer logs

### ISSUE THREAD

**Issue by oshurmamadov** [flowplayer/flash#284]
Please help....I cant read or find flowplayers logs

**Comment by danrossi** [comment]
the log config looks like

log: {
filter: "org.flowplayer.controller.*",
level: "debug"
}

If running this on chrome it needs to be on a server not locally loaded page because they broke the security manager.

**Comment by oshurmamadov** [comment]
Thanks for replay !!!

**Comment by danrossi** [comment]
Ok no worries closing this.
