### ISSUE TITLE
LiveRail Plugins SWF doesnt works with HTTPS

### ISSUE THREAD

**Issue by rgr2k** [flowplayer/flash#287]
When I try to call https://vox-static.liverail.com/swf/v4/admanager.swf it doesn't works. Only HTTP works...

There's some path to call a HTTPS?

**Comment by bbbo** [comment]
that's an issue for Liverail. Please contact them.

Trying to call the plugin via https faills regardless of Flowplayer (try curl / wget or opening it in a browser tab)
