### ISSUE TITLE
license validates sometimes without first hash char

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#29]
http://flowplayer.org/forum/8/103581#post-103586:

_It was my mistake. For the www domain I implemented the licencekey without the '#' and it works.
For the subdomain I implemented the key on the same way and it doesn't work.
Now I added the '#' and it works for the subdomain, too.
Not logical that it works on the www domain but it works now._

**Comment by phloxic** [comment]
This is still present in version 3.2.15:
http://www.blacktrash.org/test/commercial.html

**Comment by phloxic** [comment]
Truncated key for blacktrash.org validates against both www and flowplayer subdomains.

Customer truncated key validates against http://www.kv-rlp.de, but not on fortbildungstag2012.kv-rlp.de

**Comment by anssip** [comment]
The # character actually determines whether it will accept subdomains or not. Here are the rules:
- www subdomain is **always** accepted, whether # is present or not
- if # is present, all subdomains are accepted
- if # is not present, only www subdomain is accepted.

**Comment by phloxic** [comment]
thx - did not know about this, and, for the record, I made a mistake: without hash char the license does _not_ validate on the flowplayer.blacktrash.org domain.

**Comment by anssip** [comment]
"In the beginning" we were not sure how these subdomains should be handled and this #-character logic is there since those early days of FP 3 :-)
