### ISSUE TITLE
Firefox' click_to_play option breaks html based splash image setups

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#3]
Apparently Firefox' new click_to_play option breaks html based splash image setups.
See: http://flowplayer.org/forum/8/103116

A similar setting in Google Chrome is less problematic as a plugin symbol appears inside the container element, you can click it and the Flash plugin is activated to start playback. In Firefox there's only a black screen, and you have to click a plugin symbol in the location bar.

Investigate what we can do from the Flowplayer side to ease this problem.

**Comment by danrossi** [comment]
If we're touching the js api at any stage it might be any idea to implement #11, have had many people ask about it ?

**Comment by danrossi** [comment]
That's any evil option, could likely cause more havoc than good, as nothing is sacred from it's grasp it seems ;) Have already had problems with the js adware chrome ghostery extension.

**Comment by phloxic** [comment]
I agree. It punishes people who actually serve defensively so you would not need this setting: Flowplayer and html/css based splash image setup which does exactly that, Flash player is only loaded on demand of user.

I am for not pursuing this, unless a simple and undamaging idea crops up.

**Comment by phloxic** [comment]
wontfix - closing.
