### ISSUE TITLE
How can I use class instead of ID? I have more than one

### ISSUE THREAD

**Issue by acodercat** [flowplayer/flash#301]
How can I use class instead of ID? I have more than one

**Comment by phloxic** [comment]
http://flash.flowplayer.org/demos/installation/multiple-players.html

**Comment by acodercat** [comment]
i want to use hls

**Comment by phloxic** [comment]
http://flash.flowplayer.org/plugins/streaming/flashls.html

Please use our public forum https://flowplayer.com/forum/ for usage questions (mark your question as concerning Flowplayer Flash). Thank you.

**Comment by acodercat** [comment]
Where to download flashlsFlowPlayer.swf

**Comment by phloxic** [comment]
http://flash.flowplayer.org/plugins/streaming/flashls.html#download-and-documentation
Note that as you are deploying HLS, you should seriously consider migrating to Flowplayer HTML5. Flash is deprecated/disabled in all modern browsers by now, and for legacy IE Flowplayer HTML5 has Flash HLS backend builtin.

**Comment by acodercat** [comment]
i am not found,please give me download link

**Comment by phloxic** [comment]
http://flash.flowplayer.org/media/swf/flashlsFlowPlayer-0.4.4.24.swf

**Comment by acodercat** [comment]
thanks！
