### ISSUE TITLE
pseudo: play(same clip) plays audio only

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#31]
``` js
$f("player", "flowplayer-3.2.15.swf", {
  plugins: {
    pseudo: {url: "flowplayer.pseudostreaming-3.2.11.swf"}
  },
  clip: {
    provider: "pseudo",
    url: "http://pseudo01.hddn.com/vod/demo.flowplayervod/Extremists.flv"
  }
});

document.getElementsByTagName("button")[0].onclick = function () {
  $f().play({url: "http://pseudo01.hddn.com/vod/demo.flowplayervod/Extremists.flv"});
};
```

When you click the button, only audio is played. Does not happen without pseudostreaming.

**Comment by phloxic** [comment]
See also: http://flowplayer.org/forum/5/103312#post-103378

**Comment by danrossi** [comment]
I think there is a flash player bug with http streams which is what I fixed in the cluster plugin, if you try and make a call to a different file its ok ie. It's a very strange bug indeed. I think the connection needs to be closed before playing the same file again.

http://www.blacktrash.org/php/streamer.php/ccc_trailer1.flv

**Comment by danrossi** [comment]
http://pseudo01.hddn.com/vod/demo.flowplayervod/Extremists.flv?start=0 this also works also, its some wierd cache issue, where it won't begin to play until the file has fully downloaded.

**Comment by danrossi** [comment]
ok, there was something in there preventing also onstart being called if it was the same file so needs to be cleared first, so it will dispatch the event.

**Comment by danrossi** [comment]
https://dl.dropbox.com/u/3394987/flowplayer.pseudostreaming-3.2.11.zip

**Comment by phloxic** [comment]
Works for me[tm].

**Comment by danrossi** [comment]
closing for now.
