### ISSUE TITLE
shared embed code duplicates flashvars in object's data and the movie param

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#34]
When you share a player configured with the sharing or viralvideos plugin, the resulting embed code uses the complete flash object including config query and not just flowplayer.swf as the object's data attribute and as value of the movie parameter:

``` html
<object name="player" id="_fp_0.7203061692416668" width="403" height="302"    data="http://www.blacktrash.org/swf/flowplayer.swf?config=http%3A%2F%2Fwww.blacktrash.org%2Fjs%2Fccc.fb.js"  type="application/x-shockwave-flash">    <param value="true" name="allowfullscreen"/>    <param value="always" name="allowscriptaccess"/>    <param value="window" name="wmode"/>    <param value="high" name="quality"/>    <param name="movie" value="http://www.blacktrash.org/swf/flowplayer.swf?config=http%3A%2F%2Fwww.blacktrash.org%2Fjs%2Fccc.fb.js" />    <param value="config=http://www.blacktrash.org/js/ccc.emb.js" name="flashvars"/>     <video controls width="403" height="302">
<source src="http://media.blacktrash.org/ccc.webm" /><source src="http://media.blacktrash.org/ccc.mp4" /><source src="http://media.blacktrash.org/ccc.ogv" />     </video>
</object>
```

That's because the embed code is generated from a "standalone" shared object which includes Better would be without appending the config query:

``` html
<object name="player" id="_fp_0.7203061692416668" width="403" height="302"    data="http://www.blacktrash.org/swf/flowplayer.swf"  type="application/x-shockwave-flash">    <param value="true" name="allowfullscreen"/>    <param value="always" name="allowscriptaccess"/>    <param value="window" name="wmode"/>    <param value="high" name="quality"/>    <param name="movie" value="http://www.blacktrash.org/swf/flowplayer.swf" />    <param value="config=http://www.blacktrash.org/js/ccc.emb.js" name="flashvars"/>     <video controls width="403" height="302">
<source src="http://media.blacktrash.org/ccc.webm" /><source src="http://media.blacktrash.org/ccc.mp4" /><source src="http://media.blacktrash.org/ccc.ogv" />     </video>
</object>
```

So far I have not observed any problems functionality-wise, but it would be good to have any query string starting with `?config=` from flowplayer.swf in the embed code's data and movie. Especially when the query does not point to a config file, but contains an entire configuration this makes it susceptable not the least for embedders making a tiny mistake when pasting embed code.

Come to think of it, we also have to investigate cases where users append e.g. versioning queries, like `flowplayer.swf?v=3.2.15`. And then append the config for sharing? Have to test whether this works at all.

**Comment by danrossi** [comment]
Hi mate where do you see this ?

Im looking at the code now and it should be generating like the bottom one with the flashvars config are you talking about urls with the config appended to it ? Do you have an example at all ??

See here its simply getting the swf url

https://github.com/flowplayer/flash/blob/master/plugins/viralvideos/src/actionscript/org/flowplayer/viralvideos/PlayerEmbed.as#L246

and

https://github.com/flowplayer/flash/blob/master/plugins/viralvideos/src/actionscript/org/flowplayer/viralvideos/PlayerEmbed.as#L252

is appending the config string here.

**Comment by phloxic** [comment]
This happens when you embed a _shared_ player. A shared player is something like this:
http://www.blacktrash.org/swf/flowplayer.swf?config=http%3A%2F%2Fwww.blacktrash.org%2Fjs%2Fccc.fb.js
Just click on the link and then use the embed code. It uses again the above as movie and data properties.

If you want to check it in the "real" world, go to http://www.facebook.com/blacktrashproductions and start one of the videos in the timeline and click embed. Or I'll send you a private fb message.

To me it looks like `_player.config.playerSwfUrl` should be stripped of any `?config=` queries.

**Comment by danrossi** [comment]
Yeah ok so the config goes in the right place, it just needs to string the query off the name of the player file. Did you want me to do this ?

**Comment by phloxic** [comment]
For safety, as already said, remove only if the query starts with `?config=`. And of course only for what is used in the embed code ;-)

Hm, just tried:
http://www.blacktrash.org/swf/flowplayer.swf?v=10&config=http%3A%2F%2Fwww.blacktrash.org%2Fjs%2Fccc.fb.js
or
http://www.blacktrash.org/swf/flowplayer.swf?config=http%3A%2F%2Fwww.blacktrash.org%2Fjs%2Fccc.fb.js&v=10
which seem to work as well. In both cases the `_player.config.playerSwfUrl` ideally should be turned into http://www.blacktrash.org/swf/flowplayer.swf?v=10 - i.e. just remove the config query and let the user shoot himself in the foot with his other queries ;-)

**Comment by danrossi** [comment]
Hmm that will require regular expression but I guess it shouldn't be an issue no problems.

**Comment by phloxic** [comment]
I don't see the need for regex. You should be able to split the query at the ampersands, pop the config query out of the list, rejoin with ampersands.

**Comment by danrossi** [comment]
As you said above it needs to take out the config param only.

**Comment by phloxic** [comment]
I'm sure something like this python code is also possible in actionscript:

``` python
>>> flashurl = 'http://www.blacktrash.org/swf/flowplayer.swf?v=10&config=http%3A%2F%2Fwww.blacktrash.org%2Fjs%2Fccc.fb.js&another=query'
>>> flashsplit = flashurl.split('?')
>>> if len(flashsplit) > 1:
...     queries = [query for query in flashsplit[1].split('&') if not query.startswith('config=')]
...     flashurl = '%s?%s' % (flashsplit[0], '&'.join(queries))                                                         ...
>>> print flashurl
http://www.blacktrash.org/swf/flowplayer.swf?v=10&another=query
```

No regex ;-)

**Comment by danrossi** [comment]
gosh no, i'll think of something no worries.

**Comment by danrossi** [comment]
I think I have something just testing it now. there is thankfully an internal method to handle parameters from strings.

**Comment by danrossi** [comment]
https://dl.dropbox.com/u/3394987/flowplayer.viralvideos-3.2.13.zip try this

**Comment by danrossi** [comment]
any luck with that change ?

**Comment by phloxic** [comment]
As soon as I can - release chaos here.

**Comment by phloxic** [comment]
Very late, but yes, https://dl.dropbox.com/u/3394987/flowplayer.viralvideos-3.2.13.zip looks ok.

**Comment by danrossi** [comment]
closing for now.
