### ISSUE TITLE
Closed caption plugin does not support current Timed Text specifications

### ISSUE THREAD

**Issue by hmatanock** [flowplayer/flash#35]
(bringing bug report over from http://code.google.com/p/flowplayer-core/issues/detail?id=578)

The captions plug-in does not fully support Timed Text specification. In particular it only works if you use the namespace,http://www.w3.org/2006/10/ttaf1, from an older "candidate recommendation"

http://www.w3.org/TR/2006/CR-ttaf1-dfxp-20061116/

If you use the correct namespace,http://www.w3.org/ns/ttml, then no captions appear. 

We are still able to replicate this behavior, using Flowplayer 3.2.15 and Captions plugin 3.2.9.

**Comment by anssip** [comment]
Working on this now.
