### ISSUE TITLE
Patch URL is invalid

### ISSUE THREAD

**Issue by ploden** [flowplayer/flash#38]
The URL for the patch mentioned in the Readme is invalid: http://apple-http-osmf.googlecode.com/issues/attachment?aid=170002000&name=apple-osmf.diff&token=1aj08zewyjMN-hOT1QJOhGISBdU%3A1342529151230

**Comment by danrossi** [comment]
Hi try this I didn't realise there was a token on the download

http://apple-http-osmf.googlecode.com/issues/attachment?aid=170002000&name=apple-osmf.diff&token=Ph2pWgXUNSROim-yKJ7pUn-fY00%3A1349069467875

If it was also on github I could have forked the project and done my fixes on there ;)

**Comment by danrossi** [comment]
I discovered that patch stopped working so I had to make a new one

http://apple-http-osmf.googlecode.com/issues/attachment?aid=230000000&name=apple-osmf.diff&token=Hu5TvlN1sZPifbc1jsflQDqINhg%3A1349094999280

**Comment by danrossi** [comment]
I'm starting work on MBR support as it requires a bit of a refactor so a new patch will be uploaded here eventually

http://code.google.com/p/apple-http-osmf/issues/detail?id=23

**Comment by danrossi** [comment]
Hi closing for this now if possible, Ive updated the link to the new patch.
