### ISSUE TITLE
bwcheck checkOnStart with cloudfront?

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#39]
checkOnStart not supported by cloudfront?

http://flowplayer.blacktrash.org/test/bwcheck-onstart.html#player1 returns -1 as bitrate.

In conjunction with brselect http://flowplayer.blacktrash.org/test/bwcheck-onstart.html#player1 returns undefined as bitrate.

**Comment by danrossi** [comment]
Looks fine here doesn't look like any FMS update has caused problems. Sometimes it does initially return a null value in which case it repeats the process.

**Comment by danrossi** [comment]
If possible are you able to add a log to org.flowplayer.bwcheck.detect.\* You may see a log like "Bandwidth Returned is zero starting again"

**Comment by phloxic** [comment]
Perhaps it was a temporary glitch at cloudfront. But it certainly did not work because it would have chosen a higher bitrate than it did.

Now however, we have a different issue, this time with wowza: their bwcheck returns either a way too low bitrate, currently I get with my connection:
cloudfront: 5463 kbps
hddn: 601 kbps

**Comment by danrossi** [comment]
Latency with hddn ?

**Comment by phloxic** [comment]
Pretty consistent at around 1/10 of what's reported for cloudfront. Strange. I also removed temporarily the cloudfront demo on the same page, but that did not affect the result.

btw, the undefined or -1 returned from cloudfront happens when I test on my local apache, that caused me to report the bug. What could be the reason for that? Not that it matters, except that it confused me and makes testing more longwinded.

**Comment by danrossi** [comment]
If you enable this log it might help org.flowplayer.bwcheck.detect.\* . I don't know what to say about the wowza thing, I do know wowza it's using an application they copied from my red5 application and it has issues calculating correctly over latency connections possibly because it needs to send a few more packets. Nothing is 100% I guess and probably should work together with dynamic functions but even the wowza stream statistics is different to FMS therefore switching is different.

**Comment by phloxic** [comment]
log configured at http://flowplayer.blacktrash.org/test/bwcheck-onstart.html

**Comment by danrossi** [comment]
Yep try playing one at a time as it could affect the packet send and recieve. See on the fms demo "Bandwidth Returned is zero starting again" check if this happens each time, you should be seeing this.

**Comment by phloxic** [comment]
When Wowza reports the correct bitrate in bwDone, the player still choose the lowest bitrate.
i.e. I can confirm http://flash.flowplayer.org/forum/5/104123#post-104232

**Comment by danrossi** [comment]
do you have a standalone wowza example , see above " try playing one at a time as it could affect the packet send and recieve" i dont see an issue though it returned 800 for me.

**Comment by phloxic** [comment]
Wait, I have to increase maxWidth ...

**Comment by phloxic** [comment]
Yup, maxWidth did the trick - sorry for the noise.

**Comment by danrossi** [comment]
I think it should be a non required option to be honest what do you think.

**Comment by danrossi** [comment]
hang on sorry i did add that option, if you disable screen qos option, it will disable the width checking for bandwidth checking on startup. If this is a bad option to use let me know.

**Comment by phloxic** [comment]
Ah, you're making the same mistake as me ;-) qos affect dynamic switching only, not checkOnStart, right?
To disable width checking in checkOnStart you must set maxWidth to a high value (makes sense once you grasp the concept).
However `qos: {screen: false}` breaks things. See: #47

**Comment by danrossi** [comment]
I might have fixed some problems here in 47, please take a look when you have a moment.

**Comment by phloxic** [comment]
This one can actually be closed in favour of #47 - the problems here were all sitting in front of the computer ;-)
