### ISSUE TITLE
linkUrl: disabled by query directly appended to domain name

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#40]
Both

``` js
linkUrl: "http://flowplayer.org?var=test"
```

or

``` js
linkUrl: "http://flowplayer.org/?var=test"
```

do nothing. Although `$f().getClip().linkUrl` returns the correct value.

``` js
linkUrl: "http://flowplayer.org/index.html?var=test"
```

works.

See also: http://flash.flowplayer.org/forum/3/103981

**Comment by danrossi** [comment]
Confirming this a problem, its likely due to how the launch function handles urls and might need to be encoded first.

**Comment by danrossi** [comment]
Right well its not even using that, its trying to use js external interface before attempting the flash one, might need to be encoded for js.

**Comment by phloxic** [comment]
If it's releated to encoding it would happen all the time with queries, wouldn't it? But it only happens with domain names.

**Comment by krisjahn** [comment]
Hi, even linkURL: encodeURIComponent('http://domain.tld?whatever=sometext') did not work. There must be a spell-checking, that need something like http://domain.tld/spellchecking/?whatever=sometext

**Comment by danrossi** [comment]
Out of curioisty what if you placed that url into js window.open('ttp://flowplayer.org?var=test,'_blank')

this is what it's running pretty much not the native function.

**Comment by danrossi** [comment]
Getting closer, its not even being configured because of the query string, therefore not launching anything.

**Comment by phloxic** [comment]
`window.open` works, and, as I wrote already, the linkUrl is also present in and retrievable via the JS api.

**Comment by danrossi** [comment]
Its not being configured that is why it's empty as I mentioned before. I have to dig around the config parser.

**Comment by danrossi** [comment]
Hi guys I tracked down the problem ahhh, it wasn't in the property binding stage or the config but there is indeed a url validation check before configuring each clip. It's a painfully log regex, so I'll see if I can fit in here something like domain.com/?foo=bar

**Comment by danrossi** [comment]
Try this https://dl.dropbox.com/u/3394987/flowplayer.commercial-3.2.15.zip

**Comment by phloxic** [comment]
Confirming that https://dl.dropbox.com/u/3394987/flowplayer.commercial-3.2.15.zip fixes the problem.

**Comment by danrossi** [comment]
closing for now

**Comment by adammada** [comment]
Another not working linkUrl:

http://go.arbopl.bbelements.com/please/redirect/416/23/1/43/!uwi=800;uhe=600;uce=1;param=147229/192566_1_?

removing "!" fixes it.
