### ISSUE TITLE
Captions/Subtitles always activated by default

### ISSUE THREAD

**Issue by Pelirrojo** [flowplayer/flash#41]
Hi,

Is it possible to prevent the default loading of subtitles in Flash FlowPlayer?
When I add the captions plugin, it always load the subtitles by default.

I've tried to set the property: showCaptions in both clip configuration section and plugin section but nothing happens.

I'm wondering if Is it a bug on the captions plugin?

Thanks in advance

**Comment by Pelirrojo** [comment]
@blacktrash says: The solution is in the button docs: specify display: "none" in the captionTarget content plugin config. Captions will only show after clicking the captions button.
Like 

me: Thanks!!!
It works fine!

**Comment by phloxic** [comment]
Hiding the captionTarget arguably only works around a bug: It does what it says: it hides the captions, but does not disable them. The indication is that the CC widget still shows them as enabled.
We can decide that _disabling_ captions is not on offer except for embedded captions (and then not dynamically). But then we should make this official.

**Comment by danrossi** [comment]
Yes I believe disabling the cuepoint listener when turning off then binding the listener again is an easy solution here. It may cause other issues in the process but would have to find them as it goes. It may be an idea to change the cc button to a dock button in the process if things are going to be changed.

**Comment by danrossi** [comment]
Did you want me to go ahead with this ?

**Comment by danrossi** [comment]
This is trivial to fix let me know if you want it done thanks.

**Comment by phloxic** [comment]
Would this disable user-configured cuepoints too?

**Comment by danrossi** [comment]
The requirement is to unbind the cuepoints listener so its not updating anything and then when activated bind the cuepoints listener again and it will start displaying the text again. It might be an idea to change the CC button to a dock button while we're at it as has been requested for a few years now. What do you think.

**Comment by danrossi** [comment]
The listener on the plugin that is cuepoints is still functioning as always it might be too much work, to clear out the subtitles cuepoints, or reload on demand might be too slow anyway. So cuepoints would still be dispatching in the player, is that where you want them disabled ?

**Comment by danrossi** [comment]
Another option would be to store the loaded cuepoints. when disabling remove them from the players cuepoints, and when enabling add them back in. They get added for each playlist item on startup so would have to be updated for each playlist item at once. A bit of work there. the simplest is to just unbind the event on the plugin.

**Comment by phloxic** [comment]
I think it's dangerous to fiddle with the already brittle cuepoints.

My proposal is to address this merely from the UI perspective: Think not "disable", but "hide".
1. Leave the documented mechanism in place that to hide subtitles, one has to hide the captionTarget plugin.
2. Allow the CC widget to be hidden/revealed by `$f().getPlugin("captions").hide()` and friends; also allow `display: none` in config. In other words make the plugin behave like the docs say that _all_ plugins behave. If this is too complicated, move the CC widget to the dock.

This seems like the least invasive change, while being most flexible at the same time.

**Comment by danrossi** [comment]
Ok i must of missed something because thats all the button does right now, hides / shows the content plugin.  no worries then.

**Comment by danrossi** [comment]
what is the purpose of hiding the button sorry ?

**Comment by phloxic** [comment]
To disable captions from the user perspective. E.g. start with a hidden captionTarget and offer a scripted/dynamic way to enable captions. When the button is visible user can just click on it.

**Comment by danrossi** [comment]
captiontarget: { display: "none" }, would cover hiding the content plugin. dock: true / false should cover configuring to enable a dock button or not (may aswell make it a proper dock button while we are at it ?? ) , external methods showCaptions / hideCaptions() should cover that. According to what I get from that info is what you need.  However also configurable via js ie  $f().getPlugin("captiontarget").toggle(); will toggle the display.

**Comment by danrossi** [comment]
what is the resolution for this ?

**Comment by anssip** [comment]
There's now external methods showButton() and hideButton() in the version currently in our dev site. These methods can be used to show and hide the CC button.

**Comment by phloxic** [comment]
Works.
But why new methods, and not the already advertised (for all plugins) `hide()` and `show()`?
Plugin special case because `css()` and `animate()` will never work?
I'm asking because it has to be documented.

**Comment by anssip** [comment]
I cannot make those generic functions work here easily, that's why special methods. I know this is not ideal.
