### ISSUE TITLE
hw accel + canvas backgroundGradient: bleached colors

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#45]
Resurrection of http://code.google.com/p/flowplayer-core/issues/detail?id=612

http://flowplayer.blacktrash.org/test/accel.html

The testing happened without backgroundGradient of canvas, like http://flowplayer.blacktrash.org/test/accel.html#player2

But the canvas shines through: http://flowplayer.blacktrash.org/test/accel.html#player1

Which most probably also explains why the flowplayer branding is visible during playback.

**Comment by ViliusS** [comment]
Confirmed.

**Comment by phloxic** [comment]
The bleached colors go away once I trigger fullscreen mode, and stay clean after exiting fullscreen. - The flowplayer branding hower stays visible.

**Comment by phloxic** [comment]
Same for commercial player: http://flowplayer.dev/test/commercial-accel.html

**Comment by danrossi** [comment]
https://dl.dropbox.com/u/3394987/svdemo1.png - your demo
https://dl.dropbox.com/u/3394987/svdemo2.png - my demo

I have no explanation for the top one, but in my demo it's fine with exactly the same code too and the logo is correctly indexed underneath the stage video area.

**Comment by danrossi** [comment]
Just in case here is a new build https://dl.dropbox.com/u/3394987/flowplayer-3.2.15.zip

**Comment by danrossi** [comment]
ok this hazy white is indeed the gradient you are seeing its on top still but on mine its positioned correctly. Im hoping there is code yet to be committed, the pull request is quite long now.

**Comment by danrossi** [comment]
the work is being done in #44

**Comment by danrossi** [comment]
this is fixed in #44, but cant commit yet until i confirm the nasty instream transition is working.

**Comment by danrossi** [comment]
btw the latest files have the fixes I discovered it was still messing up the indexing between the free and commercial player. And it also needs to swap the position of the free logo aswell as the copyright notice didn't discover it was separate until now :(

**Comment by ViliusS** [comment]
Fixed for me in 3.2.16 commercial.

**Comment by phloxic** [comment]
Confirming and closing.
Seems the fix comes at a price though: #75
