### ISSUE TITLE
bwcheck: maxWidth + qos: {screen: false} disables maxWidth onStart

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#47]
With this setting `maxWidth` is ignored:

``` js
bwcheck: {
  checkOnStart: true,
  dynamic: true,
  maxWidth: maxvideowidth,
  qos: {screen: false}
}
```

The first bitrate item is selected in checkOnStart, regardless of the reported bitrate.

**Comment by danrossi** [comment]
sorry thats for the dynamic rule.

**Comment by phloxic** [comment]
Yes, exactly. But setting it affects checkOnStart (basically disables it: the first item is selected), see above config which uses _both_ dynamic and checkOnStart.

**Comment by danrossi** [comment]
Its not clear what server but if its about wowza it was sending two callbacks so a connection close fixes that issue, the second callback was providing a lower value. 

https://dl.dropbox.com/u/3394987/flowplayer.bwcheck-3.2.11.zip

**Comment by danrossi** [comment]
the above should fix both issues it wasn't choosing the index from the bandwidth correctly I found :(

**Comment by danrossi** [comment]
Is this all good ?

**Comment by danrossi** [comment]
closing for now
