### ISSUE TITLE
Analytics plugin causing double visits if ga.js on page also

### ISSUE THREAD

**Issue by anssip** [flowplayer/flash#49]
See this: http://flash.flowplayer.org/forum/5/66460#post-104314

Need to investigate if it's possible to put the Bridge mode back to solve this - if the GA ActionScript library we are using still supports it. Or possibly if there is another solution for this.

**Comment by danrossi** [comment]
The sources are still maintained thankfully I dont see any other official library. There is a bridge mode option in there to use the externalinterface

http://code.google.com/p/gaforflash/source/browse/trunk/src/com/google/analytics/GATracker.as

**Comment by danrossi** [comment]
The irony, the sources are up to date the pre-compiled swc and documentation isn't. It needs refactoring. It looks like they've removed the visual debug interface but ill try and find it again.

**Comment by danrossi** [comment]
It seems to be working but I need to debug somehow if it's requesting it. i'll have to try and reinstate the tracker object config again or we can simply just use the accountId config as this is what is required to be sent to the api anyway. They've removed the debugger view, with compiler definitions to add logging therefore a new build is required to compile a debug version. The debug version is a little larger than the trimmed down version, though I usually run swf's through apparat reducer to trim the sizes down further.

**Comment by danrossi** [comment]
OK with the debug version all logging is sent to the standard console.

**Comment by danrossi** [comment]
It gets messier and messier. They've depreciated the old code see "_getTracker(account) deprecated" in favour of some clunky array push format. 

https://developers.google.com/analytics/devguides/collection/gajs/methods/

The library does not support that, I can commit what ive done so far but apart from the logs in the console, I cant see any requests being made.

**Comment by danrossi** [comment]
The old method doesn't work at all I think im getting no pixel requested. Need to use new method possibly.

**Comment by danrossi** [comment]
Seems to be working, it may need support for the new async method which im assuming is v5 which seems simple to do but the library would need modifying unless they do it themselves.

**Comment by danrossi** [comment]
closing for now
