### ISSUE TITLE
brselect: cuepoints fired multiple times

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#50]
In the following configuration cuepoints are fired multiple times. (Often) twice if no stream switch has happened, 4 times if a stream switch was triggered before the cuepoint was reached:

``` js
plugins: {
  pseudo: {
    url: 'flowplayer.pseudostreaming-3.2.11.swf'
  },
  brselect: {
    url: 'flowplayer.bitrateselect-3.2.13.swf',
    hdButton: {
      place: 'controls'
    }
  },
  content: {
    url: 'flowplayer.content-3.2.8.swf'
  }
},
clip: {
  provider: 'pseudo',
  baseUrl: 'http://pseudo01.hddn.com/vod/demo.flowplayervod',
  urlResolvers: 'brselect',
  bitrates: [
    {url: "bbb-800.mp4", bitrate: 800, sd: true, isDefault: true},
    {url: "bbb-1600.mp4", bitrate: 1600, hd: true}
  ],
  onMetaData: function (clip) {
    var dur = clip.duration,
    cues = [{
      time: dur * clip.cuepointMultiplier / 10,
      name: '10'
    }, {
      time: dur * clip.cuepointMultiplier / 2,
      name: '50'
    }];
    this.onCuepoint(cues, function (c, cuepoint) {
      this.getPlugin('content').append('cuepoint ' + cuepoint.name + '. ');
    });
  }
}
```

Even a simple:

``` js
onCuepoint([60000], function (clip, cuepoint) {
  this.getPlugin('content').append('cuepoint fired. ');
})
```

sees the cuepoint fired multiple times.

See also: http://flash.flowplayer.org/forum/5/104264

Are cuepoints meant to work with bitrateselect (or bwcheck for that matter)?

Will try an rtmp setup now.

**Comment by phloxic** [comment]
Same for rtmp.

Does not seem to happen when cuepoints are not added dynamically, but right away in the clip configuration.

**Comment by danrossi** [comment]
Just looking at your example, you are adding cuepoints in the onMetadata event, this is still being dispatched after each switch and transition to a new bitrate as it's returned from rtmp. Perhaps thats what your issue is.

**Comment by danrossi** [comment]
I think thats what your issue is.

**Comment by danrossi** [comment]
[INFO] time 22:09:36.883 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:36.885 :: org.flowplayer.controller::PlayTimeTracker : firing cuepoint with time 20000
cuepoint fired.  brselect.html:69
[INFO] time 22:09:36.923 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:36.925 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:36.950 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:36.951 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:36.989 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:36.990 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.16 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.17 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.36 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.38 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.75 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.77 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.99 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.101 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.139 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.140 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.166 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.167 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.187 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.188 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.225 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.227 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.250 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.251 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.301 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.302 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.339 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.340 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.366 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.367 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.405 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.406 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.426 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.427 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired
[INFO] time 22:09:37.450 :: org.flowplayer.controller::PlayTimeTracker : cuePointReached: [Cuepoint] time 20000
[LOG] time 22:09:37.451 :: org.flowplayer.controller::PlayTimeTracker : this cuepoint already fired

Only sent once with your code.

**Comment by danrossi** [comment]
Let me know when you have a moment to look at it again.

**Comment by phloxic** [comment]
Yes, that is the problem - as I stated above: https://github.com/flowplayer/flash/issues/50#issuecomment-10119171
However, dynamically adding cuepoints in events is officially documented: http://flash.flowplayer.org/documentation/events/cuepoints.html#scripting-cuepoints
And my example, or rather the one in the forum, gives a good and simple use case: you want a cuepoint at 1/10 of the movie, and another at half of the movie duration. The earliest point to grab the clip's duration is onMetaData, therefore the need to set the cuepoints dynamically.
So the bug title should be "brselect: _Dynamic_ cuepoints fired multiple times" - but it's still a bug. Unless we say dynamic addition of cuepoints is forbidden with the bitrateselect plugin (and possibly the bwcheck plugins) - then it is a documentation bug.
So, what is it?

**Comment by danrossi** [comment]
I'll look at adding a dispatched flag for metadata and hopefully it doesn't get triggered, I think I know where to do it ..

**Comment by danrossi** [comment]
it needs a bit of work, because its being dispatched within the net client because its a stream callback and dispatches the event directly to the clip. as is im still unable to replicate any problems and the multiple metadata dispatching can be worked around with a flag in the js for now.

**Comment by phloxic** [comment]
Don't you see it here: http://flowplayer.blacktrash.org/test/brselect.pseudo.html ?
The most simple version of the originally posted config: 1 cuepoint at 8 secs inserted dynamically at onMetaData.
Switch resolution or do a simple seek. Afterwards the cueupoint handler is triggered several times.
Which js flag do you have in mind?

imho the only user workaround would be to use onStart - but that might not be possible/desired in some cases.

**Comment by danrossi** [comment]
Both rtmp and pseudo will dispatch metadata while switching, rtmp does it by default anyway, pseudo is doing it because it reloads a new file therefore flash will trigger the event. The only way is to flag not to dispatch it until a different clip is loaded or the stream has finished. Its going to need a few work arounds due to the fact is happening outside of the stream provider. I'll try to come up with something ;)

**Comment by danrossi** [comment]
Actually here is one, there is already a check if the clip is configured with the metadata to update a duration, so a different event could be dispatched here like onMetadataUpdated, the metadata might have to be cleared though when being replayed in a playlist or else it won't trigger onMetadata again. I'll try this first.

**Comment by phloxic** [comment]
I understand how difficult this is. If it rises the danger of breaking things, users have to make do with onStart. It just has to be clear and documented (I'll do the latter). Let me know how you fare.

**Comment by danrossi** [comment]
Hey hey, im going the hacky route i think rather than yet another event. On rtmp, it will dispatch metdata after each seek and after each switch transition, so a flag to disable dispatching metadata during these phases might work best assuming the completion events are returned ! , lets see. 

update: it wont work on the seeking because seek notify happens before play /  metadata events back to the old way.

**Comment by danrossi** [comment]
ok here is the killer question, we'd want to have to call onMetadata after replay or when replaying in a playlist right ? It will now dispatch onMetadataChange because the clip metadata is already set. 

let me build this for you to test if poss ;)

**Comment by danrossi** [comment]
https://dl.dropbox.com/u/3394987/flowplayer-3.2.15.zip

**Comment by phloxic** [comment]
https://dl.dropbox.com/u/3394987/flowplayer-3.2.15.zip looks good! Does the job.

**Comment by danrossi** [comment]
Thnx. OK well there is issues now with replays, and playing the clip the second time in the playlist, it will dispatch onMetadataUpdate instead because its already set. Thoughts ?

**Comment by phloxic** [comment]
Very good you're checking these - I just don't have the time atm. - My stance: Not worth changing if it affects basic functionality and/or unleashes a pile of further fixes.
In almost any case users should be able to deal with the matter at hand in onStart (where this is not happening).
So: only if a clean fix is possible.

**Comment by danrossi** [comment]
Hi for this there is no such thing as a clean fix, however I can clear the metadata to calls to reload the clip / replays. That might work ...

**Comment by danrossi** [comment]
I believe the setup for replay is to not dispatch metadata or onstart. So its just when reloading the clip in a playlist.

**Comment by danrossi** [comment]
confirming that works fine.

**Comment by danrossi** [comment]
https://dl.dropbox.com/u/3394987/flowplayer-3.2.15.zip , when you have a moment. when replaying the clip in a playlist onMetadata is called.

**Comment by danrossi** [comment]
I'll commit these for now .

**Comment by danrossi** [comment]
closing for now.
