### ISSUE TITLE
slowmotion + wowza + mp4: supported?

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#51]
try this config:

``` js
plugins: {
  slomo: {
    url: 'flowplayer.slowmotion-3.2.9.swf',
    serverType: 'wowza'
  },
  rtmp: {
    url: 'flowplayer.rtmp-3.2.11.swf',
    netConnectionUrl: 'rtmp://rtmp01.hddn.com/play'
  },
  controls: {
    tooltips: {buttons: true}
  }
},
clip: {
  url: 'mp4:vod/demo.flowplayervod/buffalo_soldiers.mp4',
  provider: 'rtmp'
}
```

No luck with forward at all, backwards only for one instance.

See also: http://flash.flowplayer.org/forum/5/104283

**Comment by danrossi** [comment]
No problems in hddn unless something has popped up can you put that online at all ?

**Comment by phloxic** [comment]
Update issue title regarding mp4. Our demo at http://flash.flowplayer.org/demos/plugins/streaming/slowmotion.html is with a flv file. With mp4 no luck.

**Comment by danrossi** [comment]
After some research aparantly h264 does not work with fastplay on wowza.

**Comment by phloxic** [comment]
Aha. I'll update the docs saying that this feature works only with flv files on wowza.

**Comment by phloxic** [comment]
Documentation issue, closing here.

**Comment by danrossi** [comment]
Yeah sorry about that I thought they were h264 clips in the test files setup but they were flv, and the wowza stepping was never an issue for me but obviously for h264 it is ;) I had to google that there is zero documentation about it.

**Comment by danrossi** [comment]
They may provide support for it but found a very recent post saying they do not.
