### ISSUE TITLE
URL name parts containing semi-colons (;) should pass validation through linkUrl usage

### ISSUE THREAD

**Issue by Alpheus** [flowplayer/flash#53]
To my knowledge semi-colons are a valid character within a URL (atleast for the path) and the current regex in https://github.com/flowplayer/flash/blob/a774e53311824054ece3bf79879be28bfaf317b3/core/src/actionscript/org/flowplayer/util/URLUtil.as does not seem to allow it.

Would be great if this could be fixed. Link structure in question:

http://ad.sample.net/click;foo;bar;v

See http://stackoverflow.com/questions/1178024/can-a-url-contain-a-semi-colon

**Comment by danrossi** [comment]
Do you have an example of this being used if possible.

**Comment by Alpheus** [comment]
Nothing in production for now as far as the url is concerned, we're temporarily using a local redirect to handle it but it's less than optimal. Ideally, the sample link above would have to pass validation.

**Comment by danrossi** [comment]
I mean a config you are using.

**Comment by Alpheus** [comment]
As far as that clip is concerned:

``` javascript
{
    clip: {
        linkUrl: 'http://ad.sample.net/click;foo;bar;v',
        linkWindow: '_blank'
    }
}
```

**Comment by danrossi** [comment]
Ok I thought so, thanks very much. I'll see how easy it is to add that to the regexp filter. I think we need to keep the filter in case of xss links or something like that, the issue is the regexp is not seeing the path correctly because of the ;.

**Comment by Alpheus** [comment]
I believe the expression below would solve the issue but you'd have to run it against your tests to check if it breaks any of the previously fixed XSS issues.

```
/^http(s)?:\/\/((\d+\.\d+\.\d+\.\d+)|(([\w-]+\.)+([a-z,A-Z][\w-]*)))(:[1-9][0-9]*)?(\/(?:%+@&=)|([\w-.\/:;%+@&=]+[\w-.\/?:;%+@&=]*)?)?(#(.*))?$/;
```

**Comment by danrossi** [comment]
Thankyou i will let you know the regex gets pretty chaotic indeed.

**Comment by danrossi** [comment]
hi confirming that regex works i can see you added the semi colon no worries.

**Comment by danrossi** [comment]
fix in https://dl.dropbox.com/u/3394987/flowplayer.commercial-3.2.15.zip

**Comment by danrossi** [comment]
Hi we'll leave it open to keep it flagged as testing, but thanks for the report ;)

**Comment by Alpheus** [comment]
Oh, alright - sorry about that, wasn't acquainted with your workflow :) But thanks nonetheless, this has been very productive.

**Comment by danrossi** [comment]
fixed. closing for now.
