### ISSUE TITLE
Subscribe settings when using RTMP and Cluster plugins together

### ISSUE THREAD

**Issue by featheast** [flowplayer/flash#57]
Hi, 

If I use RTMP plugin only, the subscribe setting is working as expected when talking to EdgeCast.

However, when I tried to use both RTMP and Cluster plugin at the same time, it appears the subscribe setting is no longer working. There is no subscribe attribute in Cluster, so that I guess the logic will simply ignore the subscribe setting in the RTMP plugin.

Is there any workaround to do that, or is it possible to expose the subscribe setting in Cluster plugin?

Also, I've noticed that in file flash/plugins/rtmp/src/actionscript/org/flowplayer/rtmp/ SubscribingRTMPConnectionProvider.as, line 58 and line 91, both log.error I think are unnecessary, which will show console errors in browsers.

**Comment by danrossi** [comment]
Hi there they can't be used together. The cluster plugin might need to be modified to add the subscribe call for now.

**Comment by danrossi** [comment]
closing this for now.
