### ISSUE TITLE
player can't handle utf-8 media file locations

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#59]
http://flowplayer.blacktrash.org/test/utf.html

JWPlayer avoids the problem (in its latest version) by not writing any media location into the object on the plage.

**Comment by phloxic** [comment]
fp5 has the same problem: https://github.com/flowplayer/flowplayer/issues/162

**Comment by danrossi** [comment]
I thought we fixed this one ages ago, it was confirmed a bug in IE8. 

what do you mean by

by not writing any media location into the object on the plage.

**Comment by danrossi** [comment]
Its defaulting to html5 on jwplayer :&

**Comment by danrossi** [comment]
Don't ask me why but this works

```
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
```

**Comment by phloxic** [comment]
JWPlayer works in Flash, I tested in Firefox which certainly does not play mp4; updated demo to enforce Flash engine. Anyway I checked the generated html:

``` html
<div id="jw_wrapper" style="position: relative; width: 624px; height: 260px;">
<object id="jw" width="100%" height="100%" type="application/x-shockwave-flash" data="http://flowplayer.blacktrash.org/jwplayer.flash.swf" bgcolor="#000000" name="jw" tabindex="0">
<param name="allowfullscreen" value="true">
<param name="allowscriptaccess" value="always">
<param name="seamlesstabbing" value="true">
<param name="wmode" value="opaque">
</object>
<div id="jw_jwpsrv" style="position: absolute; top: 0px; z-index: 10;"></div>
</div>
```

no html5 whatsoever.

Enforcing a non-utf charset can hardly be the solution ;-)

**Comment by danrossi** [comment]
shit ey you are right, this one has been bugging me for a while and thought it was working. I'll try and see what they are doing.

**Comment by danrossi** [comment]
i finally got jw6 checked out, it does indeed play back, if i dont even set utf-8 encoding  as the charset the file plays back fine and requests exactly like my example, its only when setting utf-8 as the charset it causes the problems and requires encodeURI. 

My guess the json parsing isn't liking encodeURI for some reason or another because of the percentages. 

I reckon the quickest fix of the lot is to not use utf-8 as the charset.

**Comment by danrossi** [comment]
ie

```
<meta http-equiv="content-type" content="text/html; charset=utf-8">
```

without the encodeURI will also fail in jwplayer

**Comment by danrossi** [comment]
baseUrl: "http://media.blacktrash.org/fp/test/",
url: encodeURIComponent(encodeURIComponent("Древние-624x260.mp4"))

This works

**Comment by phloxic** [comment]
encodeURI makes sense because http://media.blacktrash.org/fp/test/Древние-624x260.mp4 is not a valid url, strictly speaking.
http://media.blacktrash.org/fp/test/%D0%94%D1%80%D0%B5%D0%B2%D0%BD%D0%B8%D0%B5-624x260.mp4 is valid and works in JWPlayer.

The baseUrl trick does definitely NOT work for me. Please test again.
I still get:

```
"NetworkError: 403 Forbidden - http://media.blacktrash.org/fp/test/???????-624x260.mp4"
```

and the question marks are also written to the generated object.

Even if it worked, the baseUrl trick would not help with:

```
<a id="playerContainer"
href="http://media.blacktrash.org/fp/test/%D0%94%D1%80%D0%B5%D0%B2%D0%BD%D0%B8%D0%B5-624x260.mp4 ">
</a>
```

**Comment by danrossi** [comment]
its being decoded in the config parser

**Comment by danrossi** [comment]
flash is decoding the string from the flashvars config therefore the need for double encoding ?

**Comment by danrossi** [comment]
re-encoding the prenecoded url does work also but the property is somehow not being set anymore. basically the encoded url is sent ok in the flashvars but picked up decoded hence the issue.

**Comment by danrossi** [comment]
pretty mad !

**Comment by danrossi** [comment]
urlEncoding: true,
            url: "http://media.blacktrash.org/fp/test/%D0%94%D1%80%D0%B5%D0%B2%D0%BD%D0%B8%D0%B5-624x260.mp4",

this works

**Comment by danrossi** [comment]
so does this

urlEncoding: true,
url: encodeURI("http://media.blacktrash.org/fp/test/Древние-624x260.mp4")

**Comment by danrossi** [comment]
I finally get what you mean I have no idea how they are configuring the player its convoluted and had to track down. They are not configuring anything to the flashvars at all.

**Comment by phloxic** [comment]
Indeed it needs double encoding, this

``` js
 clip: {                                                                                                           
  urlEncoding: true,                                                                                              
  url: "http://media.blacktrash.org/fp/test/%D0%94%D1%80%D0%B5%D0%B2%D0%BD%D0%B8%D0%B5-624x260.mp4"
}
```

works too.

I guess _writing_ this into the flashvars causes the problem - and indeed

``` js
$f().play("http://media.blacktrash.org/fp/test/%D0%94%D1%80%D0%B5%D0%B2%D0%BD%D0%B8%D0%B5-624x260.mp4");
```

works without double escaping! - If you have set urlEncoding: true in the common clip then play(escaped) breaks. Similar to https://github.com/flowplayer/flash/issues/21.

**Comment by danrossi** [comment]
It is flash decoding it when loading the flashvars. When calling play it probably doesnt need to be double encoded.

**Comment by phloxic** [comment]
Yeah. Similar to #21.
I actually have an idea how to solve this. My patch here: https://github.com/flowplayer/flash/commit/bcd58baf00aaa0c4307923d073c18311d3757c02 can probably be simplified to use just `encodeURI` which even leaves rtmp urls like `mp4:clip` intact.
Contrary to your 3.2.8 canonshoot of escaping ALL config properties - `escape` - this will only address urls. Then we should be fine. Will test with the usual candidates.
Like for JWPlayer escaping UTF-8 is mandatory, as UTF-8 chars in an url are invalid. But the double encode should not be necessary.

**Comment by phloxic** [comment]
Bummer. Applying `encodeURI` for all URLs breaks with a properly escaped space (`%20`) in the filename (or href of the player container) or with a properly encode utf url for that matter.

**Comment by danrossi** [comment]
Double encode I reckon is the way to go, OR a completely refactor to not use flashvars at all is the only way to go I think. I think jwplayer is doing externalinterface calls to grab the config after it starts loading, no idea.

**Comment by danrossi** [comment]
Whats the decision here then ? Double encode ?

**Comment by phloxic** [comment]
Asking users to double encode is not what I'd call a solution.
I am for leaving this open for @anssip - as we also have to find out how to handle the licensing idn domain names.
This entire area is in the dark.

**Comment by danrossi** [comment]
hmmm, ill see if doing it twice in flash will fix the issue, seeing it gets unencoded when passed to flash.

**Comment by danrossi** [comment]
I'm going to attempt the double encode in flash to see if it helps.

**Comment by danrossi** [comment]
Sorry about the late response. It doesn't need double encoding, let flash do the encoding with urlEncoding: true. Doing an encodeURI on the js, gets decoded when sent to flash. It works fine with just

url: "http://media.blacktrash.org/fp/test/Древние-624x260.mp4",
                        urlEncoding: true,

**Comment by phloxic** [comment]
Indeed, we somehow overlooked that alternative - also we get exactly the same behaviour with the api:

``` js
$f().play({
  url: "http://media.blacktrash.org/fp/test/Древние-624x260.mp4",
  urlEncoding: true // required in api as well
});
```

See: http://flowplayer.blacktrash.org/test/unicode.html

Phew, let's close this - at least for fp Flash, and until we stumble over yet another oversight ;-)

**Comment by danrossi** [comment]
I added that feature in for exactly the same issue and it was russian characters too. But we've now figured out this causes issues because flash decoding it in the flashvars, i think pre-encoding also causes problems.
