### ISSUE TITLE
pseudostreaming + bwcheck + checkOnStart hangs on reference file download

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#6]
Minimal demo: http://flowplayer.blacktrash.org/test/bwcheck-pseudo-onstart.html

Player just hangs when/after it downloads reference file.

See also: http://flowplayer.org/forum/5/103182

**Comment by danrossi** [comment]
[LOG] time 02:16:03.695 :: org.flowplayer.bwcheck.detect::BandwidthDetectorHttp : requesting reference file http://flowplayer.blacktrash.org/flowplayer-3.2.14.swf
[LOG] time 02:16:03.696 :: org.flowplayer.bwcheck.detect::BandwidthDetectorHttp : reference file download started at time: 1440
[LOG] time 02:16:07.44 :: org.flowplayer.bwcheck.detect::BandwidthDetectorHttp : reference file successfully downloaded
[LOG] time 02:16:07.46 :: org.flowplayer.bwcheck.detect::BandwidthDetectorHttp : Current Time: 4789
[LOG] time 02:16:07.46 :: org.flowplayer.bwcheck.detect::BandwidthDetectorHttp : Download Time: 3.349
[LOG] time 02:16:07.47 :: org.flowplayer.bwcheck.detect::BandwidthDetectorHttp : KBytes: 987.5
[LOG] time 02:16:07.48 :: org.flowplayer.bwcheck.detect::BandwidthDetectorHttp : Bytes: 126400
[LOG] time 02:16:07.48 :: org.flowplayer.bwcheck.detect::BandwidthDetectorHttp : Bandwidth: 274.2236488504031

It loads fine for me what do you see

**Comment by phloxic** [comment]
Sorry about that. It seems there was a glitch with hddn, works fine now. Let me just get back to the user before closing, OK?

**Comment by danrossi** [comment]
It doesn't look like it was triggering a complete status on the download. It could be running into an IE loader bug if its ie. What browser / OS.

**Comment by phloxic** [comment]
The user's sample still does not work: http://zxc.pp.ua/fptest/index.html in all my browsers.

I told him to remove some brselect cruft from the config.

**Comment by SkeLLLa** [comment]
I removed those "brselect cruft" from config. Without checkOnStart video works, but bwcheck is never called. If I try to use JS api ($f().getPlugin("bwcheck").checkBandwidth() it also hangs bwcheck process hangs. Also tried to add qos adn dynamic:true params in bwcheck - nothing helped.

Updated demo here without checkOnStart an brselect "dinosaurs" http://zxc.pp.ua/fptest/index.html (don't forget to clear cache).

Browser: Chrome (stable/dev) Windows, Chromium (dev) Linux.

**Comment by danrossi** [comment]
Hi many thanks, does it sit at " requesting reference file" , what does the resource monitor say downloading the file do you have a screenshot ?

**Comment by SkeLLLa** [comment]
Yes. It sits at "requesting reference file". Network monitor shows that it only downloads crossdomain.xml and nothing else. In Cristian's example it correctly downloads file from netConnectionUrl

**Comment by danrossi** [comment]
Thanks heaps , ill see what I can do, at least set a timeout and dispatch normally and then it will use the default bitrate instead.

**Comment by danrossi** [comment]
The config on that page is missing checkOnStart therefore its using the lowest bitrate as default. This is required.

**Comment by phloxic** [comment]
It was present yesterday - @SkeLLLa, please leave the sample as it was, so we can reproduce the problem.

**Comment by danrossi** [comment]
OK it's an issue with the policy file, or the loader, i'll try and get the security sandbox working for chrome on windows, no idea whats going on there.

**Comment by danrossi** [comment]
Not sure if it makes a difference but here is mine http://static.electroteque.org/crossdomain.xml

**Comment by danrossi** [comment]
it's a cache control header on the request , chrome doesn't like this on windows.

**Comment by danrossi** [comment]
https://dl.dropbox.com/u/3394987/flowplayer.bwcheck-3.2.10.zip

**Comment by SkeLLLa** [comment]
Thanks, danrossi. Your file fixed this. But this bug earlier reproduced not only in chrome on windows: also I've tested firefox & chromium on linux. Now it working well in Chrome/Chromium (Win, Linux) and FF. I've updated example (now it works) if you need it for testing.

**Comment by danrossi** [comment]
Not a problem thanks for the update.

**Comment by danrossi** [comment]
Change has been committed and should be released shortly.
