### ISSUE TITLE
viralvideos: buttons disappear with dock: {autoHide: false}

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#60]
The dock buttons are hidden when one of the dialogues are called. They don't reappear when the dialogue is closed.

**Comment by danrossi** [comment]
cannot replicate im afraid they appear fine.

**Comment by phloxic** [comment]
Not after you closed a dialogue without doing anything. They do not REappear.
And, sorry, it concerns the viralvideos plugin only, the sharing plugin has no dialogue.

**Comment by danrossi** [comment]
Yes I know I tested it opened a dialog window then closed and the dock appears again.

**Comment by danrossi** [comment]
Do you have a demo ?

**Comment by phloxic** [comment]
http://flowplayer.blacktrash.org/test/viral-dock.html

**Comment by danrossi** [comment]
sorry about that mate, im juggling too many things, just post some code no need for demos as thats time consuming. I see it now ;)

**Comment by phloxic** [comment]
heh ... I thought the code was in the bug title

``` js
plugins: {
  viral: {
     url: "flowplayer.viralvideos-3.2.13.swf"
  },
  dock: {
    autoHide: false
  }
}
```

Will remove demo now ;-)

**Comment by danrossi** [comment]
Yes I dont see that im cross eyed and over worked most dayz just like yourself .... ;)

**Comment by danrossi** [comment]
i'll add a couple of helper methods here, its trying to stop / start autohide when its disabled.

**Comment by danrossi** [comment]
https://dl.dropbox.com/u/3394987/flowplayer.viralvideos-3.2.13.zip

Try this Ive added two helper methods too, .show(); .hide()

**Comment by danrossi** [comment]
fixed. closing for now.

**Comment by phloxic** [comment]
No, you fixed something else (probably): that hide and show (and animate for that matter) are documented to be available for all plugins.
But to quote the original report: "The dock buttons are hidden when one of the dialogues are called. They don't reappear when the dialogue is closed." with autoHide DISabled (see bug title).
Demo: http://flowplayer.blacktrash.org/test/viral-dock.html - click one of the icons, and then close the dialogue. The dock disappears forever.

**Comment by danrossi** [comment]
not happening in dev I suppose they aren't release yet, I haven't heard back if it was working for you but I just checked and its all good. 

You prob need the controls also because it was a change with autohide

https://dl.dropbox.com/u/3394987/flowplayer.controls-3.2.14.zip
https://dl.dropbox.com/u/3394987/flowplayer.viralvideos-3.2.13.zip

**Comment by danrossi** [comment]
I suspect these are all waiting to be tested before release right ? i'll come back to this once I complete the other issues.  half the issues posted have already been fixed or working in dev from a fix, no idea :)

**Comment by danrossi** [comment]
Leaving this open until release.

**Comment by anssip** [comment]
Does not happen with the current dev version. Just verified.

**Comment by phloxic** [comment]
Confirmed :+1: - can also be tested here: http://flowplayer.blacktrash.org/test/viral-dock.html
