### ISSUE TITLE
content: align="center" has no effect as img attribute

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#62]
The align attribute does not work as advertised for images in the html content. According to http://flash.flowplayer.org/plugins/flash/content.html#image-tag-img this should center the image:

``` js
plugins: {
  content: {
    url: 'flowplayer.content-3.2.8.swf',
    html: '<img src="http://flash.flowplayer.org/media/img/logo/logo_100x100.png" align="center" />',
    height: 150
  }
}
```

But the image stays left aligned. `align="right"` works, and `align="center"` works for p tags, but not for img.

**Comment by phloxic** [comment]
See: http://flash.flowplayer.org/forum/5/104528

**Comment by danrossi** [comment]
there is only left and right I believe. there is not much information about it.

**Comment by phloxic** [comment]
True, inasmuch align _values_ are only listed for P tags right below.
If we do not support center for IMG tags, then it's a doc bug, and we/I should list the 2 valid values for img align similar to the 3 valid ones for P.
doc bug or "real" bug?

**Comment by danrossi** [comment]
Nothing to do with the player but flash. I'll keep trying to look I suppose.

**Comment by danrossi** [comment]
Just a long shot, what about wrapping in p or span tags ?

**Comment by phloxic** [comment]
Nah, tried:

``` js
html: '<p align="center"><img src="/path/to/img.png" /></p>'
```

to no avail.

**Comment by phloxic** [comment]
Neither does have `<p textAlign="center">` have any effect, also not with text content. It seems it does not do anything.
Wrapping the image in span also does not help.
`<p align="center">` _loses_ its effect on text when an image is included.
I assume this is all somewhat related to the automatic reflowing of text around images.

**Comment by danrossi** [comment]
Try this example http://www.java2s.com/Code/Flash-Flex-ActionScript/TextField/UseimgtaginTextField.htm

**Comment by phloxic** [comment]
What are you trying to tell me? Adding `hspace="0" vspace="0"` also does not help, if that's what you mean.

**Comment by danrossi** [comment]
Ok well then it doesn't work then.

**Comment by phloxic** [comment]
So: document that for images only "left" and "right" are available?

**Comment by phloxic** [comment]
On the other hand I have so far found no workaround to center an image.

**Comment by sompylasar** [comment]
How about CSS and the 'style' attribute instead of the deprecated 'align', 'valign', 'vspace' etc.?

**Comment by phloxic** [comment]
So far I've tried to no avail. And the rudimentary content plugin html is not like html on the page. Normally you have better chances that the old-fashioned stuff works - "right" does, but not "center".

**Comment by danrossi** [comment]
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/TextField.html#htmlText here is the docs

align: Specifies the horizontal alignment of the embedded image within the text field. Valid values are left and right. The default value is left.

"Text automatically flows around images you embed in text fields. You must set the text field to be multiline to wrap text around an image."

**Comment by phloxic** [comment]
Thanks for the pointer. I gather there's no way to center an image then. Taking over and will update docs accordingly.

**Comment by phloxic** [comment]
Closing in favour of doc improvement in site repo.
