### ISSUE TITLE
PseudoStreaming - Secured urls don't seek

### ISSUE THREAD

**Issue by ohanyan** [flowplayer/flash#66]
The queryString parameter is appended as the first parameter in the url.  This breaks when the first X characters of the url are signed for security.

ie
 url to mp4:   http://content.site.com/pathto.mp4?t=timestamp&ip=10.12.12.12&sign=2f2j3rwk2h3rkjjefkjwef

Here the signature signs the first portion of the url (http://content.site.com/pathto.mp4?t=timestamp&ip=10.12.12.12) - or the first predefined number of characters.  This prevents the stream from being stolen, since the signature expires based on the timestamp and is limited to an ip).
However, the pseudostreaming provider adds the querystring parameter to the url, the signature becomes invalid:

ie 
 url to mp4:   http://content.site.com/pathto.mp4?start=1234.5&t=timestamp&ip=10.12.12.12&sign=2f2j3rwk2h3rkjjefkjwef

However, it would work if the queryString was appended to the end of the url,

http://content.site.com/pathto.mp4?t=timestamp&ip=10.12.12.12&sign=2f2j3rwk2h3rkjjefkjwef&start=1234.5

since the signature only applies the first part of the url, and anything that follows can change.

**Comment by danrossi** [comment]
hi this has been fixed in development but possibly not released ill have a look.

**Comment by ohanyan** [comment]
thanks.  I did modify the plugin locally to append the string at the end it does work.  Looking forward to an update if it's available.

**Comment by ohanyan** [comment]
Is there a way to contribute to flowplayer or submit pull requests

**Comment by danrossi** [comment]
https://github.com/flowplayer/flash/blob/danielr-httpstreaming/plugins/pseudostreaming its in here.

**Comment by danrossi** [comment]
Closing this for now if possible.
