### ISSUE TITLE
3.2.16-dev, Flash 10.3, FLV: tiny "preview" while loading

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#69]
![fp3loading](https://f.cloud.github.com/assets/168338/134748/0b9d5a04-70f4-11e2-86b7-32ece978fa1f.jpg)

Might be caused by https://github.com/flowplayer/flash/commit/117de6ebe314208bcda39b1619fcb238cafe1f80#core/src/actionscript/org/flowplayer/view/Screen.as

But:
- does not happen with mp4
- does not happen in strobe player: http://www.speaker.org/video/smp/setup.html

We claim to be compatible with Flash 10.1

**Comment by danrossi** [comment]
Uhh I think the release might need to be hold off. Possibly something to do with the display fixes.

**Comment by anssip** [comment]
I have fixed this one today. Should not happen here any more:
http://flash.flowplayer.org--dev.s3-website-us-east-1.amazonaws.com/documentation/version-history.html

Remember to clean your browser cache :-)

Anssi

On Thu, Feb 7, 2013 at 5:06 PM, danrossi notifications@github.com wrote:

> Uhh I think the release might need to be hold off. Possibly something to
> do with the display fixes.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flowplayer/flash/issues/69#issuecomment-13239679.

## 

http://about.me/anssi.piirainen

**Comment by phloxic** [comment]
I always scrub my cache with a tooth brush. Confirming that this is fixed and closing.

**Comment by danrossi** [comment]
top job thnx.
