### ISSUE TITLE
HDS not working, bwcheck httpstreaming not functional

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#70]
See: http://code.google.com/p/flowplayer-core/issues/detail?id=507
and: http://flash.flowplayer.org/forum/8/98541

Requires OSMF2 integration.

**Comment by danrossi** [comment]
Thanks will look into this

**Comment by danrossi** [comment]
started this not as simple as I thought as they are using different api methods for http streaming.

**Comment by danrossi** [comment]
this is going to mess up quite a few of the functions that need changing because of differences in the api.

**Comment by danrossi** [comment]
getting back to this, more of the osmf classes needed modifying now because of the different api's but looking into the possibility of not having to set the indexes when manually switching and using its manual switch method instead, but test as is for now.

**Comment by danrossi** [comment]
https://dl.dropbox.com/u/3394987/flowplayer.bwcheck-3.2.12.zip
https://dl.dropbox.com/u/3394987/flowplayer.bwcheck-httpstreaming-3.2.12.zip
https://dl.dropbox.com/u/3394987/flowplayer.httpstreaming-3.2.10.zip
https://dl.dropbox.com/u/3394987/flowplayer.f4m-3.2.10.zip

The whole set of plugins dependant on osmf needs updating, have begun changing version numbers. These are ready for testing but I'd like to try to reduce their compile sizes are little bit as OSMF tends to be bloaty hence why the functions are loaded directly. And tend more using dynamic switching with bitrareselect to see if I still need to specifically set the index so the name reporting functions correctly. 

From my quick tests it switches and retains a high level bitrate fine and doesn't resort back to the lowest bitrate. Same for rtmp.

**Comment by danrossi** [comment]
how did it go ?

**Comment by danrossi** [comment]
have yet to test alongside bitrateselect thats the crazy part will also test against the hls plugin as it should function the same and auto switch.

**Comment by danrossi** [comment]
Need to implement some "playback" optimisation code that strobe media playback is doing. And for some reason now does not work with live streams.

**Comment by danrossi** [comment]
all good now.

**Comment by jsardas** [comment]
Thanks a lot danrossi for looking into this issue !!! It will be a very important improvement to Flowplayer.

Are the Dropbox links actually updated with the latest code you applied today? Or is there a way to download the latest updated (compiled) plugins?

**Comment by danrossi** [comment]
closing this for now.
