### ISSUE TITLE
menu toggle: selecting checked item deselects it without having an effect

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#71]
Can be reproduced in our own demo: http://flash.flowplayer.org/demos/plugins/streaming/brmenu.html
The UI should reflect the behaviour: Selecting an already selected item is a no-op.

**Comment by danrossi** [comment]
they dont act like toggle buttons as such so it has to be replicated. I had to do some modifications for someone recently so it would disable the item, and display a toggled colour instead of those ticks. Perhaps its simple to disable the selected item so it can't be selected again.

**Comment by phloxic** [comment]
The tick is fine. But selecting a ticked/already selected item should not cause the tick to go away.

**Comment by danrossi** [comment]
Yes the entire thing needs to be changed to a toggle button instead so it disables that item like I've had to do with some modifications.

**Comment by danrossi** [comment]
Just had a look, if we set the items to be a toggle function the tick marks will be removed. Thats how its been programmed to toggle on and off. Its not going to switch because its the same bitrate.

**Comment by danrossi** [comment]
I'm assuming the toggle like that is there for a reason so we turn off toggling and the tick marks.

**Comment by danrossi** [comment]
http://flash.flowplayer.org/plugins/flash/menu.html

"Is this a toggle item? Toggle items can be selected and de-selected. In the selected state (pressed down) a check mark is displayed next to the label text."

**Comment by danrossi** [comment]
Ive had to do this with a customisation also. If we remove the tick mark toggle feature, there is just the bare elements with no selection notification. So in this circumstance we might need to use a selection background colour instead ?

**Comment by danrossi** [comment]
So when items are selected / deselected, if there is no toggle feature and tickmark, change the background colour instead. What do you think ?

**Comment by danrossi** [comment]
I was close getting this going but because its not a toggle button the colour resets on mouse out. Please confirm if this will resolve the issue.

**Comment by phloxic** [comment]
Can't you check whether the item is already selected and make it a no-op?

**Comment by phloxic** [comment]
For that, as well as for the completely lacking brselect api docs (which I'm currently working on) it would be good to know whether getBitrate() is supported - you seem to use setBitrate() in your JS brselect plugin.

**Comment by danrossi** [comment]
http://flash.flowplayer.org/plugins/flash/menu.html

"Is this a toggle item? Toggle items can be selected and de-selected. In the selected state (pressed down) a check mark is displayed next to the label text." 

Did you see this ? The menu is doing what its supposed to do, toggle the check mark. I'm proposing a different solution for the menu when "toggle" is not enabled so it can still display what is selected. I don't understand how this is related to the bitrateselect plugin. What is the issue with getBitrate ?

**Comment by danrossi** [comment]
Are you able to setup a different feature request for that if possible. There is a get method on bwcheck but not bitrateselect.

**Comment by danrossi** [comment]
working on a solution which im doing for a similar customisation. it will disable the item when selected if the "toggle" feature is not enabled. this will also show up as a different colour.

**Comment by phloxic** [comment]
I don't understand what you're doing or intend to do, sorry.
From the user perspective it's very simple: when I (accidentally) click on a checked item, nothing should happen.

There is no issue with getBitrate, I wasn't asking for a new feature, I want to document the existing features. But, yes, I will open a "feature" request for info about it.

**Comment by danrossi** [comment]
http://dev.electroteque.org/flowplayer/example/menu.html have a look here I manage to get a solution together and muck around with putting online. Try these if poss. 

https://dl.dropbox.com/u/3394987/flowplayer.bitrateselect-3.2.13.zip
https://dl.dropbox.com/u/3394987/flowplayer.menu-3.2.11.zip

So if we disable this toggle feature on the menu, it will disable the items when selected and highlight the backgrounds instead. Not keen to completely undo this tick mark toggling feature which is already documented. There is now an issue though with the "label" item at the top its enabled and clickable also, needs to be turned into a label item instead.

**Comment by phloxic** [comment]
Why disable the toggle feature? When I select a bitrate _successfully_, I want the display to toggle somehow.
Why is a color needed when we already have tick mark? Isn't that the same problem, just with color?
Should work similar to here: http://example.flowplayer.org/scripting/qsel.html - the selected button is disabled upon selection, and reenabled when something else is selected. In theory it just means that you:
1. disable the menu item on selection when it gets the tick mark.
2. cycle through the remaining items and enable the one who was disabled before the current selection - or grab the moment before selection to reenable the one with a tick mark.

**Comment by danrossi** [comment]
Do you see what I mean, disabling the item then it cant toggle therefore undoing the point of that documented feature :) 

I think this other alternative is better and doing exactly whats in your link above not sure what the problem is. it disables the item and does not give the option to toggle or click it again. In terms of the bitrate menu its doing exactly what you just said.

**Comment by danrossi** [comment]
I'll revert it back then ?

**Comment by phloxic** [comment]
I don't see what you mean, but if you say it does what I described then it's ok.

**Comment by danrossi** [comment]
http://dev.electroteque.org/flowplayer/example/menu.html did you have a look ?

https://dl.dropbox.com/u/3394987/Screen%20Shot%202013-03-01%20at%2012.55.09%20AM.png

I cant think of any other way and anything I do will break the feature, if the items get disabled then that menacing feature can't toggle. I think this is a better way in terms for bitrate item selection, use a disabled colour to display the selection notification just like its doing in your example.

**Comment by danrossi** [comment]
I think its needed anyway a playlist menu config like

items: [
                    { label: '<b>first clip</b><br/><i>3:30</i>', index: 0 },
                    { label: 'second clip', index: 1 },
                    { label: '<b>third clip</b><br/><i>3:66</i>', index: 2 },
                    { label: 'fourth clip', index: 3 },
                    { label: '<b>fifth clip</b><br/><i>13:30</i>', index: 4 },
                    { label: 'sixth clip', index: 5 }
                ],

When you select the item, there is no selection notification, the item is not disabled / still clickable. Fortunately / Unfortunately the change above will make it do the same thing here, disable the item, and show a different background colour. 

There is still a few blockers that will break the tick feature still  due to some selection flags when clicking im trying to fix.

**Comment by danrossi** [comment]
having more troubles now, the top item which is the "title" needs to be also disabled so defeats the purpose so it needs to change. It sounds easy but there is too many possible ways to break this obviously therefore needs time.

**Comment by danrossi** [comment]
I mean when adding the items, there is always going to be one that is default selected and the other items are not selected. When its chosen to be selected it will invert the enabled state therefore that title item is being enabled, just fixed that.

**Comment by danrossi** [comment]
http://dev.electroteque.org/flowplayer/example/menu.html
http://dev.electroteque.org/flowplayer/example/menu-playlist.html

Need as many different menu demos as possible to test so I know it doesn't break anything. Still quite possible ive broken that tick toggle feature, will test.

**Comment by danrossi** [comment]
the changes have been unchecked and lost now because i have to redo the rep and it was never committed. what did you want to do about it, disable the toggle config for the bitrate menu ?

**Comment by phloxic** [comment]
What I want is: the current behaviour - except that clicking on an already selected item becomes a no-op.

I don't see any toggle configuration in the example at http://flash.flowplayer.org/demos/plugins/streaming/brmenu.html and per http://flash.flowplayer.org/plugins/flash/menu.html#itemprops the default for `toggle` is false, so I do not understand why you continue to talk about toggle?

**Comment by danrossi** [comment]
That is correct again it's part of the menu feature "Is this a toggle item? Toggle items can be selected and de-selected. In the selected state (pressed down) a check mark is displayed next to the label text." turns the tick icon on and off each time its pressed. Disabling the toggle config will not display the tick icon at all.  The bitratemenu is configured with them as enabled. That is all I can explain for now, or go with the other solution changing the background colours instead to display selection as a disabled item.

**Comment by phloxic** [comment]
Your argument makes only sense if the UI would have no relation to the function it should execute.
In this case you cannot de-select _all_ streams. Therefore a click on an already selected stream has no effect, and that must be reflected in the UI. As it stands, clicking on a selected stream does indeed nothing, but tells the user: no stream is selected. Which is wrong, because the same stream is still running.
That's the behaviour I get in any checkmark menu on my machine: If I cannot deselect _everything_ functionality-wise the tick stays when I select an item which is already selected - in these cases the selection is often greyed out (with the tick present) to show that selecting the item will have no effect. But selecting it does not remove the tick mark (because that would not make sense).

**Comment by sompylasar** [comment]
BTW, the behavior @blacktrash [described above](https://github.com/flowplayer/flash/issues/71#issuecomment-20411590) is commonly named a radio button group. This is different from the checkbox group where an item may be deselected.

**Comment by phloxic** [comment]
@sompylasar - are you sure? As this is the menu plugin: In my browser if I (re-)select the current window in the window menu, i.e. selected the menu item with the tick mark, the tick mark does not go away. I would not call the menu items in my browser's window menu radio buttons, would you?

**Comment by sompylasar** [comment]
I would call that behavior the radio button group behavior regardless of
what the visuals are (the single tick or circles with a bullet for the
current selection).

**Comment by phloxic** [comment]
OK, radio button behaviour it is then ;-) Whatever the name, this behaviour is the one which makes sense for bitrate selection via menu.

**Comment by lordrak007** [comment]
Hi,
I have a little bit different problem.
When I used bwcheck together with bitrate select than flow is confused which quality is selected.
Example is here http://web-a.visual.cz/nacevi/players/1556485578_noe/ with debug for both plugins enabled.
On start flow detects bw and select highest quality. bw check has disabled dynamic streaming.
Than you can select quality 176p. Flow switch to 176p.
Now select Auto - its enable dynamic streaming for bwcheck. Occurs switch to 432p. Now please choose 176p. Its disable dynamic streaming for bwcheck and select 176p. (in console log you can see that flow thing that selected stream is 432p but not 176p)
Until this time all works fine but now when you choose 432p nothing happens because flow thinks that 432p is selected but you can see that stream name in debug log contain 176p and displayed video equals 176p.

That is bug i think.
Do you have any body idea how to repair it?
Thanks

**Comment by danrossi** [comment]
https://dl.dropboxusercontent.com/u/3394987/flowplayer.menu-3.2.12.zip 

Please try this, it will disable the currently selected item still which will prevent it being re-selected and therefore dispatching click callbacks, it will also prevent over states on the selected item like it probably should. When other items are selected it will re-enable the previously selected item. 

This is exactly what I did before which i ported over from some hacks in a project but it doesn't do the background colour changes. So hopefully im not wasting my time here again thanks. 

Regarding your dyn switching needs I have done hacks for this also in other projects so perhaps setup a different ticket for this if possible.

**Comment by phloxic** [comment]
https://dl.dropboxusercontent.com/u/3394987/flowplayer.menu-3.2.12.zip  behaves _exactly_ as it should imho. Nice work!

**Comment by danrossi** [comment]
Alright. I wonderful, I will add an option to set a disabled colour now if that is the planned way and hopefully no funky issues down the track. The normal menu configuration might need to be tested ...

**Comment by danrossi** [comment]
I believe this can be configured in the button config as normal. button: { disabledColor: "rgba()" }

**Comment by phloxic** [comment]
Yes. `menuItem.disabledColor` is used.

**Comment by lordrak007** [comment]
Hi,
thank you. It seems better but when I once select "Auto" than it is disabled forever.
Problem is when I select "auto" the last selected quality i still disabled.
You can see this here: http://web-a.visual.cz/nacevi/players/1556485578_noe/
Thank you

**Comment by phloxic** [comment]
@lordrak007 - you still have that trailing semicolon outside the quotes of your style directive of the container, and spurious commas in your config.

**Comment by lordrak007** [comment]
Hi, I hope that I removed all errors in my code.
Unfortunately it is no take an effect which problem that I have with menu.

**Comment by phloxic** [comment]
@lordrak007 - http://web-a.visual.cz/nacevi/players/1556485578_noe/ does not work at all for me(tm), the semicolon is also still there.

**Comment by lordrak007** [comment]
Hmm, I have some problem with srv.
Could you try this link? http://web02.visual.cz/nacevi/players/1556485578_noe/

**Comment by phloxic** [comment]
The problem is that you now try to circumvent the menu behaviour:
1) for manual _toggling_ the menu behaves correctly
2) but now you want a _boolean_ switch (which does not make sense for bitrates) in the _same_ menu.
imho that is a feature request, and not trivial to implement.

**Comment by danrossi** [comment]
Yes the "Auto" menu I have implemented as a modification before it's a feature request. That has to tell bwcheck to go back into autoswitching mode. It may need a bit of work there as the menu is generating via bitrateselect.

**Comment by phloxic** [comment]
Interest in "Auto" menu: http://flowplayer.org/forum/#!/plugins#flowplayer-flash-user-driv
Maybe this should go into a separate feature request, disentangled from this bug?

**Comment by danrossi** [comment]
http://flowplayer.electroteque.org/widevine i've done it as mods for the widevine plugin also.

**Comment by danrossi** [comment]
The auto menu feature might need a new ticket if it will happen is another story, changing to testing for release.

**Comment by anssip** [comment]
Selected menu items cannot be now reselected: http://flash.dev94.flowplayer.us/demos/plugins/streaming/brmenu.html

**Comment by phloxic** [comment]
Actually no, they can **not** be reselected, which is how it should be for bitrate selection: one should _not_ be able to _de_select but only be able to select a _different_ bitrate.
However, this works now with bitrateselect + menu, but it does not work in other circumstances:

``` js
items: [{
  index: 0, label: "initial selection", toggle: true, selected: true, enabled: false, group: "x" // first item selected and therefore disabled
}, {
  index: 1, label: "alternative selection", toggle: true, group: "x" // adding selected: false, enabled: true does not change anything
}]
```

Here "initial selection" will stay disabled and "alternative selection" will stay enabled for deselection. Inside a toggle group, `enabled` should be toggled as well, not only `selected`. Inside a toggle group `selected: true, enabled: false` and `selected: false, enabled: true` should be toggled. This is the point of a toggle group: You can only _de_select by selecting another item of the group.

**Comment by phloxic** [comment]
Ignore what I said in the last comment - it works exactly as expected, sorry for the noise. Probably some cache interfering while working on a complex setup.
Re-closing.
