### ISSUE TITLE
securedrm demo does not work

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#73]
http://flash.flowplayer.org/plugins/streaming/securedrm.html
gives "200, Stream not found" error

**Comment by danrossi** [comment]
The videos have been moved to cloudfront here http://videos.electroteque.org/BigBuckBunnyAuth.f4v

**Comment by danrossi** [comment]
As mentioned before the entire git checkout is broken again and will take hours to reconfigure. Are you able to change it ?

**Comment by danrossi** [comment]
nothing has changed, ive not touched it in months but each pull attempt I get this

"No submodule mapping found in .gitmodules for path 'modules/headjs'"

**Comment by phloxic** [comment]
@danrossi - I can change it.

**Comment by phloxic** [comment]
Migrated to https://github.com/flowplayer/work/issues/635 - closing here.

**Comment by phloxic** [comment]
@danrossi - I've updated the video location - https://github.com/flowplayer/site/commit/f2947d0765b3fe880c82dac10c09f9fa95afcb27 - and it makes the stream not found error go away successfully.
However, I am stuck in an authentication loop: I enter username and pw in the dialogue only for the dialogue to reappear.
Are the demo plugins supposed to work on flowplayer.org only?

**Comment by phloxic** [comment]
@danrossi - I have to wait until the updated locations are published. Then I'll see whether the demos work on flowplayer.org . If the domain is the problem, it would be nice to have versions which also validate against localhost:8080 at some point.

**Comment by danrossi** [comment]
its not related to domains for drm authentication , once i manage to get into the console i can see whats going on, its been a while since ive logged into it and can't get in right now. they've probably made a change and i need to update the returned license config correctly.

**Comment by danrossi** [comment]
I managed to get a login, and seems the authentication backend service wasn't happy with the db code so ive hardcoded to return the correct certificate config. Should work now. Same with the preauth version.

**Comment by phloxic** [comment]
@danrossi - works now, tested locally, must be published. Closing here.

**Comment by danrossi** [comment]
"No submodule mapping found in .gitmodules for path 'modules/headjs'" how do i fix this ?

**Comment by phloxic** [comment]
@danrosii - Is that about `hyde gen` locally? Probably you have to update the hyde requirements:

```
$ cd site
$ workon fp
$ pip install -U -r requirements.txt
```

**Comment by danrossi** [comment]
no I cant run a git pull to update my location. ive not touched it in months therefore the rep is broken.

**Comment by phloxic** [comment]
@danrossi ? git pull what, where? Which repo?
Just do a fresh clone?

**Comment by danrossi** [comment]
takes too long to setup again ?  no worries.
