### ISSUE TITLE
accel + canvas backgroundGradient breaks UI entirely

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#75]
Demo: http://flowplayer.blacktrash.org/test/accel.html
The controlbar shows on load, then disappears. Screen is entirely unresponsive.

**Comment by ViliusS** [comment]
Ping?

**Comment by phloxic** [comment]
@ViliusS - does this also happen with Flash > 10.x ?

**Comment by ViliusS** [comment]
Yes, 11.x series are affected too.

**Comment by ViliusS** [comment]
As a temporary workaround you can set it to "backgroundGradient: [0, 0]". Hopefully this saves somebody the day.

**Comment by danrossi** [comment]
Hi guys I checked every possible configuration and it does indeed seem to be this display indexing issue again, the stage video mask is displaying above everything, I think this was because the logo was displaying underneath for the commercial version. There is too many different possibilities for this ...

**Comment by danrossi** [comment]
Yes it was to fix #45, if I change the index back to 0, the silly gradient is displayed above the video. I'll have to do somemore research.

**Comment by ViliusS** [comment]
It's strange, that the control bars appear in full screen. Also, it's strange that specifying [0, 0] instead of "none" works. Or does backgroundGradient: "none" means something enterly different?

For what it's worth, I'm currently satisfied with [0, 0] workaround.

**Comment by danrossi** [comment]
The dev revision number has changed now its .3.2.16. Please try this

https://dl.dropbox.com/u/3394987/flowplayer.commercial-3.2.16-dev.zip

When a gradient is set, the display list changes because its adding a sprite on top with the added gradient instead of just manipulating the current "canvas" one directly therefore where the stage video container gets added is dependant on this, when you choose "none" it removes this from the display list. the check seems to help.

**Comment by ViliusS** [comment]
Confirming as fixed in dev code.

**Comment by danrossi** [comment]
Great thanks, sorry this has been ongoing, quite a complicated one where fixes break other fixes etc ;)

**Comment by danrossi** [comment]
leaving this open for release.

**Comment by phloxic** [comment]
This should be checked again after #156 is fixed. Reopening.

**Comment by phloxic** [comment]
Can be tested now by _developers_ themselves at http://flowplayer.blacktrash.org/test/accel.html - it now uses latest build from http://flash.cdn.dev94.flowplayer.us.s3.amazonaws.com/swf/flowplayer-3.2.17-dev.swf
Re-assigning to developers ;-)

**Comment by danrossi** [comment]
keep it here. It has to be peiced back together from the commit logs the changes never got merged it seems.

**Comment by phloxic** [comment]
although not that _this_ issue is originally about `canvas: {backgroundGradient: "none"}` causing trouble, which currently is not the case.

**Comment by danrossi** [comment]
yes, this pull request system did not actually work part the time it needs to be manually put back into place.

**Comment by danrossi** [comment]
https://github.com/flowplayer/flash/commit/295d5f11ac092b246bef19e0246e094f41c9074f beyond my knowledge how to fix this i have no idea where it went.

**Comment by danrossi** [comment]
https://github.com/flowplayer/flash/pull/166 I was able to partially get it back in but its totally hard to track whats what, its in the master branch. The only thing I can find a problem with what I just merged is seeking twice inside a buffered area of http, then going fullscreen the stage mask hasn't reset ... will have to relook at that now

**Comment by danrossi** [comment]
i apparantly fixed this memory leak now so will look at this stage video changes again.

**Comment by danrossi** [comment]
hmm not doing what I was experiencing anymore. 75 definitely fixed this. It was not branched from master to dev correctly.

**Comment by danrossi** [comment]
Just got it, it's reliant on seek complete callback events so stop the stage video moving around while seeking. no callback the event is not enabled again lol. hmm.

**Comment by danrossi** [comment]
ok it's possibly something to do with this seek end timer. the seek event gets dispatched after a delay on http. may have to use a different event.

**Comment by danrossi** [comment]
https://github.com/flowplayer/flash/pull/166 this should fix it. Its a temporary fix though because of this seek event delay timer which I think should be taken out completely, im not sure of it's purpose.

**Comment by danrossi** [comment]
it should be visible once the build is done.

**Comment by anssip** [comment]
Latest fix merged and this is newly built http://flash.cdn.dev94.flowplayer.us.s3.amazonaws.com/swf/flowplayer-3.2.17-dev.swf

Cannot see the issue any more in http://flowplayer.blacktrash.org/test/accel.html  Closing this.

**Comment by phloxic** [comment]
Confirming fix, most of all at http://flash.dev94.flowplayer.us/demos/configuration/accelerated.html
