### ISSUE TITLE
hls not prebuffer video in ie

### ISSUE THREAD

**Issue by vodcms** [flowplayer/flash#76]
chrome is work right. but't in ie(my ie is 8.0). when a part play then be download. bot prebuffer video on next part.

**Comment by ViliusS** [comment]
IE doesn't support HLS.

**Comment by vodcms** [comment]
yes.but i m play hls on flash mode. is not support?

**Comment by ViliusS** [comment]
What do you mean by "on flash mode"? Flash doesn't support HLS too.

**Comment by vodcms** [comment]
flowplayer has a plugin,it support hls on flowplayer with flash. it' work in chrome is perfect. but in ie. have a problem.

**Comment by ViliusS** [comment]
Which plugin do you talking about?

**Comment by vodcms** [comment]
this is https://github.com/flowplayer/flash/tree/master/plugins/httpstreaming-hls

**Comment by danrossi** [comment]
The feature is not officially supported yet, I will have a look when I have a moment.

**Comment by danrossi** [comment]
Hi please contact me directly here http://flowplayer.electroteque.org/contact , the github sources will be taken down and I will be supporting it directly. Closing for now.
