### ISSUE TITLE
audio: time is null in paused state (regression)

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#78]
Same for `$f().getTime()`

Regression introduced in flowplayer.audio-3.2.10, release with core 3.2.13.

See: http://flowplayer.org/forum/#!/moot/8042

**Comment by danrossi** [comment]
Not enough information, no demo supplied. This is working for me

 onPause: function() {
            console.log("onPause " + $f().getTime());
        },

onPause 72.48922902494331

**Comment by phloxic** [comment]
Mate, just look at the audio plugin page http://flash.flowplayer.org/plugins/streaming/audio.html and hit pause.

**Comment by danrossi** [comment]
Ok the time display resets.

**Comment by danrossi** [comment]
not happening in the dev. I have no idea what has / hasn't been released because it was all happening while I was on leave all of a sudden. Ill get to that after I fix all these other issues if possible.

**Comment by danrossi** [comment]
I meant that person didn't supply a demo but thanks, please try this https://dl.dropbox.com/u/3394987/flowplayer.audio-3.2.10.zip

**Comment by danrossi** [comment]
any luck ?

**Comment by phloxic** [comment]
Yes, that seems to work.
A lot of your code doesn't seem to have gone into the release. @danrossi, @anssip - please coordinate. It doesn't make much sense to setup demos, test, etc. when the code then does not go in. If in doubt @danrossi has to `diff -r` his repo against a fresh clone of master before a release. Pedestrian, but less pedestrian than what happened here.

**Comment by danrossi** [comment]
I just got word it hasn't been released live yet the audio plugin that is, the others possibly have. I work in branches no changes on my side, not sure what you are suggesting here ?  It should go out then with the other changes that were just pushed through cheers.

**Comment by anssip** [comment]
Not happening any more with our current dev build: http://flash.dev94.flowplayer.us/plugins/streaming/audio.html

The fix is in the player, the demo in that page uses the old 3.2.10 audio plugin.
