### ISSUE TITLE
bitrateselect: non-ascii characters not accepted for splash labels

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#79]
This might not be confined to this area, but:

``` js
hdButton: {
  onLabel: "вкл On",
  offLabel: "выкл Off"
}
```

does not work.
Neither does escaping them. Or replacing the utf chars with unicode raw bytes:

``` js
hdButton: {
  onLabel: "\u1074\u1082\u1083 On",
  offLabel: "\u1074\u1099\u1082\u1083 Off"
}
```

See: http://flowplayer.org/forum/#!/moot/8137

**Comment by danrossi** [comment]
Its because the asset uses an embedded font. I think for the sake of reducing its filesize it doesnt use embedded fonts. Adding extra embedding options will increase the filesize of the compile.

**Comment by danrossi** [comment]
specifying to not use embedded fonts makes the text render badly. Need to use embedded fonts. Adding all possibly glyphs makes the plugin compile at 180kb. I dont know what characters those are for but I would have to add them in only and therefore leave other ones out. They could perhaps have a custom compile only instead.

**Comment by danrossi** [comment]
adding the cyrllic characters which I think it is doubles the filesize to 60kb. custom compile I think.

**Comment by danrossi** [comment]
made them a custom build also needed changing the text width because it doesn't understand the width of the characters.

**Comment by phloxic** [comment]
Yeah, cyrillic character are higher than 8 bit, i.e. double width.
So you're saying that non-ascii chars are not available? Or is it some kind of European charset? - Then this must be documented. Japanese, chinese etc. Which font is it?

**Comment by danrossi** [comment]
Its using embedded text for the font for that asset. we'd have to make it non emebdded to use system fonts but the rendering will become pixelated. We could make two versions perhaps to easily internationalise it ?

**Comment by danrossi** [comment]
i compiled them quickly a version with the cyrillic glyphs added they have to be added specifically and compiled in which increases the size.

**Comment by danrossi** [comment]
closing this for now not much can be done unless the text label is changed to not embedded and therefore doesn't render smoothly.
