### ISSUE TITLE
3.2.16 - stopping live stream make screen go blank

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#81]
I would expect this to be caused by the changes to the rtmp plugin, but using core 3.2.15 + rtmp 3.2.12 brings back the old behaviour which is certaintly nicer for the viewer.
Can be observed e.g. here: http://flowplayer.blacktrash.org/test/live.html

**Comment by danrossi** [comment]
not happening in https://dl.dropbox.com/u/3394987/flowplayer.commercial-3.2.16-dev.zip

**Comment by danrossi** [comment]
any luck ?

**Comment by phloxic** [comment]
I guess this is another case of https://github.com/flowplayer/flash/issues/78#issuecomment-14726655

**Comment by danrossi** [comment]
This would be the core, I guess it hasn't been released yet either. I don't manage those please consult with @anssip .

**Comment by phloxic** [comment]
@danrossi - you consult with @anssip - you both speak English, you don't need a translator.

**Comment by danrossi** [comment]
All the pull requests that built up possibly with these fixes and were merged last month should be in the dev branch possibly, everything is going to the dev branch now https://github.com/flowplayer/flash/tree/dev. I was not around when it was happening last time. Some more merges just happened today. I have to provide the zips for you because I don't manage the dev zips either.

**Comment by danrossi** [comment]
So to my knowledge none of it has been released yet and should do now with these extra changes after its gone to the testing site.

**Comment by phloxic** [comment]
See also: http://flowplayer.org/forum/#!/setup#at-stream-when-i-pause-to

**Comment by danrossi** [comment]
pausing a live stream will stop it by default. stopLiveOnPause: false on the clip property try that.

**Comment by phloxic** [comment]
Never heard about `stopLiveOnPause` before, but, yes it pauses displaying the last frame - unfortunately it does not resume: http://flowplayer.blacktrash.org/test/live.html

**Comment by danrossi** [comment]
cant see logs but likely a pause event is not firing. I think that config is there is because you cant entirely pause a live stream i think. It will simply timeout related to the idle settings on the server.

**Comment by phloxic** [comment]
Whatever. Currently the expected behaviour is happening with core 3.2.15 - no blank screen.

**Comment by phloxic** [comment]
With HDS still a problem in 3.2.17 dev:
http://flash.dev94.flowplayer.us/demos/plugins/streaming/bwcheck-hds-live.html
Works with 3.2.15 core:
http://flowplayer.blacktrash.org/test/bwcheck-hds-live-3215.html

**Comment by phloxic** [comment]
With RTMP and 3.2.17 dev _pausing/stopping_ works as expected - screen not blank, but you cannot resume:
http://flowplayer.blacktrash.org/test/live.html
As already mentioned above: https://github.com/flowplayer/flash/issues/81#issuecomment-26196934

**Comment by danrossi** [comment]
confirming it's not resuming probably because an event is not firing on pause.

**Comment by danrossi** [comment]
wow no idea whats happened there, but after resuming its stopping because there is no duration. I'm fairly certain it was resuming .. This is on the core not rtmp plugin.

**Comment by danrossi** [comment]
I didn't think so it doesn't resume the stream it's not vod. this would only work for dvr most likely. Thats why that feature to stop on pause is in there. @anssip leave it ?

**Comment by anssip** [comment]
We cannot leave it like this. Of course it needs to be able to resume.

**Comment by danrossi** [comment]
The default is to stop and then when click to play it starts again, thats what you had put it anyway. "resume" does not work the stream just hangs, it may have to trigger "load" as "play" just makes the player go into finish state in my hacks.

**Comment by danrossi** [comment]
It will be doing exactly the same thing so not sure if this is necessary. It cannot pause / resume with live rtmp. Perhaps close the stream but leave the video display open, it's a cosmetic request.

**Comment by danrossi** [comment]
what we can possibly do is disable this duration tracker, then it will allow to call resume. And in resume on rtmp check if its live , stop the stream and reload it.

**Comment by anssip** [comment]
> what we can possibly do is disable this duration tracker, then it will allow to call resume. And in resume on rtmp check if its live , stop the stream and reload it.

This sounds like a reasonable approach. Maybe the duration tracker can also check if it's live and there's no duration ---> allow resume. Or duration tracker can be completely disabled with live streams.

And with RTMP live it internally does what's necessary just to make it continue.

**Comment by anssip** [comment]
In my opinion it does not really matter if the screen goes blank when pressing the pause button. That is just cosmetics. The main thing is that pause and resume works!

> It will be doing exactly the same thing so not sure if this is necessary. It cannot pause / resume with live rtmp. Perhaps close the stream but leave the video display open, it's a cosmetic request.

This also makes sense. I think we used to do just that: close the stream when it's live. Not sure if with this approach it's possible to not have the screen going blank.

**Comment by danrossi** [comment]
It does work by default Stopping and starting.

**Comment by danrossi** [comment]
stopping makes the video display hide hence the ticket. so no can't be paused/resumed like a vod.

**Comment by phloxic** [comment]
Why does it work in 3.2.15?
Users are - still - surprised by new behaviour.
Again: it works in 3.2.15 core with 3.2.12 rtmp: http://flowplayer.blacktrash.org/test/live-3215.html
@anssip - that's why you had to special build a 3.2.15 Unlimited.
Now checking whether the obscure `stopLiveOnPause` makes any difference.

**Comment by phloxic** [comment]
3.2.17 and `stopLiveOnPause`:
- not set, i.e. default (I don't know the default value): blank screen on pause
- `true`: same as before, I infer `true` must be the default
- `false`: shows current frame on pause, but player cannot resume

Users certainly just want the behaviour of 3.2.15 core, not additional option needed.

**Comment by anssip** [comment]
Well if this was working properly in 3.2.15 then it's certainly possible to fix the issue :-) Perhaps just diff with the 3.2.15 tagger version to see what has been changed. @danrossi let me know if you want me to take a look at this. We need to stop discussing this issue over and over and just fix it!

**Comment by danrossi** [comment]
I certainly don't see anything to fix so be my guest Ive just been wasting my time to fix what is not broken. Its simply pause on live stops the stream, the screen goes black. You press play again, it reconnects and begins playback again.

**Comment by anssip** [comment]
This is now fixed. @blacktrash, please verify with the version in dev.

**Comment by phloxic** [comment]
Confirmed :+1:

**Comment by Elegent** [comment]
how to merge clips stream to one video play

**Comment by phloxic** [comment]
@Elegent - please do not swamp the bug tracker with
- a usage question, that's what our forums - https://flowplayer.org/forum/  - are for
- a repeated question in short intervals
- which is completely off-topic regarding this (fixed) bug as well

P.S. you are probably looking for how to combine rtmp streams: http://flash.flowplayer.org/plugins/streaming/rtmp.html#combining-streams

**Comment by danrossi** [comment]
Hi you want the streams config it will initiate a server side playlist.
