### ISSUE TITLE
Add "getBitrate" to bitrateselect

### ISSUE THREAD

**Issue by danrossi** [flowplayer/flash#82]
See https://github.com/flowplayer/flash/issues/71#issuecomment-14170244

**Comment by phloxic** [comment]
Not requested by me - more docs ;-) I need you here: https://github.com/flowplayer/work/issues/636

**Comment by danrossi** [comment]
https://dl.dropbox.com/u/3394987/flowplayer.bitrateselect-3.2.13.zip 

There is a few options but the first two does not get updated by the javascript api

```
console.log($f().getClip().bitrate);
console.log($f().getClip().mappedBitrate);
console.log($f().getPlugin("brselect").getCurrentItem());
console.log($f().getPlugin("brselect").getBitrate());
```
