### ISSUE TITLE
why remove hls plugin?

### ISSUE THREAD

**Issue by vodcms** [flowplayer/flash#86]
it's a very good feature. just have small problem work at IE. pls keep is thks.

**Comment by danrossi** [comment]
Hi i'm releasing it myself its available here now http://flowplayer.electroteque.org/httpstreaming-hls

**Comment by danrossi** [comment]
closing this

**Comment by danrossi** [comment]
Can't see your comment. Not part of Flowplayer although it was going to be, not free anymore. Supported on my page. Have made a tonne of improvements.
