### ISSUE TITLE
3.2.16 regression: rtmp live audio - no audio

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#87]
This demo http://flowplayer.blacktrash.org/test/audio-live.html
- works with core 3.2.15 and rtmp 3.2.11 (before last release)
- does not work with core 3.2.16 and rtmp 3.2.12 (last release)
- works with core 3.2.5 (before last) and rtmp 3.2.12( (last)

@anssip, @danrossi - guess that's another case for release coordination?

**Comment by danrossi** [comment]
http://flowplayer.dev/test/audio-live.html is this the staging site ? It is down that is all.  Possible to check the staging site if possible ? All fixes have been pushed there by now I believe.

**Comment by phloxic** [comment]
Sorry, sorry, I sometimes paste the virtual domain for local testing - http://flowplayer.blacktrash.org/test/audio-live.html - working sample with core 3.2.15. Does not work with core 3.2.16.

**Comment by danrossi** [comment]
all ok with this https://dl.dropboxusercontent.com/u/3394987/flowplayer.rtmp-3.2.12.zip

**Comment by phloxic** [comment]
We'll leave this open until the next release is out - hopefully fixes itself.

**Comment by danrossi** [comment]
Yes. I cannot guarantee when. I've just applied more httpstreaming and bwcheck fixes so I guess now but ive had no response myself and they should be up on the dev build site location right now.

**Comment by phloxic** [comment]
Cannot repro anymore. Works here: http://flash.flowplayer.org/demos/plugins/streaming/audio-live.html
