### ISSUE TITLE
3.2.16 bitrateselect + pseudostreaming broken (regression)

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#88]
See http://flowplayer.blacktrash.org/test/issue88.html
Works with RTMP.
Like with #81 and #87 and possibly others this regression seems to be caused by a change in core 3.2.16, not in the new plugin version 3.2.13: brselect 3.2.13 with core 3.2.15 does not have the problem.

EDIT: update, does not work at all, starts from beginning.

**Comment by phloxic** [comment]
Here's the exact same setup with core 3.2.15 - works: http://flowplayer.blacktrash.org/test/brselect-pseudo.html

**Comment by danrossi** [comment]
the page is broken. cannot see an issue with this https://dl.dropboxusercontent.com/u/3394987/flowplayer.pseudostreaming-3.2.12.zip

**Comment by phloxic** [comment]
What page is broken?

**Comment by danrossi** [comment]
https://dl.dropboxusercontent.com/u/3394987/flowplayer.pseudostreaming-3.2.12.zip it will update after switching with this now.

**Comment by phloxic** [comment]
Note to self: devel pseudostreaming plugin which fixes this at http://flowplayer.blacktrash.org/dev/flowplayer.pseudostreaming-3.2.13-dev.swf

**Comment by phloxic** [comment]
3.2.17 dev can be tested now at http://flowplayer.blacktrash.org/test/issue88.html - currently looks ok.
