### ISSUE TITLE
bitrateselect + menu: menu does not reset to default bitrate on onStop

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#9]
http://flowplayer.blacktrash.org/test/brmenu.html

Start playing (default 750 kbps), switch to a visibly different resolution (400 kbps), wait until it's selected, click stop.
Click play, and the clip plays at isDefault of 750 kbps, but menu stays at 400 kbps.
After that also switching to yet another bitrate has no effect.

**Comment by danrossi** [comment]
stop is stopping the stream therefore resetting it as if its being reloaded. I'll have a look at the switching problem though.

**Comment by danrossi** [comment]
Ok i see the problem no worries.

**Comment by danrossi** [comment]
some things need to be reset once stop is called. this is so the bitratelist isn't being set more than once.

**Comment by danrossi** [comment]
stop doesn't actually stop the stream either so something up with pseudo.

**Comment by danrossi** [comment]
Now I figured out how this works, I'm not seeing the issue im afraid. Its resuming the stream not actually close and restarting everything so it plays back from the currently selected bitrate doesn't reset back to default ?

**Comment by danrossi** [comment]
probably have to skype it.

**Comment by danrossi** [comment]
Just tested against both rtmp and pseudo,  it replays to current playing clip.

**Comment by phloxic** [comment]
It resets to default 750. But the menu stays at 400 (or whatever the last selection was before stopping). And you cannot switch anymore.

**Comment by danrossi** [comment]
We might have to skype this im afraid, I don't see this.

**Comment by danrossi** [comment]
Unless its actually resetting fot you because for me it pauses and resumes.

**Comment by phloxic** [comment]
This is about _stop_, not replay, or resume - leftmost button.

**Comment by danrossi** [comment]
skype

**Comment by danrossi** [comment]
ok confirming at times when resuming the stream from stop its replaying the original played video. im seeing something bizarre with http streaming also and possibly within the screen where it updates the displays.

**Comment by danrossi** [comment]
I found partially your issue, the netclient which captures the rtmp callbacks is being reset on a stop call so resuming is silenced. Im assuming so when resuming no metadata event is triggered ??

**Comment by danrossi** [comment]
Please try this when you have a moment, might need to have a chat about it first

https://dl.dropbox.com/u/3394987/flowplayer.commercial-3.2.14.zip

**Comment by danrossi** [comment]
Let me know if that fixes your problem.

**Comment by phloxic** [comment]
Callbacks now seem to work after restarting.

The bitrate it restarts on still varies: Sometimes it stays on the last chosen bitrate. Sometimes it restarts on the default bitrate and switches to the last chosen bitrate by itself - usually after the first stop, you can see it in the logs.

http://flowplayer.blacktrash.org/test/brmenu.html now uses your dropbox file and all the latest plugins, if needed from releases.flowplayer.org.

**Comment by danrossi** [comment]
I tried to start and stop on a 400 clip and always begins playing the 400 clip and is visible in the logs. The only way to tell really properly is having bitrate watermarks on the videos :( Might have to skype about it again sometime.

**Comment by danrossi** [comment]
I tried a heap of options still can't get it to display that transition event when resuming from being stopped. It's not reinitialising anyone just resuming the stream. it keeps returning the pixelated 400k file for me. I guess this is some random server issue, because I do indeed see it on your end but it will transition back to 400. From what I can see before it resumes the stream it also runs a seek back to zero so perhaps this also has something to do with it, resetting the transition mode from before.

**Comment by danrossi** [comment]
What do we do about this one I can't get it replicated here.

**Comment by phloxic** [comment]
We can close this here.

In most cases no-one will notice ;-)

Regarding the onSelect, onStreamSwitchBegin and onStreamSwitch events, I will try to find out whether there is a way to create a setup using global vars which makes the status messages reflect what's actually going on. It might be nice to not only use the for debugging purposes, but in a way I've already outlined in my demo.

If I come across an issue which can be reliably reproduced, I'll file another bug ;-)
