### ISSUE TITLE
ova mid-roll ad

### ISSUE THREAD

**Issue by mohammadagha** [flowplayer/flash#91]
Hi
I am trying to use mid-roll ad (example: http://telewebion.com/flowplayer/vod_ova.html )
the mid-roll ad is configured to run 3 seconds into the stream.

The problem is that the main video stays on top and the ad is invisible even though it plays.

we are using octoshape provider which might be the reason but I suspect there should be some config to avoid this.
BTW, pre-roll is just fine.

**Comment by ViliusS** [comment]
Another variation of this bug https://github.com/flowplayer/flash/issues/44 comment number 33.

**Comment by mohammadagha** [comment]
so, is there any solution to this problem? I also upgraded to 3.2.16 and still have the problem.

**Comment by mohammadagha** [comment]
BTW, this is not just an OVA issue. I reproduced it with instream:
http://telewebion.com/flowplayer/instream.html

**Comment by mohammadagha** [comment]
I narrowed it down to the provider that we use: octoshape.
When my main clip is a normal http file then the instream/ova plays fine. When it is octoshape, we have this issue.

Do you have any advise on how to fix this? Is there some css or something like that that specifies z-index or similar properties?

**Comment by ViliusS** [comment]
At least for me (considering if that's the same issue), setting accelerated to false fixes the problem. However to really fix the issue that needs to be fixed in Flowplayer OR OVA. I contacted Paul from OVA multiple times regarding this issue and he mainly said that it's a bug in Flowplayer. Another discussion and Paul's answer http://code.google.com/p/flowplayer-core/issues/detail?id=608

Maybe you can contact OVA and see if you have more luck? If they again confirm that this is a bug in Flowplayer maybe Flowplayer developers will look into it again.

**Comment by mohammadagha** [comment]
I tried accelerated=false and other values for wmode didn't help.
It's not an OVA issue as I have same issue with instream clips. see http://telewebion.com/flowplayer/instream_100tb.html , at seconds 5 is plays instream.

can you guide me for more temporal solutions?
like can I reduce the size of the playing video so it's image will be small once the instream clip is playing?

**Comment by mohammadagha** [comment]
btw, I cannot set canvas property. is it something only available in commercial version?

**Comment by ViliusS** [comment]
I don't think there is a workaround in your case. If two pluging, OVA and Octoshape behaves the same, then it's probably a bug in Flowplayer.

**Comment by mohammadagha** [comment]
is there anyway to get a quick support from flowplayer on this? if we get a comercial version. it's so important to us.

**Comment by ViliusS** [comment]
I'm not speaking for Flowplayer, but you can try buying a support ticket http://flowplayer.org/support/. If it will help or not, it's hard to tell :)

**Comment by mohammadagha** [comment]
one more finding:
in fact no screen setting (such as opacity) works.
See http://telewebion.com/flowplayer/instream_100tb.html where I have set
opacity to 0.1. If I use another stream (e.g. a http file) it works.
So, do you think if it is my provider problem (octoshape) or there is some
setting per provider/plugin?
--  Mohammad

**Comment by danrossi** [comment]
Have you tried a normal video at all, http ? You just said its your custom stream provider that is causing the issue its not related to the stage video config bug with Ova which I dont know if or when its been updated. If we cant get the sources to the custom stream provider we can't help. First try a normal video if possible.

**Comment by mohammadagha** [comment]
As I mentioned in earlier posts I don't have issues with http streaming.
I also talked to my provider (octoshape) this morning and this issue is
special to them: what they do is that they put their video on top so that
no element can block it (they need to show a dialoge box to user asking to
instlal a plugin).
I wonder if there is anyway I can disable this behavior or not. Please
advise.
--  Mohammad

**Comment by danrossi** [comment]
You are going to have to interface with them I'm afraid, we can't support that plugin. It is indeed seem to be interfering with the display. If there was source code I could assist.

**Comment by danrossi** [comment]
did you manage to resolve this at all ?

**Comment by danrossi** [comment]
Hi closing this for now, not possible to support this sorry, please contact longtail and the provider vendor about the issue.
