### ISSUE TITLE
Compile Warning about static-link-runtime-shared-libraries

### ISSUE THREAD

**Issue by luoyx08** [flowplayer/flash#93]
I use flex4.5 to compile flowplayer3.2.16 successfully but it has warning when compile plugin. Following the prompts, i modify static-runtime-shared-libraries attribute in my flex-config.xml to true but it doesn't change. my compiled flashplayer can work but what does the warning mean and how to fix it?Thanks!

**Comment by danrossi** [comment]
Hi there has been structural changes on github you need to checkout the flash-build repo now. I dont have access to fix the build file yet but these are the flags to remove the warnings. Its got something to do with a preloader frame

```
<arg line="-static-link-runtime-shared-libraries=false"/>
                <arg line="-generate-frame-loader=false"/>
```

**Comment by danrossi** [comment]
This has been committed and will close this. Please add these to your file or grab it from here

https://github.com/flowplayer/flash-build/blob/danielr/plugin-build.xml

**Comment by luoyx08** [comment]
thanks! it does help!

**Comment by danrossi** [comment]
It's ok its an error something to do with missing default preloaders. It's specific to flex based applications which this isn't. Compiling in the shared libraries would make the plugins huge so not a good idea ;)
