### ISSUE TITLE
acessibility: widgets need labels

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#96]
According to http://flowplayer.org/forum/#!/moot/9763 the widgets need not only to be highlighted when tab-selected, they also need labels.

`controls.tooltips.buttons: true` makes the labels appear on hover only, maybe they can be made to appear when the widget is tab selected in conjunction with SeemlessTabbing: "false"?

There's also a minor config syntax issue: Normally the JS flash configuration accepts unquoted keywords, like `false`, in this case it must be quoted `"false"`` to work.

**Comment by danrossi** [comment]
Unless something has changed it does work and confirmed by a few users about a year ago now. Will have to install the program again and test will take a while. The accessbility options get added and named from the widget name its not related to the tooltip label but can make it use that if the label is enabled.

**Comment by danrossi** [comment]
functions fine with jaws. the download kept timing out took a while.
