### ISSUE TITLE
build fails due to plugin-build.xml error

### ISSUE THREAD

**Issue by erentantekin** [flowplayer/flash#97]
compile:
     [echo] compiling with  ../viralvideos/src/flash src/flash ../../lib/common/src/flash
     [echo] compiling with  
     [exec] Loading configuration file /opt/flex-sdk/frameworks/flex-config.xml
     [exec] /home/dev/flash/plugins/viralvideos/src/actionscript/org/flowplayer/viralvideos/PlayerEmbed.as: Error: Can not resolve a multiname reference unambiguously. JSON (from /opt/flex-sdk/frameworks/libs/player/11.1/playerglobal.swc(JSON, Walker)) and com.adobe.serialization.json:JSON (from /home/dev/flash/core/build/flowplayer.swc(com.adobe.serialization.json:JSON)) are available.
     [exec] 
     [exec] /home/dev/flash/plugins/viralvideos/src/actionscript/org/flowplayer/viralvideos/PlayerEmbed.as(113): col: 33 Error: Access of undefined property JSON.
     [exec] 
     [exec]                 _playerConfig = JSON.decode(configObj);
     [exec]                                 ^
     [exec] 
     [exec] /home/dev/flash/plugins/viralvideos/src/actionscript/org/flowplayer/viralvideos/PlayerEmbed.as(232): col: 46 Error: Access of undefined property JSON.
     [exec] 
     [exec]                 configStr = escaped ? escape(JSON.encode(conf)) : JSON.encode(conf);
     [exec]                                              ^
     [exec] 
     [exec] /home/dev/flash/plugins/viralvideos/src/actionscript/org/flowplayer/viralvideos/PlayerEmbed.as(232): col: 67 Error: Access of undefined property JSON.
     [exec] 
     [exec]                 configStr = escaped ? escape(JSON.encode(conf)) : JSON.encode(conf);
     [exec]                                                                   ^
     [exec] 

BUILD FAILED
/home/dev/flash/core/build.xml:338: The following error occurred while executing this line:
/home/dev/flash/core/build.xml:354: The following error occurred while executing this line:
/home/dev/flash/lib/devkit/plugin-build.xml:218: The following error occurred while executing this line:
/home/dev/flash/lib/devkit/plugin-build.xml:32: The following error occurred while executing this line:
/home/dev/flash/lib/devkit/plugin-build.xml:209: The following error occurred while executing this line:
/home/dev/flash/lib/devkit/plugin-build.xml:84: exec returned: 4

**Comment by anssip** [comment]
We have the latest code now in the 'dev" branch. All build files have been moved to a new module called 'flash-build': https://github.com/flowplayer/flash-build (master branch here).

Please checkout the dev branch of the flash module and master branch of flash-build. Then in flash-build run ant.

**Comment by Qambar** [comment]
i am still getting this error here

compile-lib:
     [echo] running /Users/Qambar/Work/Library/flex_sdk_4.6/bin/compc with classpath ../flash/core/lib/corelib/src ../flash/core/lib/goasp/src_go ../flash/plugins/controls/src/actionscript ../flash/lib/common/src/actionscript ../flash/core/src/actionscript-builtin, using manifest manifest.xml
     [exec] Loading configuration file /Users/Qambar/Work/Library/flex_sdk_4.6/frameworks/flex-config.xml
     [exec] Error: could not find source for class com.adobe.serialization.json:JSONforFP in namespace http://flowplayer.org/flowplayer/2008.
     [exec] 

BUILD FAILED
/Users/Qambar/Work/elexutvflash/flash-build/build.xml:240: The following error occurred while executing this line:
/Users/Qambar/Work/elexutvflash/flash-build/build.xml:248: exec returned: 1

**Comment by danrossi** [comment]
You might need to switch to the dev branch, as there was a change for some reason of the json classes to avoid conflict with Flex 4.6 although it's not neccessary as specifying the package is enough. 

https://github.com/flowplayer/flash/tree/dev/core/lib/corelib/src/com/adobe/serialization/json

Please checkout the dev branch and confirm you have that specific file in there. 

I would recommend this branch though as its the most up to date

https://github.com/flowplayer/flash/tree/danielr-httpstreaming/core/lib/corelib/src/com/adobe/serialization/json

**Comment by danrossi** [comment]
closing this for now as the dev branch has all been merged.
