### ISSUE TITLE
captions: cannot show, hide, css etc.

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#98]
``` js
$f().getPlugin("captions").hide();
```

throws this error:

```
"Error in Actionscript. Use a try/catch block to find error."
```

In spite of the method being defined. Console:

```
>>> $f().getPlugin('captions').hide
function()
```

Similarly for all display methods. Doing:

```
$f().getPlugin('captions').display = "none";
```

does not throw an error, but has no effect either.

**Comment by phloxic** [comment]
Related: #41

**Comment by anssip** [comment]
There's now external methods showButton() and hideButton() in the version currently in our dev site. These methods can be used to show and hide the CC button.

hide(), show() are only supported for the captionTarget (content plugin).

**Comment by phloxic** [comment]
Closing in favour of #41.
