### ISSUE TITLE
bwcheck-httpstreaming: erroneous diagnostics

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#99]
http://flowplayer.blacktrash.org/test/bwcheck-httpstreaming.html
Seems to work fine.
But the return values of the onStreamSwitch events do not reflect the actual bitrates.

Furthermore:
- onBwDone always reports -1 - in what circumstances does this work?
- without a reasonable result from onBwDone, how can dynamic: false work?

The following properties seem to have no effect:
- live - duration is always shown (why?)
- netConnectionUrl
- serverType ? it's http, what am I missing?

**Comment by danrossi** [comment]
#70 fixes the duration reporting for a pure live stream it will be removed within the metadata event, the osmf feature sends a duration. For dvr it should dispatch and keep updating the duration on a dvr event.

**Comment by danrossi** [comment]
Is this stream from a user http://itv08.digizuite.dk/tv2b/ngrp:ch1_all/manifest.f4m ? 

The test stream we use is from the demos, notice the bitrate order, lowest to highest, that one is non standard highest to lowest. I will try to run a sort order in the f4m plugin if it's not doing it in the parser. 

http://stream.flowplayer.org/httpstreaming/sample1.f4m

**Comment by danrossi** [comment]
The config is all wonky you need checkOnStart which is disabled so the check won't run, if you want to choose a default it needs to be selected in the bitrates config which should be as normal bitrates: [ { bitrate: 400, isDefault: true } ]. Actually I just checked and it won't pickup the default property that needs to be added in. dynamicBuffer is only useful when checking on startup. the live config goes into the clip config not bwcheck. Will test this feed now

**Comment by danrossi** [comment]
The config is all wonky you need checkOnStart which is disabled so the check won't run, if you want to choose a default it needs to be selected in the bitrates config which should be as normal bitrates: [ { bitrate: 400, isDefault: true } ]. Actually I just checked and it won't pickup the default property that needs to be added in. dynamicBuffer is only useful when checking on startup. the live config goes into the clip config not bwcheck. Will test this feed now

**Comment by danrossi** [comment]
There is nothing wrong with these, it is reporting ok. serverType is http by default. use checkOnStart to begin detection. 

https://dl.dropboxusercontent.com/u/3394987/flowplayer.bwcheck-httpstreaming-3.2.13-dev.zip
https://dl.dropboxusercontent.com/u/3394987/flowplayer.f4m-3.2.10-dev.zip

add default option like so should work now

bitrates: [
                { bitrate: 259},
                { bitrate: 405, isDefault: true},
                { bitrate: 894},
                { bitrate: 3064}
]

**Comment by phloxic** [comment]
When we went through the differences between bwcheck and bwcheck-httpstreaming for documentation you told me, there was no checkOnStart for this plugin.
Updated demo, and it returns empty for detected bitrate.

I can see the non-standard order (not documented) influencing the _first_ choice. But if you watch and toggle fullscreen you can often see it choosing a correct high resolution but reporting a low one.

live is a property _you_ had documented for the plugin, that's why I put it there. And it's also there fore the clip.

I'm afraid you have to walk through all the documented options for me (again) and tell me which are valid, and in what circumstances, and which are missing. The sampel config is the result of pure guesswork. The _docs_ are wonky. That's why I'm asking you for clearly listed concise input.

**Comment by phloxic** [comment]
Will remove live property from bwcheck-httpstreaming docs. checkOnStart still unclear.

**Comment by danrossi** [comment]
It activates manual bandwidth checking before startup if disabled it will use the default setting or the lowest rate. We can enable it by default perhaps if dynamic is not set.

**Comment by phloxic** [comment]
No, that's not what I'm talking about. And leave that as it is - as with the stock bwcheck.
But independently of checkOnStart you can see it selecting a higher bitrate after the default bitrate (correct) and just before the switch (which actually happens visibly) it says that it will select the lower bitrate (which it correctly does not).
Here's the demo without checkOnStart: http://flash.flowplayer.org/demos/plugins/streaming/bwcheck-hds-live.html

And do I need netConnectionUrl in this case? According to my testing it did not seem to make any difference. And if not, why not?

**Comment by danrossi** [comment]
netConnectionUrl is the file to download to calculate bandwidth for http or the rtmp server url.

**Comment by danrossi** [comment]
The production server doesn't have the httpstreaming changes yet of course its in those files above. Hopefully they go up soon ive done some more tweaks to the code and think it's ready and have asked it get all merged.

**Comment by danrossi** [comment]
The production version is broken i fixed it in dev with the osmf 2.0 changes.

**Comment by phloxic** [comment]
ok, fingers crossed ;-)

**Comment by danrossi** [comment]
yes. it's fixed in those files above as far as i've tested it, it has gone out to someone already but have no heard back from them. If you need a demo page lemme know.

**Comment by ashconnell** [comment]
My current setup with bwcheck-httpstreaming grabs the lowest bitrate first (250) and takes roughly 10 seconds to switch to 4000). How might I set my default bitrate to start at something significantly higher than a blurry screen for 10 seconds?

I will happily paypal someone a beer or two for an answer...

**Comment by danrossi** [comment]
Hi there see example above, this configuration chooses which to use as default, it needs to reflect your bitrate list though. 

clip: {
   bitrates: [
{ bitrate: 259},
{ bitrate: 405, isDefault: true},
{ bitrate: 894},
{ bitrate: 3064}
]

}

**Comment by danrossi** [comment]
Hang on are you using the dev sources ? Please use the dev versions pasted above. or my branch has all the above fixes thanks

https://github.com/flowplayer/flash/tree/danielr-httpstreaming

**Comment by ashconnell** [comment]
I'm using the files on the flowplayer site. Will have a look at work tommorrow. Please email me your PayPal details

**Comment by ashconnell** [comment]
I get an f4m error using the plugins posted above. Error 1006.

**Comment by danrossi** [comment]
post link
